### ISSUE TITLE
Testing classes does not work well when combined with Puppet::Parser::Functions.function()

### ISSUE THREAD

**Issue by tokkee** [rodjek/rspec-puppet#100]
Given the following setup:
 - custom module
 - custom (rvalue) function in the module's lib/puppet/parser/functions/
 - a class in that module calling the function

Now, when rspec-testing that the function exists using a call to Puppet::Parser::Functions.function('foo') any *class* tests that include a call to the function will fail with "Function 'foo' does not return a value". This only happens if the function test is executed before the class test:

  rspec spec/functions/foo_spec.rb spec/classes/foo_spec.rb # -> fails
  rspec spec/classes/foo_spec.rb spec/functions/foo_spec.rb # -> works

Apparently, executing the function check has some side effects affecting the Puppet parser that persist throughout multiple checks.

The following tarball includes a minimal sample triggering the issue: http://osprey.tokkee.org/~tokkee/tmp/rspec-test.tgz

I'm not sure if this is due to some Puppet parser issue. However, imho, rspec tests should behave in the same way no matter in which order they are executed. Note, that when simply running "rspec" (without arguments) in the module's directory, the behavior is totally random; apparently depending on the order in which readdir() returns the "functions" and "classes" subdirectories.

**Comment by DavidS** [comment]
I had to adapt the test case a little bit to get it working with rspec-puppet 2.x, but the problem then was not reproducible. Therefore I close this.

Please open a new issue with any further problems you have.
