### ISSUE TITLE
test exported resources

### ISSUE THREAD

**Issue by aswen** [rodjek/rspec-puppet#113]
(this should not be mixed up with: https://github.com/rodjek/rspec-puppet/pull/51)

I would like the following functionality to be added to rspec puppet:

if a manifest has an exported resource rspec should be able to test whether the resource is exported correctly. At the moment rspec can only test for stuff that ends up in the catalogue.

**Comment by logicminds** [comment]
@hunner has there been any enhancements within puppet that might make this easier now since the creation of this ticket?

**Comment by arioch** [comment]
+1 just got bitten by this as well

**Comment by nhinds** [comment]
I'm currently working around this with a little monkey-patching in a support class, which seems to work okay. Could be worth tidying up and including in rspec-puppet? https://gist.github.com/nhinds/32d4fb95d754d075effb

**Comment by ITler** [comment]
+1 would be awesome

**Comment by DavidS** [comment]
@nhinds  that looks intriguing, any ideas whether that works with puppet 4?

**Comment by ITler** [comment]
I'm on Puppet 4 and it works for me.

**Comment by codylane** [comment]
I'm also using puppet 3 and puppet 4, the workaround that @nhinds provided works perfectly!  Thank you!

**Comment by lazyfrosch** [comment]
Should we consider integrating this within rspec-puppet?

**Comment by DavidS** [comment]
@lazyfrosch seeing as this seems to be working in the field, it would be great to have that properly integrated and test covered, instead of a flying monkey patch. Sadly I can currently provide only cycles for code review & releases.

**Comment by lazyfrosch** [comment]
@DavidS you mean in Puppet core? This won't allow tests with older Puppets.

**Comment by DavidS** [comment]
@lazyfrosch here in rspec-puppet

**Comment by aswen** [comment]
Thanks everyone, especially @nhinds for fixing this!
