### ISSUE TITLE
only_with README example doesn't mention namevar is added as a parameter

### ISSUE THREAD

**Issue by 3flex** [rodjek/rspec-puppet#133]
A bit of a gotcha with the new `only_with` matcher (the README and the gh-pages docs examples suffer from this too).

I have this manifest:

``` puppet
user { 'luke':
  ensure => 'present',
  uid    => '501',
}
```

And this test (from the README):

``` ruby
require 'spec_helper.rb'

describe 'test' do
  it do should contain_user('luke').only_with(
    'ensure' => 'present',
    'uid'    => '501'
  ) end
end
```

And I get this output:

> expected that the catalogue would contain User[luke] with exactly 2 parameters but the catalogue contains 3

I realised that the namevar is added as a parameter. Test should be:

``` ruby
it do should contain_user('luke').only_with(
  'name'   => 'luke',
  'ensure' => 'present',
  'uid'    => '501'
) end
```

Don't know how best to explain in the docs.

**Comment by alexharv074** [comment]
@DavidS looks like this fell into the cracks.  I just hit this for the first time.  I'd be happy to update the documentation, although it looks like a bug to me.
