### ISSUE TITLE
Functions not found on Puppet 3.0.x

### ISSUE THREAD

**Issue by domcleal** [rodjek/rspec-puppet#136]
Testing of classes that call custom functions seems to fail when more than one module in the fixtures modulepath contains a lib/ directory, but only on Puppet 3.0.x with rspec-puppet >= 1.0.0.

Example builds:
https://travis-ci.org/theforeman/puppet-foreman/builds/15218311
https://travis-ci.org/theforeman/puppet-puppet/builds/15183316

I wonder if it's to do with setting `Puppet[:libdir]` in lib/rspec-puppet/support.rb, which rspec-puppet 0.1.6 didn't used to do for class example groups.

There were a load of problems in 3.0.x with loading custom types from libdir too, e.g. http://projects.puppetlabs.com/issues/16277, so it's probably related to that.

Here's a test that shows the problem under 3.0.2: https://github.com/domcleal/rspec-puppet/commit/4d2153f8fdc6f0773648e3ba9110e9b2138d2ac6

**Comment by DavidS** [comment]
That should be fixed by https://github.com/rodjek/rspec-puppet/commit/4efca5cb3afb04b779ec004f4f81f7abdc04fa5c currently sitting in master. It'd be great if you could verify that!
