### ISSUE TITLE
[Coverage] Exclude certain resources from coverage report

### ISSUE THREAD

**Issue by electrical** [rodjek/rspec-puppet#158]
Would be cool to exclude certain resources ( like anchor's ) from the coverage reports as sometimes these can't be tested.

**Comment by cdenneen** [comment]
@DavidS I know this is a bit old but has any work around been found to allow to exclude resources?
I'm having a hell of a time with some "temp" resources being created and are showing as Untouched in my coverage report:

```puppet
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-10yejr8/foo]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-10yejr8]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-1mzkiid/foo]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-1mzkiid]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-5knfi7/foo]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-5knfi7]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-a0jdbo/foo]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-a0jdbo]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-lzuz1h/foo]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-lzuz1h]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-ybxhr4/foo]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T/d20160520-77749-ybxhr4]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq/T]
  File[/var/folders/6n/gmsf88x13k98lwb4z45r1mjr0000gq]
  File[/var/folders/6n]
  File[/var/folders]
  File[/var]
```

**Comment by JBleijenberg** [comment]
So, 1,5 years later and i don't know if you still run into this issue.
But i found a way to apply a filter.
In your  *_spec.rb classes, you can add a filter by adding
```
RSpec::Puppet::Coverage.add_filter(<type>, <title>)
```
For example:
```
RSpec::Puppet::Coverage.add_filter('Accounts::User', 'apache')
```
Would exclude the Accounts::Users resource, with the title 'apache'.

**Comment by Houlistonm** [comment]
Just to drag this out further ... (grin)
The filter mechanism works great, but ... can you support an optional title or a regex in the title.
I need to filter out all 'titles' of a specific type.
add_filter('Accounts::User')
or
add_filter('Accounts::User, '/^AA.*/') - not intended to be a correct pattern, just an example.

**Comment by benningm** [comment]
The Coverage class uses @filter.include?() to check if the resource in the filter list.
So it is just a `==` comparsion.

You can do the following:

```ruby
RSpec::Pupet::Coverage.filters << Class.new do
  def ==(other)
    /nocoverage/.match(other)
  end
end.new
```
