### ISSUE TITLE
[Coverage] Testing defines does not remove them from the coverage report

### ISSUE THREAD

**Issue by electrical** [rodjek/rspec-puppet#159]
When a define is tested in the rspec tests it doesn't seem to be processed in the coverage reports.

See https://travis-ci.org/elasticsearch/puppet-elasticsearch/jobs/17994337

the python define is tested with the different clients but it still shows up in the untouched resources list.

**Comment by DavidS** [comment]
Is that still happening, or did you work around that locally? The link is 404 :-(

**Comment by electrical** [comment]
Hi,

its still happening yeah.
I've solved it for now by adding a check if the define is being called as well.

New link: https://travis-ci.org/elastic/puppet-elasticsearch/jobs/17994337
