### ISSUE TITLE
Relationship matcher caveats?

### ISSUE THREAD

**Issue by jcmcken** [rodjek/rspec-puppet#165]
From playing around with the relationship matchers (e.g. `that_comes_before`), it seems that you can only test direct relationships. For example, if a particular resource explicitly requires another resource, you can test that. But if a resource implicitly requires another resource via a dependency chain (e.g. two hops away), you cannot test this (without explicitly testing each intermediate dependency).

This behavior seems to contradict the error message for relationship matchers ("expected that the catalogue would contain x to come before y in the graph"), which seems to imply that the topological ordering of resources is what's being tested.

Could the documentation be updated to mention this caveat? Or, alternatively, could the error message be clearer about what is being tested?

**Comment by DavidS** [comment]
An implementation of this is being developed here: https://github.com/rodjek/rspec-puppet/pull/261

**Comment by rodjek** [comment]
#261 was merged which implements this.
