### ISSUE TITLE
'run' matcher not exported in v1.0.1?

### ISSUE THREAD

**Issue by coofercat** [rodjek/rspec-puppet#168]
I'm using the 1.0.1 gem from rubygems.org. I have a params_spec.rb file like this:
```
describe 'my_module::params' do
  # Try various permutations of operatingsystemrelease and see what happens
  let(:facts) { {:operatingsystemrelease => '6.4'} }
  it { should run.with_params().and_return({'base_package' => 'my_package'}) }
end
```
when running 'rspec' to test this, it returns:
```
Failures:

  1) my_module::params
     Failure/Error: it { should run.with_params().and_return({'base_package' => 'my_package'}) }
     NameError:
       undefined local variable or method `run' for #<RSpec::Core::ExampleGroup::Nested_2:0x007f08386f07b0>
     # ./spec/classes/params_spec.rb:7:in `block (2 levels) in <top (required)>'
```
I had a look in the code, and it seems like it's all there, but somehow the 'run' matcher isn't exported into my namespace. I tried fully qualifying it (with RSpec::Puppet::FunctionMatchers::Run), but then I got the same error about the "with_params" method. I notice 'run' is the only FunctionMatcher - all the ManifestMatchers seem to work fine.

What can I do to fix this?

**Comment by DavidS** [comment]
@coofercat You are testing a class and the `run` matcher is only for functions. Please use the `compile` matcher and the `contains_` syntax.
