### ISSUE TITLE
(Regression?) if any node tests are defined, class tests require a proper node to be used

### ISSUE THREAD

**Issue by incase** [rodjek/rspec-puppet#169]
As we changed both puppet and puppet-rspec lately, I'm not 100% sure if this is related to the puppet 2.7->3.2 upgrade or the rspec-puppet <1.0 to 1.0.1 upgrade or both. But lately, if you have _any_ node defined in a modules fixtures, we seem to need a default node (or a node matching the local hostname) to be defined for the class tests to work (a let(:node) might also work, haven't tested that yet). 
This used to not be the case.

Failure looks like this in this case:
1) <test description>
    Failure/Error: Unable to find matching line from backtrace
    Puppet::Error:
      Could not find default node or by name with 'a.b.c.d, a.b.c, a.b, a' on node a.b.c.d
    # ./spec/classes/whatever_spec.rb:78

Opening an issue here to raise awareness, basically. It might be working as designed/intended, but it seem this is not documented anywhere.

**Comment by DavidS** [comment]
Is this still a problem with 2.2? If yes, can you post a complete, minimal example that exhibits that problem?
