### ISSUE TITLE
should contain_resource with requires parenthesized condition?

### ISSUE THREAD

**Issue by dayglojesus** [rodjek/rspec-puppet#179]
Given this:

    class foo::bar {
      service { "org.ntp.ntpd": ensure => running }
    }

These two tests should be grammatically equivalent, but produce different results:

    # This test fails, as it should...
    specify do 
      should contain_service("org.ntp.ntpd").with({ 'ensure' => 'stopped' }) 
    end

    # This test passes
    specify do 
      should contain_service("org.ntp.ntpd").with
        { 'ensure' => 'stopped' }
    end

**Comment by DavidS** [comment]
Ruby does not recognise that as a multiline statement and therefore doesn't pass the hash to the function. I'd loath to add defences for that to rspec-puppet.
