### ISSUE TITLE
Switch for --parser=future

### ISSUE THREAD

**Issue by daenney** [rodjek/rspec-puppet#182]
It would be nice if we could instruct rspec-puppet to use the future parser somehow. With 3.5.0-rc1 out the door and future parser and evaluator getting that much closer to being a reality the ability to test modules against it would be very useful and could potentially help unearth bugs in the new parser too.

**Comment by Yuav** [comment]
let(:parser) { 'future' }

**Comment by jesusfidalgo** [comment]
how do I set up rspec-puppet use future parser for testing a specific module or all modules?

**Comment by daenney** [comment]
Please take a look at many of the modules in the Voxpupuli org on Github.
