### ISSUE TITLE
Hiera integration seems flawed

### ISSUE THREAD

**Issue by krancour** [rodjek/rspec-puppet#184]
In the documentation, the section on Hiera integration wraps with this snippet of code:

    ntpserver = hiera.lookup('ntpserver', nil, nil)
    let(:params) { :ntpserver => ntpserver }

I would humbly submit that there is either some ambiguity in the documentation or there is otherwise a flaw in how rspec-puppet's hiera integration is intended to work... possibly both?

In the snippet shown above, it is _test code_ that is retrieving a value from Hiera; not Puppet.  That value is being passed as a parameter to the class under test in the very same way you'd pass any other value if _not_ using Hiera.  The bottom line is that the example does _not_ demonstrate _Puppet_ resolving a value from Hiera.

Is that not possible with rspec-puppet?  Or is this only a flaw in the documentation?

**Comment by DavidS** [comment]
I've updated the docs at https://github.com/rodjek/rspec-puppet#hiera-integration a little bit recently. It'd be great if you could write u a little bit of your experience with hiera testing for the README.
