### ISSUE TITLE
Test that "require => FOO" will (perhaps indirectly) require BAR

### ISSUE THREAD

**Issue by bitglue** [rodjek/rspec-puppet#189]
It's a neat "feature" of puppet that if a class is inside another class, [then requiring the outer class won't require the inner class](http://docs.puppetlabs.com/puppet/latest/reference/lang_containment.html). The solution to this is pretty simple: in 3.4 we have `contain()`, and prior to that, `anchor`. However, expressing the problem that these solutions solve in a test assertion is difficult.

It looks like we can currently assert that there are anchor resources exist, and they have `require => this` and `before => that`, but that isn't directly expressing the requirement, which is that `require => Class['ntp']` will also effectively `require => Service['ntp']` (but you, as a user of the `ntp` class, wouldn't do that, because that would be breaking encapsulation.) The NTP module might like to have a test like this:

``` ruby
describe 'ntp' do
  it { should contain_service('ntp').that_is_contained_by("Class[ntp]") }
end
```

A test such as this would pass even if `Service[ntp]` happens to be in `ntp::service` (an implementation detail) or if the requirement was solved with `contain()` or `anchor`. Thus, it allows us to refactor our manifests while simultaneously asserting that the specified functionality (that I can do `require => Class['ntp']` and expect something reasonable) is maintained.

**Comment by DavidS** [comment]
This should be addressed by #261
