### ISSUE TITLE
compile matcher fails when checking classes targeting windows on posix.

### ISSUE THREAD

**Issue by fessyfoo** [rodjek/rspec-puppet#192]
We're trying to  use the compile matcher on all of our role classes. Our puppetmaster serves windows and linux nodes.   each node definition has one role class assigned.

when trying to compile a windows role, on a ci linux or dev osx machine.  there's inevitably a File resource with a path of the form: `C:\foo.txt`   rspec-puppet fails to compile the class because `File paths must be fully qualified, not 'C:\foo.txt'`  

Any guidance on how to resolve this would be greatly appreciated. 

for those interested I've created a sample project which illustrates the issue:

   https://github.com/fessyfoo/rspec-puppet-windows-issue

**Comment by fessyfoo** [comment]
Just reiterating that the puppetmaster running on linux  does not have a problem compiling catalogs for windows nodes,  so it's very odd that the specs do.    I got lost in the puppet code for this but it almost looked like the puppetmaster and the spec code were calling different catalog complilation paths within puppet.   ...   fuzzy I know.

**Comment by philippvh** [comment]
+1: Same issue happening here.
I tried to apply work-around from @drrb. It works to a point, but there seem to be more dependencies in our case than in the example code. I won't spend time on it currently, just as a note here.

**Comment by mrdima** [comment]
+1 for fixing this

**Comment by mbruntink** [comment]
+1, same issue here.

**Comment by DavidS** [comment]
I've delved deeper into this issue. `puppet master --compile` creates only a so-called 'resource catalog', which is the server-side representation to facilitate network serialization. This does not call into any of the validation methods nor creates a "proper" resource graph.

rspec-puppet on the other hand, needs the resource graph and therefore acts like an agent and converts the resource catalog in a RAL catalog. This starts calling into actual types and therefore hits this validation.

This is documented in https://github.com/puppetlabs/puppet/blob/master/docs/catalogs.md

Stubbing `Puppet::Util::Platform.windows?`, as @drrb can only be a start in this case. On the puppet side alone, there is also `Puppet.features.microsoft_windows?` which needs to be considered. Finally, all types that are used by the catalog need to be checked for things where they access system specific runtime behaviour.

In the end it might be easier to run rspec on an actual windows system for these cases. rspec's metadata support might help here to select tests based on platform.

**Comment by fessyfoo** [comment]
thanks for that explanation.

**Comment by mcasper** [comment]
Would love to see this fixed

For anyone using @drrb's workaround, I had to change `!!Thread.current[:windows?].call` to 
```Ruby
if Thread.current[:windows?]
  !!Thread.current[:windows?].call
else
  false
end
```
to get it to work.

**Comment by fessyfoo** [comment]
@mcasper,  @DavidS  explanation means I think this won't be fixed, without some serious support from the puppet internals.   (and not `rspec-puppet`)  

which leaves you with two choices.  

  - test platform specific manifests on the target platform
  - do the monkey patching hacks. 

fwiw this is the level our hack has grown to:  https://gist.github.com/fessyfoo/5903ceb7c94f067e21e2  we have to selectively pretend to be on windows depending on what part of the code is calling.   it's really dirty.

**Comment by ferventcoder** [comment]
>which leaves you with two choices.

> * test platform specific manifests on the target platform
> * do the monkey patching hacks.

FWIW, there are other issues that make testing on the target platform optimal. 

* Ruby has different defined constants on different platforms (particularly Windows) and I believe certain areas are not even compiled unless Windows. This could possibly have an effect with provider-level validation called from types.
* Windows especially has these differences (like Pathing, Registry, API calls) show up versus other platforms as it mostly comes down to differences based in POSIX against another POSIX, versus POSIX against Windows, and things are not similar enough.

At one point the Puppet team had a way of attempting to test Windows specific stuff when on POSIX platforms, but then it became about determining whether test failures were about the overrides working or the code in question. It appears we've removed the final remnants of the overrides from the Puppet code base. 

Trying to stub things out could become a bit of a challenge (at least wrt types and providers) - you could spend significant time in adding back in missing constants and stubbing code (and code from Windows specific gems) that are available when on Windows. Or in this case with overriding Puppet internals that could later change. The cost over the benefit is definitely something to take into consideration. 

When you test platform specific code against those specific platforms and you have a failure, you have a much better guarantee that it's likely your code (or your test) and not something you need to change with any monkey patches you may have implemented. So you spend a lot less time debugging failed tests.

**Comment by james-powis** [comment]
FYI version 2.2.0 of the rspec-puppet gem works on POSIX

**Comment by james-powis** [comment]
More info... on versions > 2.2.0 the following hack is needed in your spec files:
```ruby
      before :each do
        Puppet[:autosign] = false
        Puppet::Util::Platform.stubs(:windows?).returns true
      end
```

However if you are using puppetlabs/powershell the only way I could get it to work is to stub adding the provider (having the fixture was not enough)
```ruby
      before :each do
        Puppet[:autosign] = false
        Puppet::Util::Platform.stubs(:windows?).returns true
        Puppet::Type.type(:exec).provide :powershell, :parent => Puppet::Provider::Exec do
          def run(command, check = false)
          end
        end
      end
```

Unfortunately this only works for versions < 2.5.0 of rspec-puppet

**Comment by james-powis** [comment]
I have logged yet another issue around this with a pretty in depth investigation... https://github.com/rodjek/rspec-puppet/issues/437

**Comment by rodjek** [comment]
This should now be resolved by #498

**Comment by jessereynolds** [comment]
This seems to be happening again with rspec-puppet 2.6.7, puppet 5.5.6, and the puppetlabs/chocolatey module

**Comment by jessereynolds** [comment]
Oh, ignore me. I was not using double backslashes in my `spec/pre-conditions/variables.pp` file. Once I changed all `\` to `\\` everything is golden. Ie:

```
$choco_install_path = 'c:\\foo\\bar\\choco.exe'
$chocolateyversion  = '0.9.9.8'
```
