### ISSUE TITLE
should be able to access scope that function call was made on

### ISSUE THREAD

**Issue by bodepd** [rodjek/rspec-puppet#193]
rspec-puppet for functions does not support accessing the scope object on which the function was called.

This is required for cases where the function calls another function and you want to stub the results of that function. (b/c you have to stub that function call on the same scope object used for the function call being tested)

**Comment by DavidS** [comment]
This is implemented in 2.2.0: https://github.com/rodjek/rspec-puppet#accessing-the-parser-scope-where-the-function-is-running
