### ISSUE TITLE
Setting Module path is deprecated from 3.6.0 on

### ISSUE THREAD

**Issue by duritong** [rodjek/rspec-puppet#211]
Running rspec-puppet with >= 3.6.0 we get the following warning:

    Warning: Modifying 'modulepath' as a setting is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
       (at /homeduritong/.rvm/gems/ruby-1.9.3-p448@puppet/gems/puppet-3.6.2/lib/puppet/settings.rb:127:in `[]=')

This warning should be addressed so future puppet version will work fine.

**Comment by DavidS** [comment]
I'm running tests against 3.x and 4.x without problems. Please create a new issue, should you encounter specific problems.
