### ISSUE TITLE
Time for a new Gem?

### ISSUE THREAD

**Issue by coofercat** [rodjek/rspec-puppet#213]
Is it time for a new gem build?

I ask because I just spent a few hours trying to figure out how to make a manifest that does a 'split' on a parameter. To try to make my life easier, I used the 1.0.1 gem to unit test it, but it seems that gem doesn't understand the 'split' function (having looked at the source, it seems the latest github version does). So I'd like to update the gem on our systems so that we can put these tests back in (seeing as Puppet itself is quite happy with my module, it seems helpful to be able to test it).

Anyone got any opinions/thoughts? Any idea when we can expect a new gem?

**Comment by rnelson0** [comment]
@jeffmccune @rodjek Bump.

**Comment by domcleal** [comment]
It appears 2.0.0 is now live: https://rubygems.org/gems/rspec-puppet/versions/2.0.0

**Comment by raphink** [comment]
:tada:
