### ISSUE TITLE
expect does not behave properly?

### ISSUE THREAD

**Issue by feniix** [rodjek/rspec-puppet#217]
I am using rspec-puppet from master and when I do this: 

    expect { should compile }.to raise_error(Puppet::Error, /Parameter has to be set to either true or false/)

fails with this error:
    
    expected Puppet::Error with message matching /Parameter has to be set to either true 
    or false/, got #<RSpec::Expectations::ExpectationNotMetError: error during compilation

The "stable" rspec-puppet gem works as documented.

For now I am working around it by doing:

    expect { should compile }.to raise_error(/Parameter has to be set to either true or false/)

Is this a bug?

**Comment by DavidS** [comment]
Please use `it { is_expected.to compile.and_raise_error(...) }` : https://github.com/rodjek/rspec-puppet#checking-if-the-catalog-compiles
