### ISSUE TITLE
Test fail if checking content of static files

### ISSUE THREAD

**Issue by piotrgo** [rodjek/rspec-puppet#231]
Hi,

rspec-puppet fails if I try to do a 

```
should contain_file('/etc/init/mock.conf').
      with_content(/respawn/)
```
When I declare that file as
```
file { '/etc/init/mock.conf':
    ensure   => present,
    source   => 'puppet:///modules/mock/mock.conf',
}
```

with 
```expected that the catalogue would contain File[/etc/init/mock.conf] with content set to /respawn/ but it is set to nil```

This only happens with the file being declared from static file not a template. If that's by design, can additional message be presented in the log to save time for searching for reason? :-)

Cheers,
Piotr

**Comment by DavidS** [comment]
There is an extra helper gem at https://github.com/Jimdo/jimdo-rspec-puppet-helpers if you really need that. Otherwise I'd suggest what @Aethylred said.
