### ISSUE TITLE
Puppet::Error exceptions mangled

### ISSUE THREAD

**Issue by jhoblitt** [rodjek/rspec-puppet#232]
Sometime between 93773d3cda0a8be016882cf25fc26d6a358c9bf7 (start of this year) and the current master `Puppet::Error` exceptions are getting mangled into `RSpec::Expectations::ExpectationNotMetError`, which breaks an awful lot of tests.  I haven't had the time to bisect where the regression was introduced.

Example test failure message:

```
 Failure/Error: expect { should compile }.to raise_error Puppet::Error, /not supported on Solaris/
   expected Puppet::Error with message matching /not supported on Solaris/, got #<RSpec::Expectations::ExpectationNotMetError: error during compilation: Module awstats is not supported on Solaris 
```

**Comment by geoffdavis** [comment]
@Aethylred Thanks for that tip.

If the raise_error matcher should be used instead of expect, the documentation page definitely needs to be updated. In particular: http://rspec-puppet.com/matchers/#testing_for_errors

**Comment by riton** [comment]
:+1:  for the documentation Update, the documentation is still wrong and does not work with the current master code

**Comment by DavidS** [comment]
`expect { should compile }` is wrong on many levels. The correct `should compile.and_raise_error` is documented in the [README](https://github.com/rodjek/rspec-puppet#checking-if-the-catalog-compiles) . I have no idea how to fix the docs on rspec-puppet.com though. @rodjek ?

**Comment by igalic** [comment]
@DavidS https://github.com/rodjek/rspec-puppet/tree/gh-pages
