### ISSUE TITLE
No objects created by tests

### ISSUE THREAD

**Issue by cypherfox** [rodjek/rspec-puppet#233]
For the following class:

    class nagios::rsp_test {
       file{ '/tmp/dummy':
         content => 'a dummy, really',
       }
       nagios_command {'check_imap_ssl':
         command_line => '$USER1$/check_imap -H $ARG1$ -p $ARG2$ -S',
         require      => Package['nagios-plugins'];
       }
     }

and the following spec:

    require 'spec_helper'
    
    describe 'nagios::rsp_test', :type => :class do
      context 'set commands for default environment' do
        it { should contain_file('/tmp/dummy') }
        it { should have_file_count(1) }
        it { should contain_file('/tmp/dummy2') }
        it { should have_nagios_command_count(1) }
        it { should contain_nagios_command('check_imap_ssl') } 
        it { should contain_nagios_command('check_imap_ssl').that_requires('Package[nagios]') }
      end
    end

I would expect 1 failure for the false file name, but I get the following:

```
Failures:

  1) nagios::rsp_test set commands for default environment should contain exactly 1 Have_file_count resource
     Failure/Error: it { should have_file_count(1) }
       expected that the catalogue would contain exactly 1 Have_file_count resource but it contains 0
     # ./spec/classes/rsp_test_spec.rb:13:in `block (3 levels) in <top (required)>'

  2) nagios::rsp_test set commands for default environment should contain File[/tmp/dummy2]
     Failure/Error: it { should contain_file('/tmp/dummy2') }
       expected that the catalogue would contain File[/tmp/dummy2]
     # ./spec/classes/rsp_test_spec.rb:15:in `block (3 levels) in <top (required)>'

  3) nagios::rsp_test set commands for default environment should contain exactly 1 Have_nagios_command_count resource
     Failure/Error: it { should have_nagios_command_count(1) }
       expected that the catalogue would contain exactly 1 Have_nagios_command_count resource but it contains 0
     # ./spec/classes/rsp_test_spec.rb:17:in `block (3 levels) in <top (required)>'

  4) nagios::rsp_test set commands for default environment should contain Nagios_command[check_imap_ssl] that requires Package[nagios]
     Failure/Error: it { should contain_nagios_command('check_imap_ssl').that_requires('Package[nagios]') }
       expected that the catalogue would contain Nagios_command[check_imap_ssl] with that requires Package[nagios]
     # ./spec/classes/rsp_test_spec.rb:19:in `block (3 levels) in <top (required)>'
```

I pull rspec-puppet from github and use bundler and the Puppetlabs-Helper in a combo that works for the puppetlab modules. I have added the dummy2 test to verify that at least something is tested at all.

I am at a loss what to check. Any pointers?

**Comment by DavidS** [comment]
The `have_file_count` should be `have_file_resource_count`: https://github.com/rodjek/rspec-puppet#checking-the-number-of-resources

The `nagios_command` doesn't have a require on Package[nagios].
