### ISSUE TITLE
#subject method no longer exists

### ISSUE THREAD

**Issue by jhoblitt** [rodjek/rspec-puppet#235]
It appears that the `#subject` alias to `#catalogue` was removed in 34220fc7349267f7def34fdadc035fb43e17d97a .  This breaks fairly idiomatic usage of puppetlabs_spec_helper's `#verify_contents`.  I assume this was done so as not to conflict with a `rspec-core` usage of `#subject`?  In any event, this happened without a deprecation warning. I've opened a bug on https://tickets.puppetlabs.com/browse/MODULES-1514 as well.

The fix is to replace `subject` with `catalogue` in the invocation of `#verify_contents`.

**Comment by DavidS** [comment]
Is there a reason those tests do not use `is_expected.to contain_file(config_file).with_content(content)` (example from https://github.com/jhoblitt/puppet-smartd/commit/e80c3aa740e578587bf1aaba9b6e64c52806c7a8)? That is rspec-puppet only, gives you the same semantic (unless I'm missing something) and will give you a nice diff on mismatches.

**Comment by jhoblitt** [comment]
@DavidS As to using the implicit receiver instead of `is_expected.to`, the module/tests predate rspec 3.  `#with_content` is not exactly equivalent to `#verify_contents` in that the later allows you to specify only the lines you want to ensure are present. AFAIK, `#with_content` doesn't work with an array of match patterns but it would be trivial to write a helper method around it.  `#verify_contents` was fairly idiomatic several years ago but I don't see it much anymore.

I'm not sure if any action is needed at this point since there has been a major API bump since I opened this issue.
