### ISSUE TITLE
run.and_raise_error fails on regex mismatch

### ISSUE THREAD

**Issue by aptituz** [rodjek/rspec-puppet#240]
I tried writing a test, that checks weither a certain ParseError is raised by a parser function. Apparently this works fine as long as the regex is matching, but as soon as it does not, the test fails with:

wrong number of arguments (0 for 1)

This message is not really helpful and seems more like its a bug in rspec-puppet.

**Comment by DavidS** [comment]
Most of this was rewritten in 2.2.0. I've added a test case to verify that this is not happening anymore.
