### ISSUE TITLE
Push version 2.0.0 rubygems

### ISSUE THREAD

**Issue by danzilio** [rodjek/rspec-puppet#244]
Could someone please push 2.0.0 to rubygems.org? Thanks! :)

**Comment by gaudenz** [comment]
same here too, please do a release

**Comment by razorsedge** [comment]
@rodjek bump?

**Comment by ampedandwired** [comment]
+1 would be really great to get this out @rodjek

**Comment by deltaroe** [comment]
Who do I need to bribe to get this done :)

**Comment by danzilio** [comment]
This got pushed yesterday! Thank you!!!!
