### ISSUE TITLE
Fix 1.0.1

### ISSUE THREAD

**Issue by voidus** [rodjek/rspec-puppet#247]
http://github.com/voidus/rspec-puppet/tree/1.X contains a fix for rspec-2.99 and sets the rspec version to ~> 2.99.

Please use it as a starting point for further 1.X development and release 1.0.2 because of the rspec-2.99 fix.

Thanks for the good work!

**Comment by DavidS** [comment]
As I don't know anybody who's working on rspec 1.x, can we close this?
