### ISSUE TITLE
rspec-puppet requires rspec 2. unable to run with rspec 3

### ISSUE THREAD

**Issue by electrical** [rodjek/rspec-puppet#248]
I wanted to try out rspec 3 with one of my puppet modules but rspec-puppet requires rspec 2 which makes it unable to try out rspec 3.

https://github.com/rodjek/rspec-puppet/blob/master/rspec-puppet.gemspec#L13

**Comment by logicminds** [comment]
now getting errors because I have incompatible versions of rspec.  Why is rspec 2 required?

```shell
Bundler could not find compatible versions for gem "rspec":
  In Gemfile:
    rspec-puppet (>= 0) ruby depends on
      rspec (~> 2.0) ruby

    beaker-rspec (>= 0) ruby depends on
      serverspec (~> 2) ruby depends on
        rspec (3.0.0)

```

**Comment by jeffmccune** [comment]
Puppet still requires rspec 2, perhaps that's why?

**Comment by logicminds** [comment]
It works with my fork using rspec 3.  This should probably be changed to accept both 2 and 3.  I have been use 3 for at least a year with rspec-puppet but the old syntax is still being used which is still supported.

https://github.com/logicminds/rspec-puppet/blob/master/rspec-puppet.gemspec

**Comment by frizop** [comment]
Confirmed, just tried this fork out. Seems fine.

**Comment by electrical** [comment]
I've submitted a PR for it to get it fixed https://github.com/rodjek/rspec-puppet/pull/249

**Comment by Sharpie** [comment]
@jeffmccune Looks like Puppet 4 is switching to Rspec 3 (puppetlabs/puppet#3442), so `rspec-puppet` will likely have to support both.

**Comment by logicminds** [comment]
Transpec makes it easy to switch to rspec3.

**Comment by electrical** [comment]
I think we can close this now since my PR is merged.
