### ISSUE TITLE
Could the documentation be extended regarding run tests for all modules at once

### ISSUE THREAD

**Issue by 030** [rodjek/rspec-puppet#250]
At the moment it is possible to run tests for a module from a module by executing rspec. The aim is to run the tests of all modules at once using rake or something?

The idea is to execute a build like Jenkins does for Java code. The tests of all Java Classes is run at once and fails if there is something wrong.

Another part is the test coverage. This is shown per module as well. Would it be possible to show the code coverage of all the modules instead of one and let the build fail if the coverage is .e.g X < 90% for all modules and per module

**Comment by DavidS** [comment]
I believe this is currently out of scope. The current common module dev workflow uses separate repos for each module. Cross-module integration therefore needs to happen outside of these repos/projects.

As an easy workaround, you can run rake in each of the modules. There is ongoing work to make modules' rakefiles more uniform at https://github.com/rodjek/rspec-puppet/commit/e88264a0591573280733440969675a9fdc1b01c6
