### ISSUE TITLE
Parameter values that are a hash cannot be compared to arrays

### ISSUE THREAD

**Issue by bodepd** [rodjek/rspec-puppet#253]
Code was added in commit: f491957410cb1dadcc0cd69390d8ea79b0a1ab28

that does the following:

```
-        if expected.is_a?(Array) && expected.length == 1
-          actual = Array[actual] unless actual.is_a?(Array)
-        end
+        actual = [*actual] if expected.is_a?(Array)
```

In the case where a parameter is an array with a single hash as an element, it transform this hash into an array by calling '*' on it

To show a very precise example of that this code is doing in the case of an array with a single hash element:

```
2.0.0-p598 :012 > [*{"path"=>"/", "url"=>"http://127.0.0.1:18774/"}]
 => [["path", "/"], ["url", "http://127.0.0.1:18774/"]]
```

@jeffmccune this is your patch that is causing this data transformation, but reading through the commit message I did not quite understand what it did?

**Comment by Phil-Friderici** [comment]
see https://travis-ci.org/ghoneycutt/puppet-module-ntp/jobs/50639671 for an example with package resource used

**Comment by ghoneycutt** [comment]
Here's a hack to get Travis-ci happy if you are hitting this issue.

``` ruby
# Gemfile

gem 'rspec', '~>2.0' # needed to support ruby 1.8.7
gem 'rspec-puppet', '~>1.0' # addresses this issue
```

**Comment by jeffmccune** [comment]
@bodepd The patch, as a whole, was trying to add test coverage to describe how parameter matchers are expected to behave.

The change to use [*actual] was simply an attempt to clean up and simplify the logic, but I didn't anticipate the array of hashes issue, nor is there test coverage for it.

My suggestion is to add another test case that fails with the [*actual] usage, then let's see if we can get the matcher behavior changed to address all of the examples.

**Comment by bodepd** [comment]
@jeffmccune sure. I'm happy to see if I can put something together for this.

**Comment by kjetilho** [comment]
this just hit me, [ {"foo"=>"bar"} ] seemed to be mysteriously changed to [["foo", "bar"]] in the "catalogue".  I changed the code to

        actual = [actual] if expected.is_a?(Array) and not actual.is_a?(Array)

it worked for me, but I think the old code is better?

**Comment by DavidS** [comment]
github closed this by accident.
