### ISSUE TITLE
rspec-puppet 1.0 tests break with the v2.x gem

### ISSUE THREAD

**Issue by GeoffWilliams** [rodjek/rspec-puppet#257]
I don't think this is a bug as such but I encountered a problem recently when using `rspec-puppet` and would like to make the solution easier to find for those who encounter the same conditions.

## Background
I was demoing Puppet RSpec testing to an audience by creating a new puppet module `puppet module create ...` and since I had a bit of time left over, I started demonstrating some previously written RSpec tests by pasting them into the current module.  This promptly broke and I was unable to resolve the problem until some time later.

Thinking back, do remember getting a bunch of deprecation warnings when running the tests in the original module that looked liked this:

    Deprecation Warnings:

    Filtering by an `:example_group` subhash is deprecated. Use the subhash to filter directly instead. Called from /usr/local/share/gems/gems/rspec-puppet-1.0.1/lib/rspec-puppet/example.rb:12:in `block in <top (required)>'.
    Filtering by an `:example_group` subhash is deprecated. Use the subhash to filter directly instead. Called from /usr/local/share/gems/gems/rspec-puppet-1.0.1/lib/rspec-puppet/example.rb:16:in `block in <top (required)>'.
    Filtering by an `:example_group` subhash is deprecated. Use the subhash to filter directly instead. Called from /usr/local/share/gems/gems/rspec-puppet-1.0.1/lib/rspec-puppet/example.rb:20:in `block in <top (required)>'.
    Too many uses of deprecated 'Filtering by an `:example_group` subhash'. Pass `--deprecation-out` or set `config.deprecation_stream` to a file for full output.

    --------------------------------------------------------------------------------
    RSpec::Puppet::ManifestMatchers::CreateGeneric implements a legacy RSpec matcher
    protocol. For the current protocol you should expose the failure messages
    via the `failure_message` and `failure_message_when_negated` methods.
    (Used from /root/test-test/spec/classes/init_spec.rb:11:in `block (3 levels) in <top (required)>')
    --------------------------------------------------------------------------------

    If you need more of the backtrace for any of these deprecations to
    identify where to make the necessary changes, you can configure
    `config.raise_errors_for_deprecations!`, and it will turn the
    deprecation warnings into errors, giving you the full backtrace.

    5 deprecation warnings total

When I first encountered these messages I thought they were to do with the library itself but perhaps they're coming from my code?

## Code extract
The test code causing the problem was the statement:
```
    it {
      expect { subject }.to raise_error
    }
```
I can't remember where I originally borrowed this from but in any case, the `subject` variable/keyword seems to have gone from version 2.0.0 of `rspec-puppet`.

## Expected Behaviour
I expected `rspec-puppet` to inform me there was an error or deprecation with my test itself.  I ended up triple testing the Puppet manifest and re-reading my known-good code before I started investigating the gem versioning (the exception is definitely raised).  A more descriptive error message would be great if possible, eg something like:
```
expected Exception but nothing was raised (HINT: variable under test 'subject' == None)
```

## Actual Behaviour
On running the code above, I get an error which seems to indicate that the puppet manifest didn't raise an exception:

    Failures:

      1) ::test fails on non-redhat os family should raise Exception
         Failure/Error: expect {subject }.to raise_error
           expected Exception but nothing was raised
         # ./spec/classes/init_spec.rb:22:in `block (3 levels) in <top (required)>'

The puppet manifest definitely raises an exception though and I verified this via smoke testing.

## Workaround
Force the rspec-puppet gem to be an earlier version by adding or changing the line in Gemfile to read:
```gem 'rspec-puppet', '1.0.1'```
If using `bundler` otherwise change the system version of the gem to be version 1.0.1.

## Fix
Update the failing tests to be compatible with rspec-puppet v2.0.0, eg:
```
    it {
      expect { should compile }.to raise_error
    }
```

**Comment by DavidS** [comment]
Thank you for documenting this. For forcing an older version of a gem, I'd recommend using `~>` dependencies, as that will still allow bundler to install compatible updates. See "Pessimistic Version Constraint" here: http://guides.rubygems.org/patterns/
