### ISSUE TITLE
Order of arrayitems shouldn't matter

### ISSUE THREAD

**Issue by fonk** [rodjek/rspec-puppet#259]
With this piece of code:
```
    it do
      should contain_augeas('sshd_config').with({
        :context => '/files/foobar',
        :changes => [
          'set PermitRootLogin "YES"',
          'set foo "bar"',
        ]
      })
```

I get:
```
expected that the catalogue would contain Augeas[sshd_config] with changes set to ["set PermitRootLogin \"no\"", "set foo \"bar\""] but it is set to ["set foo \"bar\"", "set PermitRootLogin \"no\""]
```

As it's an array, the order shouldn't matter. Please also note that different puppet versions seem to order the items in the catalog different, what makes the problem even worse for testing with different versions.

**Comment by DavidS** [comment]
I disagree. Order in arrays often matters. You might want to check out the augeas helper linked at the end of the [README](https://github.com/rodjek/rspec-puppet#related-projects).
