### ISSUE TITLE
Transfer rspec-puppet to the Puppet Community org

### ISSUE THREAD

**Issue by dfarrell07** [rodjek/rspec-puppet#260]
Per [discussions](http://irc-logs.puppetlabs.com/puppetdev/%23puppet-dev-2015-03-03.log.html#t2015-03-03T11:35:35) on the #puppet-dev IRC channel and [this rspec-puppet PR](https://github.com/rodjek/rspec-puppet/pull/249#issuecomment-77198840) (please, someone merge it), there seems to be non-trivial support for transferring rspec-puppet to the [Puppet Community](http://puppet-community.github.io/) project and [their GitHub organization](https://github.com/puppet-community).

The primary driver for this change is the [lack of maintenance](https://github.com/rodjek/rspec-puppet/pull/249#issuecomment-75811101) of rspec-puppet. There have been no PRs merged since December 2nd 2014, over 3 months ago. Per the [Puppet Community docs](http://puppet-community.github.io/), this seems like a perfect match for their mission:

> Over the years a lot of tooling on top of Puppet has been developed. Some of those, though in active use, have fallen into a state of decay because the maintainer is AWOL or simply doesn't have the time or need to maintain this tool.

To be super clear: We understand that devs get busy and that maintaining a large project is a huge task. We deeply appreciate the contributions of @rodjek and the other rspec-puppet maintainers. Thank you!

This issue is meant to consolidate the discussions related to the potential transfer and get the conversation off of [a mostly-unrelated PR](https://github.com/rodjek/rspec-puppet/pull/249).

**Comment by nemski** [comment]
I'm in support of this if it means the project gets the time and love it needs! There seems to be a large number of users of this project and it would certainly be helpful to have more maintainers than just poor @rodjek

**Comment by domcleal** [comment]
Yeah, I agree.  I'm concerned about Puppet 4 support, as I had a quick test at the last contributor summit and it was failing to initialise Puppet and build catalogs, which is going to be a big pain for maintainers and the adoption of Puppet 4.  It needs to be actively maintained.

**Comment by ffrank** [comment]
+1

**Comment by raphink** [comment]
Puppet-lint is also affected.

**Comment by peiriannydd** [comment]
+1

**Comment by nibalizer** [comment]
+1

**Comment by jeffmccune** [comment]
Just as an FYI, Rodjek has been kind enough to give me push access to rubygems.org.  In an effort to help alleviate some of the pressure that seems to have built up around the conflicting dependency situation, I went ahead and merged the PR to relax the dependency on rspec-core and then pushed rspec-puppet 2.0.1 to rubygems.org.

**Comment by jeffmccune** [comment]
With that said, I think we definitely need to continue the discussion about how best to maintain rspec-puppet into the future.

**Comment by dfarrell07** [comment]
> I went ahead and merged the PR to relax the dependency on rspec-core and then pushed rspec-puppet 2.0.1 to rubygems.org.

As we said on that PR, ***thank you so much*** for taking the time to review it. :)

> With that said, I think we definitely need to continue the discussion about how best to maintain rspec-puppet into the future.

How does the proposal to transfer it to Puppet Community sound to you? Any other suggestions? You didn't happen to get any feedback from @rodjek about maintenance options, did you?

**Comment by logicminds** [comment]
+1

**Comment by peiriannydd** [comment]
:+1: 

Community transfer seems ideal.

Although, is there another recommended testing framework that we should be using/looking at? It seem that this will need to keep up with the language and parser pretty aggressively.

**Comment by dbeckham** [comment]
There isn't actually any other framework. It seems that @rodjek is becoming a victim of his own success. He's created two fantastic tools (rspec-rspec and puppet-lint), but doesn't seem to really have the time to maintain them against the constant movement of Puppet and Ruby testing tools. I really do hope that he can either transfer them to the puppet-community group or find a trustworthy group of individuals that can help him maintain it and keep it moving forward under his vision.

**Comment by DavidS** [comment]
After doing some of the release-prep work for the last versions, rodjek granted me push rights here and on rubygems. I'm subscribed to this repo now and am slowly workingthrough the backlog. If you have any PRs I should specifically look at, please ping me there!

**Comment by nibalizer** [comment]
Sounds like we can close this then.

**Comment by ffrank** [comment]
Ack!

**Comment by dfarrell07** [comment]
> After doing some of the release-prep work for the last versions, rodjek granted me push rights here and on rubygems.

Great! Thanks for putting in the work, and thanks @rodjek for helping this move to a conclusion.

> Sounds like we can close this then.

+1

**Comment by DavidS** [comment]
Thanks for y'alls trust :blush:
