### ISSUE TITLE
Future Parser and exec resources

### ISSUE THREAD

**Issue by electrical** [rodjek/rspec-puppet#262]
I'm getting the following error when using the future parser ( puppet 3.7.4 )

```
     Failure/Error: it { should contain_file('/etc/elasticsearch/templates_import').with(:require => 'Exec[mkdir_templates_elasticsearch]') }
       expected that the catalogue would contain File[/etc/elasticsearch/templates_import] with require set to "Exec[mkdir_templates_elasticsearch]" but it is set to [Exec[mkdir_templates_elasticse
arch]{:command=>"mkdir_templates_elasticsearch"}]
```
I'm unsure where the extra `{:command=>"mkdir_templates_elasticsearch"}` comes from.

**Comment by DavidS** [comment]
`spec/defines/sysctl_spec.rb` tests something very similar to this. Can you add your manifest and spec code too, that triggers that?

**Comment by electrical** [comment]
Hi David,

if you checkout https://github.com/elastic/puppet-elasticsearch it should show up.

I've tried it with recent puppet 3.x and future parser enabled and also with puppet 4 and got the same error.

**Comment by DavidS** [comment]
I've tried my hand at a fix but that didn't work very well. You should look into changing those tests to use the relationship matchers as described here: https://github.com/rodjek/rspec-puppet#relationship-matchers Any reason, you're not using them?

**Comment by electrical** [comment]
Hi David,

I did test with those and made no difference if i remember correctly. @hunner gave me that advice a while ago but no change.

**Comment by electrical** [comment]
Been doing some more tests and for some weird reason it now works with the new relationship matchers.
Confused why the old way doesn't work anymore though.

**Comment by DavidS** [comment]
Thanks for re-checking. 

If I had a nickel for every time ...
