### ISSUE TITLE
Colon-separated Puppet[:libdir] breaks fixtures' `require`

### ISSUE THREAD

**Issue by hunner** [rodjek/rspec-puppet#264]
This line: https://github.com/rodjek/rspec-puppet/blob/v2.0.1/lib/rspec-puppet/support.rb#L145

Conflicts with this line: https://github.com/puppetlabs/puppet/blob/4.0.0-rc2/lib/puppet/defaults.rb#L255

Because `$LOAD_PATH` is supposed to be an array of lib directories, but if `Puppet[:libdir]` is a colon-separated list of directories, then this falls over and breaks `require` from fixtures. This eventually trickles down to https://github.com/puppetlabs/puppet/blob/4.0.0-rc2/lib/puppet/util/autoload.rb#L161 and broken load paths.

The solution would need rspec-puppet not use `Puppet[:libdir]`. I'm not sure of a hook that works yet, but perhaps something like `$LOAD_PATH` directly? Or letting the autoloader do its thing with `Puppet[:modulepath]` on its own.

**Comment by drudnev** [comment]
From what I can tell this boils down to modulepath and libdir aren't beeing autoloaded by puppet; 
https://github.com/puppetlabs/puppet/blob/4.0.0-rc2/lib/puppet/util/autoload.rb#L127
https://github.com/puppetlabs/puppet/blob/4.0.0-rc2/lib/puppet/util/autoload.rb#L149
I've worked around it by calling Puppet.settings.initialize_app_defaults(defaults) function. 

Here is the modified function that appears to work for me. can anyone else verify that this is proper fix.
https://gist.github.com/drudnev/941f5f1c722370d563d1

**Comment by joshcooper** [comment]
When puppet starts up, its bootstrapping process can result in the autoloader being called before the modulepath is known. So this is why the [autoloader roughly does](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/util/autoload.rb#L127-L143):

```
if Puppet.settings.app_defaults_initialized?
  # if the app defaults have been initialized then it should be safe to access the module path setting.
  $env_module_directories[env] ||= env.modulepath.collect do |dir|
   ..
  end
else
  # if we get here, the app defaults have not been initialized, so we basically use an empty module path.
  []
end
```

Calling `Puppet.settings.initialize_app_defaults` tells puppet that its settings have been parsed, its `run_mode` is known, and the bootstrapping process is done. And it allows the autoloader to load from the current environment's modulepath.

That said, there are two problem with that approach. First, it will only work if you load a custom type, provider, etc from a module, but not if that code attempts to `require` helper code from the same or different module.

Second, puppet's [`Puppet::Test::TestHelper`](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/test/test_helper.rb) is intended to be the entry point when testing puppet as a library. For example, the `TestHelper` calls [`initialize_app_defaults`](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/test/test_helper.rb#L211), as well as a bunch of other test initialization, e.g. pushing an environment onto the context stack.

Puppet's own [spec_helper](https://github.com/puppetlabs/puppet/blob/master/spec/spec_helper.rb) calls into `Puppet::Test::TestHelper` to handle initialization. See https://github.com/puppetlabs/puppet/blob/master/spec/spec_helper.rb#L79, https://github.com/puppetlabs/puppet/blob/master/spec/spec_helper.rb#L99, https://github.com/puppetlabs/puppet/blob/master/spec/spec_helper.rb#L144, etc.

I'm thinking rspec-puppet should be doing the same?

For this specific issue (colon separated `Puppet[:libdir]`), I have submitted https://github.com/rodjek/rspec-puppet/pull/237. It adds the current environment's module lib directories to the $LOAD_PATH, which works for custom types, etc, and helper code that they may require.
