### ISSUE TITLE
FunctionExampleGroup#catalogue inconsistency

### ISSUE THREAD

**Issue by DavidS** [rodjek/rspec-puppet#268]
FunctionExampleGroup#catalogue somehow differs from how other example groups implement this property. I've written up my current state of research at https://github.com/DavidS/rspec-puppet/commit/5a85f279b13028ed7d24715b1f92e4438eba23b7

**Comment by rodjek** [comment]
I believe #475 resolves the problems noted in your linked commit, so I'm going to close this for now, but please re-open if I've missed part of it.
