### ISSUE TITLE
Rspec LocalJumpError and LoadError

### ISSUE THREAD

**Issue by hussainaphroj** [rodjek/rspec-puppet#270]
Hi All,

I am currently using 3.6.2 version of puppet  with 1.8.7 version of Ruby and tried setting up rspec(http://rspec-puppet.com/ ). Getting following erros while running test case:

# rake spec
/usr/bin/ruby -I/usr/lib/ruby/gems/1.8/gems/rspec-support-3.2.2/lib:/usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*/\*_spec.rb
/etc/puppet/environments/dev/modules/rspec-test/spec/spec_helper.rb:1:in `require': no such file to load -- rspec-puppet (LoadError)
        from /etc/puppet/environments/dev/modules/rspec-test/spec/spec_helper.rb:1
        from /etc/puppet/environments/dev/modules/rspec-test/spec/classes/init_spec.rb:1:in `require'
        from /etc/puppet/environments/dev/modules/rspec-test/spec/classes/init_spec.rb:1
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load_spec_files'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/exe/rspec:4

#bundle exec rake spec
/usr/bin/ruby -I/usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib:/usr/lib/ruby/gems/1.8/gems/rspec-support-3.2.2/lib /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*/\*_spec.rb
/usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:512:in `all_hooks_for': return from proc-closure (LocalJumpError)
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:564:in `process'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/flat_map.rb:11:in `map'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/flat_map.rb:11:in `flat_map'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:563:in `process'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/hooks.rb:429:in `register_globals'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:394:in `set_it_up'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:361:in `subclass'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/example_group.rb:253:in `describe'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/dsl.rb:43:in `__send__'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/dsl.rb:43:in `describe'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/dsl.rb:82:in `__send__'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/dsl.rb:82:in `describe'
        from /etc/puppet/environments/dev/modules/rspec-test/spec/classes/init_spec.rb:2
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load_spec_files'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
        from /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/exe/rspec:4
/usr/bin/ruby -I/usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/lib:/usr/lib/ruby/gems/1.8/gems/rspec-support-3.2.2/lib /usr/lib/ruby/gems/1.8/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\*/\*_spec.rb failed

I have installed the following gems:

# gem list

*** LOCAL GEMS ***

bundler (1.9.4)
CFPropertyList (2.2.8)
colored (1.2)
cri (2.6.1)
diff-lcs (1.2.5)
facter (2.4.3)
faraday (0.9.1)
faraday_middleware (0.9.1)
faraday_middleware-multi_json (0.0.6)
hiera (2.0.0)
json (1.8.2, 1.5.5)
json_pure (1.8.2)
log4r (1.1.10)
metaclass (0.0.4)
metadata-json-lint (0.0.6)
mocha (1.1.0)
multi_json (1.11.0)
multipart-post (2.0.0)
passenger (5.0.6)
puppet-lint (1.1.0)
puppet-syntax (2.0.0)
puppetlabs_spec_helper (0.10.2)
r10k (1.5.1)
rack (1.6.0)
rake (10.4.2)
rspec (3.2.0, 2.99.0)
rspec-core (3.2.3, 2.99.2)
rspec-expectations (3.2.1, 2.99.2)
rspec-mocks (3.2.1, 2.99.3)
rspec-puppet (2.0.1)
rspec-support (3.2.2)
semantic_puppet (0.1.1)
spdx-licenses (1.0.0)

Any Help will be appreciated.

Thanks,
Afroz Hussain

**Comment by alexjfisher** [comment]
Your version of rspec is too recent for ruby 1.8?

In your Gemfile, pin rspec-core.  eg
```
gem 'rspec-core', '3.1.7', :require => false
```

A large number of puppetlabs modules are doing this (I guess to keep them ruby 1.8 compatible)

**Comment by DavidS** [comment]
I've added a note to the README covering this.

**Comment by alexjfisher** [comment]
@DavidS You have?  I can't see a commit for this.  Thanks.

**Comment by DavidS** [comment]
Oh sorry! I only added it to my local work branch here: https://github.com/DavidS/rspec-puppet/commit/6bb7a41b793083bd5136b06d29194477b6b08fc2 

That'll be merged RSN.
