### ISSUE TITLE
integer :params get converted to string

### ISSUE THREAD

**Issue by michakrause** [rodjek/rspec-puppet#286]
spec.rb:
let(:params) { { :foo => 42 } }

foobar.pp:
define foobar ($foo) {
  foobar=$foo+1
}

This failes with: "left operand of + is not a number"

**Comment by DavidS** [comment]
I can't reproduce this with the current master (see above commit). Quite to the contrary, when I use the foobar variable as title, puppet 4 will complain about it being an integer.

Which puppet and rspec-puppet versions are you using?

**Comment by michakrause** [comment]
rspec-puppet: 1.0.1-2
puppet: 3.7.2-4

**Comment by DavidS** [comment]
Would you be able to upgrade to 2.x? If not, I would be interested to hear reasons for still using 1.x.

**Comment by michakrause** [comment]
:-( ok, I was not able to reproduce the problem now, even with the older version. I guess this issue can be closed for now, I will reopen it in the event I get this problem again.

**Comment by DavidS** [comment]
Thanks for checking it out!
