### ISSUE TITLE
should_not contain_exec throws error

### ISSUE THREAD

**Issue by Aethylred** [rodjek/rspec-puppet#289]
I have a manifest that runs an `exec` resource depending on `osfamily`

I have the following statement in my rspec-puppet test script.

```ruby
case facts[:osfamily]
when 'RedHat'
  it{ should contain_exec('dev_tools').with(
    'user'    => 'root',
    'path'    => ['/usr/bin'],
    'command' => "yum -y groupinstall 'Development Tools'",
    'unless'  => "yum -y groupinstall 'Development Tools' --downloadonly",
    'timeout' => '0600',
    'require' => 'Package[yum-plugin-downloadonly]'
  ) }
else
  it{ should_not contain_exec('dev_tools') }
end
```

...but it throws the following error:

```ruby
Failure/Error: it{ should_not contain_exec('dev_tools') }
     NoMethodError:
       undefined method `negative_failure_message' for #<RSpec::Puppet::ManifestMatchers::CreateGeneric:0x7f0270851a00>
     # ./spec/classes/core_install_spec.rb:23
```

**Comment by Aethylred** [comment]
Right found it. It was reintroduced later in the horrible mess. Nested ifs and cases.

**Comment by rwaffen** [comment]
i have the same problem. i have a simple if-statement in my puppet code and want to test "true or false" and if the resource inside the if-block is in the catalogue or not.

**Comment by DavidS** [comment]
@Aethylred I can't see your problem with the current released version. Closing.

@rwaffen please open a separate issue with both your manifest and test code.
