### ISSUE TITLE
Using symlinks doesn't work on Windows and breaks puppet doc and geppetto

### ISSUE THREAD

**Issue by rharrison10** [rodjek/rspec-puppet#29]
Windows doesn't support symlinks so any user trying to use rspec-puppet on Windows is simply out of luck.  Also since Java doesn't support symlinks either (mainly due to Windows lack of support for them) once you allow  `rspec-puppet-init` to create the symlinks from the fixtures directory to the top of the modules directory any user trying to work with [Geppetto](http://cloudsmith.github.com/geppetto/) as their editor will be broken as well.  Especially if they keep their modules under source control which everyone should be doing.  Its no longer possible to use Geppeto for any git operations on my modules and its sees the symlinked directories as containing a separate copy of all of my manifests.

Also after using `rspec-puppet-init` to generate the layout in my module I'm no longer able to use `puppet doc` to generate rdoc documentation on any of my modules because it sees the classes defined multiple times.

``` sh
$ puppet doc --outputdir /tmp/puppet/rdoc --mode rdoc --manifestdir ~/git/puppet/manifests --modulepath ~/git/puppet/modules
```

``` ruby
/usr/lib/ruby/1.8/rdoc/dot/dot.rb:28: warning: already initialized constant NODE_OPTS
/usr/lib/ruby/1.8/rdoc/dot/dot.rb:46: warning: already initialized constant EDGE_OPTS
/usr/lib/ruby/1.8/rdoc/dot/dot.rb:76: warning: already initialized constant GRAPH_OPTS
Could not generate documentation: Definition 'haproxy::proxy_farm' is already defined at /home/example/git/puppet/modules/haproxy/manifests/proxy_farm.pp:32; cannot be redefined at /home/example/git/puppet/modules/haproxy/spec/fixtures/modules/haproxy/manifests/proxy_farm.pp:32
```

I need to know what the best way to work around this bug is and another solution to the modulepath issue clearly needs to be found.  Why isn't it acceptable to include the parrent directory of the module in the module path?

**Comment by Breeze773** [comment]
Any work on this issue?  With cucumber puppet being dead and PuppetLabs giving more love to Windows lately, I think this should be bumped.
Are there any windows-friendly testing alternatives?

**Comment by iljaweis** [comment]
If you can't use symlinks, you could try copying everything into spec/fixtures/modules/#{modulename} in the 'setup' task instead of creating a symlink.

**Comment by cyberious** [comment]
@Breeze773 @iljaweis We got around this in the puppetlabs_spec_helper by using the underlying puppet api to create the symlinks, it does however require puppet > 3.5.0
https://github.com/puppetlabs/puppetlabs_spec_helper/pull/87
