### ISSUE TITLE
catalogue property does not interact well with expect()

### ISSUE THREAD

**Issue by DavidS** [rodjek/rspec-puppet#297]
See https://github.com/puppetlabs/puppetlabs-stdlib/pull/464#discussion-diff-31345775R24 for context.

**Comment by igalic** [comment]
github diff discussions might be a bit too ephemeral for linking from an issue ;)

**Comment by DavidS** [comment]
Should github vanish, it will take both ends of the link with it. In any other case, the content should stay available long enough that I can come up with a fix.

**Comment by igalic** [comment]
hahah okay :D

**Comment by DavidS** [comment]
the compile matcher (and others) use `catalogue.call` (https://github.com/rodjek/rspec-puppet/blob/f69b47ec113d6d27df44f41ef74cdde435af3530/lib/rspec-puppet/matchers/count_generic.rb#L15) to actually create the catalog on matching. in `FunctionExampleGroup` the `catalogue` property returns an already compiled catalog.
