### ISSUE TITLE
Enable rspec-mocks integration everywhere

### ISSUE THREAD

**Issue by DavidS** [rodjek/rspec-puppet#298]
Seems like the custom `ExampleGroups` elide the rspec-mocks integration. This leads to workarounds like https://github.com/puppetlabs/puppetlabs-stdlib/pull/464/files#diff-93830fa29d616f7c87903d08b5b1b29aR18 and https://github.com/puppetlabs/puppetlabs-stdlib/pull/464/files#diff-93830fa29d616f7c87903d08b5b1b29aR38 

Note that the workaround there is incomplete, as it does not handle nested example groups and throws away all stubs/expectations after every test.

**Comment by rodjek** [comment]
Closing as no work arounds are necessary these days to use rspec-mocks
