### ISSUE TITLE
Resource references in relationship matchers should support more puppet features

### ISSUE THREAD

**Issue by j-vizcaino** [rodjek/rspec-puppet#315]
It seems that `that_requires`,  `that_comes_before` and such get confused when the name of the resource is surrounded by quotes (or double-quotes).

Example:
```ruby
shoud contain_package('foo').that_comes_before('Package["bar"]')   # does not work
shoud contain_package('foo').that_comes_before('Package[bar]')   # works !
```

This is surprising (and misleading) because, both notations are the same in the Puppet language.

**Comment by DavidS** [comment]
The resource references on the ruby side of things always are unquoted, since they are not "really" puppet code. I'd hesitate to change this behaviour for a single consumer of puppet's ruby API. Do you think a note in the README would have helped you avoid this pitfall?

**Comment by j-vizcaino** [comment]
I understand there is a limitation as to how the resource are represented inside Ruby but, as a Puppet developer I have no such knowledge.
A note in the README would be a must (I just wasted about an hour on this problem).

The main problem I see here is that the content inside the quotes feels like Puppet code but it seems like it isn't. This is really confusing...

**Comment by dsn** [comment]
I am having a problem checking a require on a package with a hyphen in the name that I think is related.

```
should contain_file('/etc/ssh/sshd_config').that_requires('Package[openssh-server]')

Failure/Error: should contain_file('sshd_config').that_requires("Package[openssh-server]")
NoMethodError:
  undefined method `[]' for nil:NilClass
```
In testing I noticed if I try to escape the hyphen or add an extra hyphen I get a different error

```
should contain_file('/etc/ssh/sshd_config').that_requires('Package[openssh--server]')

Failure/Error: should contain_file('sshd_config').that_requires('Package[openssh--server]')
  expected that the catalogue would contain File[sshd_config] with that requires Package[openssh--server]
```

**Comment by DavidS** [comment]
What do you think about the note added here: https://github.com/DavidS/rspec-puppet/blob/42c83bff6175327e0f69236300b3860c530f8476/README.md#relationship-matchers 

(https://github.com/DavidS/rspec-puppet/commit/42c83bff6175327e0f69236300b3860c530f8476#diff-04c6e90faac2675aa89e2176d2eec7d8R243)

**Comment by j-vizcaino** [comment]
I think that's good, thanks!
Please use a more "eye-catchy" style, because this is really a caveat and people have a tendency to "run through the doc". I would suggest writing **unquoted title** using bold font for example.
Also, IIRC, `Class[foo]` works whereas `Class[::foo]` doesn't. This should be mentioned as well.

**Comment by DavidS** [comment]
Good point. This is now #326

**Comment by j-vizcaino** [comment]
Thanks, with #326, explanation is pretty clear and examples help avoid the pitfalls.

**Comment by DavidS** [comment]
Thank you for validation!
