### ISSUE TITLE
Coverage of functions not working as expected

### ISSUE THREAD

**Issue by bodgit** [rodjek/rspec-puppet#316]
I'm not 100% sure if this is rspec-puppet's fault or not but basically I was trying to add coverage reports to my modules with "coveralls" for any custom functions and/or types/providers. However for a given function say, my coverage report only seems to cover the flow from the last expectation, whereas I would expect it would cover the sum of all expectations.

I've distilled this into a sample test module available at `bodgit/puppet-test`. If I simply reorder the expectations within `spec/functions/test_spec.rb` I can change the coverage percentage anywhere from ~30% upwards whereas I'd expect it to be the same (near 100% I think) no matter the order.

Is this something specific to rspec-puppet? I'm at a bit of a loss as to where to initially go for help on this however as it seems very Puppet-specific I thought I'd try here first.

**Comment by DavidS** [comment]
Weird. I had basically the same code working here: https://github.com/DavidS/puppetlabs-stdlib/commit/23abe4caeea5e62f40d891cb1c5f9655d2ad358b#diff-93830fa29d616f7c87903d08b5b1b29a

**Comment by bodgit** [comment]
I've created a simple non-Puppet Ruby project and SimpleCov/Coveralls works correctly there so I'm thinking there's something somewhere in one of the Puppet-based gems that is screwing up the coverage tracking, but I don't even know where to begin looking to debug it.

**Comment by bodgit** [comment]
I was intrigued by your stdlib commit, so I cloned the stdlib module and just added the coveralls gem as simplecov is already there and made the necessary changes to the top of `spec/spec_helper.rb`. I can see the same problem here if I take the `any2array()` function, by making the following change:

```diff
diff --git a/spec/functions/any2array_spec.rb b/spec/functions/any2array_spec.rb
index 70121f1..bcdab27 100755
--- a/spec/functions/any2array_spec.rb
+++ b/spec/functions/any2array_spec.rb
@@ -6,10 +6,10 @@ describe "any2array" do
   it { is_expected.to run.with_params(true).and_return([true]) }
   it { is_expected.to run.with_params('one').and_return(['one']) }
   it { is_expected.to run.with_params('one', 'two').and_return(['one', 'two']) }
-  it { is_expected.to run.with_params([]).and_return([]) }
   it { is_expected.to run.with_params(['one']).and_return(['one']) }
   it { is_expected.to run.with_params(['one', 'two']).and_return(['one', 'two']) }
   it { is_expected.to run.with_params({}).and_return([]) }
   it { is_expected.to run.with_params({ 'key' => 'value' }).and_return(['key', 'value']) }
   it { is_expected.to run.with_params({ 'key' => 'value' }).and_return(['key', 'value']) }
+  it { is_expected.to run.with_params([]).and_return([]) }
 end
```

I can get the coverage to drop from 75% to 50%.

**Comment by DavidS** [comment]
Thanks for verifying that.

**Comment by bodgit** [comment]
I've now noticed that for the test module I created to illustrate this bug I now get zero code coverage if I use Puppet 4.x.

The only way to get any coverage now is to remove the `add_filter spec/` line from `spec_helper.rb` which causes all the code to be shown as living under `spec/fixtures/modules/<module under test>/lib/...` instead of `lib/...` as it used to.

If I pin Puppet to `~> 3.0` then the original behaviour (including this bug) is restored.

**Comment by bodgit** [comment]
I've noticed some annecdotal behaviour when I was testing a custom function that did a bit of patching to work around running on Ruby 1.8.7. The function in question is here: https://github.com/bodgit/puppet-bodgitlib/blob/master/lib/puppet/parser/functions/validate_ldap_uri.rb . Originally on [line 11](https://github.com/bodgit/puppet-bodgitlib/blob/master/lib/puppet/parser/functions/validate_ldap_uri.rb#L11) I was performing a simple `=` assignment however I noticed for multiple tests of that function I would see a Ruby warning for redefining that constant so I changed it to `||=` to silence the warning. So it looks like my function gets re-imported each time it's tested rather than just get loaded once the first time it's invoked.

Would Puppet (or rspec-puppet) be re-importing the function on each expectation and by doing that it resets the coverage tracking for that function somehow? That might explain the behaviour I'm seeing.

I'm not going to be able to poke about with this for at least a couple of weeks but I thought I'd mention it in case it gives some inspiration.

**Comment by mccartjm** [comment]
I'm using puppet 4.1.8 currently and i am getting this:
Coverage report generated for RSpec, Rspec to Users/../../../coverage. 0.0 / 0.0 LOC (100.0%) covered.

COVERAGE: 100.00% -- 0.0/0.0 lines in 0 files

The top of my spec_helper file looks like: 
`require 'simplecov'
require 'simplecov-console'

SimpleCov.start do
  add_filter '/spec'
  add_filter '/vendor'
  formatter SimpleCov::Formatter::MultiFormatter[
    SimpleCov::Formatter::HTMLFormatter,
    SimpleCov::Formatter::Console
  ]
end`

So I am assuming that this is the same issue, though I have not tried puppet 3.

**Comment by DavidS** [comment]
This might be connected to the facts that simplecov forgets coverage for a file when it is reloaded, and the puppet core has shenanigans around function loading going on. I currently don't have cycles to delve deeper into it, but maybe someone playing around with strace can confirm that a) function ruby files are reloaded during testing, and b) coverage works for a single example (indicating that the without reloads, everything else works)?

**Comment by alexjfisher** [comment]
@DavidS Is there a workaround for this?  For the last few hours, I've been trying to figure out why I can't get any code coverage working in puppet/extlib...

**Comment by alexjfisher** [comment]
I tried this workaround. https://github.com/colszowka/simplecov/issues/389#issuecomment-104863943

Didn't have much luck though.  I did see if use `command_name = rspec` then `rspec1`, `rspec11` etc. but they all had 0% coverage so there was nothing to merge.
