### ISSUE TITLE
future parser documentation

### ISSUE THREAD

**Issue by logicminds** [rodjek/rspec-puppet#319]
I don't know the state of future parser support for rspec but it doesn't seem to be documented.  Can someone update the documentation on how to configure future parser support?

**Comment by DavidS** [comment]
There is currently no pre-fab way to do so within rspec-puppet. It just uses puppet as provided by the environment (usually bundler and the spec_helper).

There is https://github.com/puppetlabs/puppetlabs_spec_helper to help with setting that up.

**Comment by DavidS** [comment]
I've added https://github.com/rodjek/rspec-puppet/commit/8ca07a3a7473897b7e26ffbfae4134ea2bb2c133 to that effect.
