### ISSUE TITLE
Stages not recognized with puppet 4.2.2 and rspec-puppet 2.2.0

### ISSUE THREAD

**Issue by seanmckinley** [rodjek/rspec-puppet#320]
We recently upgraded to Puppet 4, and have since upgraded the gems we use for writing specs.

Unfortunately specs that were previously passing are now failing:
```
Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Function Call, Could not find stage first specified by Class[Ipa::Client]
```

The class in question:
```
$cat client.pp

class ipa::client(
  $principal = 'host_manager',
  $stage     = 'first',
  ){
```

And our site.pp
```
$cat ./spec/fixtures/manifests/site.pp
stage { 'first': before => Stage['main'] }
stage { 'last': require => Stage['main'] }
```

I thought perhaps the issue is related to the conditional statement here, but I'm not entirely sure: https://github.com/rodjek/rspec-puppet/blob/d2bbad3f3ff4c8327a6f60917b93c02de49429fc/lib/rspec-puppet/coverage.rb#L43-L4. 

Upon trying just a pry session during the rspec tests and seeing what Puppet[:environmentpath] is set to, I'm met with the following:
```
[7] pry(#<Class>)> Puppet[:environmentpath]
Puppet::Settings::InterpolationError: Error converting value for param 'environmentpath': Could not find value for $codedir
from /Users/sean.mckinley/.rvm/gems/ruby-2.1.5@puppet/gems/puppet-4.2.2/lib/puppet/settings.rb:1317:in `block in convert'
```

Of course the specs pass quite easily if we simply remove the stage parameter from the manifest, but that's not entirely ideal.

**Comment by seanmckinley** [comment]
Bit of an update that will hopefully prove useful:

Puppet 4 apparently uses the :codedir setting when creating the value for the :environmentpath setting. Since that apparently isn't being set anywhere when running rspec, environmentpath ends up returning the above interpolation error.

**Comment by DavidS** [comment]
If you're not using puppetlabs_spec_helper to setup your puppet test environment, you need to set the environmentpath manually, as in https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/module_spec_helper.rb#L23
