### ISSUE TITLE
site.pp file not being sourced by puppet during catalog compilation

### ISSUE THREAD

**Issue by dudemcbacon** [rodjek/rspec-puppet#322]
Hello,

I'm seeing the following error messages:

```
profile::ipa::client
  with default for all parameters
    should contain Notify[this is from site.pp] (FAILED - 1)

Failures:

  1) profile::ipa::client with default for all parameters should contain Notify[this is from site.pp]
     Failure/Error: it { should contain_notify('this is from site.pp') }
       expected that the catalogue would contain Notify[this is from site.pp]
```

I have the following in my site.pp file (at spec/fixtures/manifests/site.pp):

```
notify { 'this is from site.pp': }
```

I am using the puppetlabs_spec_helper to help configure RSpec. This setup worked fine before our company transitioned to Puppet 4 but now it seems like anything put into the site.pp file is ignored.

This is the content of my spec_helper.rb (at spec/spec_helper.rb) file:
```
require 'puppetlabs_spec_helper/module_spec_helper'
```

This is the content of the specfile (at spec/classes/profile__ipa__client_spec.rb):
```
require 'spec_helper'

describe 'profile::ipa::client' do
  context 'with default for all parameters' do
    it { should contain_notify('this is from site.pp') }
  end
end
```

**Comment by dudemcbacon** [comment]
I created a test puppet module to better isolate this failure from the other code in the module here: https://github.com/dudemcbacon/testmodule

bundle install --path local/vendor
bundle exec rake spec

Running the above commands from that repository yields:

```
brandon ➜  testmodule git:(master) bundle exec rake spec
/home/brandon.burnett/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/brandon.burnett/development/testmodule/local/vendor/ruby/2.1.0/gems/rspec-core-3.2.3/lib:/home/brandon.burnett/development/testmodule/local/vendor/ruby/2.1.0/gems/rspec-support-3.2.2/lib /home/brandon.burnett/development/testmodule/local/vendor/ruby/2.1.0/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color
.F

Failures:

  1) testmodule with default for all parameters should contain Notify[this is from site.pp]
     Failure/Error: it { should contain_notify('this is from site.pp') }
       expected that the catalogue would contain Notify[this is from site.pp]
     # ./spec/classes/testmodule_spec.rb:6:in `block (3 levels) in <top (required)>'

Finished in 0.27405 seconds (files took 1.15 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/classes/testmodule_spec.rb:6 # testmodule with default for all parameters should contain Notify[this is from site.pp]

/home/brandon.burnett/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/brandon.burnett/development/testmodule/local/vendor/ruby/2.1.0/gems/rspec-core-3.2.3/lib:/home/brandon.burnett/development/testmodule/local/vendor/ruby/2.1.0/gems/rspec-support-3.2.2/lib /home/brandon.burnett/development/testmodule/local/vendor/ruby/2.1.0/gems/rspec-core-3.2.3/exe/rspec --pattern spec/\{classes,defines,unit,functions,hosts,integration\}/\*\*/\*_spec.rb --color failed
```

**Comment by DavidS** [comment]
Thanks for the excellent bug documentation. I've tested this locally and can confirm that these tests work with puppet 3.8.3 and fail with puppet 4. I suspect that the setup code for puppet 4 is incomplete and will have a look.

**Comment by DavidS** [comment]
I've looked a bit into the code around this, and it's all over the place. I didn't find a quick fix and need to allocate some quality time for this, which might not happen soon.

**Comment by wachr** [comment]
Any updates for this?

@DavidS, could you outline the problem enough for someone else to start working on a PR?

**Comment by binford2k** [comment]
@DavidS ping, is this on a roadmap?

**Comment by DavidS** [comment]
@wachr  I could repro the bug easily with the example code from @dudemcbacon ; I don't know what else I could provide to help someone to work on this.

@binford2k there is no roadmap.

**Comment by DavidS** [comment]
Or rather, THIS is the roadmap.

**Comment by gpetras** [comment]
@DavidS, have you been able to look into this bug any further? Any help you can offer would be much appreciated!

**Comment by ajvb** [comment]
This is a debilitating bug for me at the moment.

**Comment by jcmcken** [comment]
@DavidS, would this also be a problem in 3.8 with the future parser enabled?

I'm using Puppet 3.8.4 and having this issue, but only when the future parser is enabled.

**Comment by jk2l** [comment]
+1 i think i got hit with this bug too.

**Comment by rnelson0** [comment]
This would not be a long term fix, but I think you could move the contents of `site.pp` into the `:pre_condition` value ala https://github.com/voxpupuli/puppet-zabbix/blob/9e0f7841f589075aee7b1e51fa4a1106026e6961/spec/defines/userparameters_spec.rb#L25 to have it evaluated before the tests, for the moment. This condition runs before the subsequent contexts. E.g.
```
let (:pre_condition) { "
  notify{ 'this is from site.pp': }
" }
```

Can you validate that it is a good workaround?

**Comment by jk2l** [comment]
hi @DavidS I dig into the code and found the source of problem. 

In Puppet 3, there is "import_str" it also produce the following line "import '/path/to/module/spec/fixtures/manifests/site.pp'". This import_str function is totally responsible on loading site.pp

Now with Puppet 4 dropping support of "import" keyword, this function usage also is being disabled. But also introduce a side effect that site.pp never get imported. 

I am not sure what is the best approach to solve this issue. 

code line 23: https://github.com/rodjek/rspec-puppet/blob/master/lib/rspec-puppet/support.rb

**Comment by jk2l** [comment]
I created a pull request, it tested with @dudemcbacon test module. Can't think of a better way to do this without import keyword
