### ISSUE TITLE
Diff does not show trailing newline at end of file

### ISSUE THREAD

**Issue by ghoneycutt** [rodjek/rspec-puppet#327]
The new diff style output is great though if a newline is at the end of the file, it does not show it.

comparison of

a file with an empty line at the bottom
```
foo
bar

```
with

a file without an empty line at the bottom
```
foo
bar
```

results in

    Failure/Error: it { should contain_file('foo').with_content(fixture) }
       expected that the catalogue would contain File[foo] with content set to supplied string
       Diff:

After reverting from using master in the git repo in my Gemfile to using the newest release it gave me the old style string output where it was obvious that the file ended with "\n\n" instead of "\n"

If I put dummy data at the beginning of the file or otherwise, it would correctly show empty lines with a `+` sign on its own line as you would expect from diff, though the last line it seems to be missing.

**Comment by DavidS** [comment]
This is an upstream rspec issue. I've submitted that as https://github.com/rspec/rspec-core/issues/2134

**Comment by ghoneycutt** [comment]
@DavidS Thank you!!!
