### ISSUE TITLE
Removed 2.2.1-pre?

### ISSUE THREAD

**Issue by ITler** [rodjek/rspec-puppet#328]
Something goes wrong when bootstrapping new puppet module
`bundle install` leads to
    [...]
    Using puppet-lint-trailing_comma-check 0.3.1
    Using puppet-lint-unquoted_string-check 0.2.5
    Using puppet-lint-version_comparison-check 0.1.2
    Using puppet-syntax 2.0.0

    NoMethodError: undefined method `spec' for nil:NilClass
    An error occurred while installing rspec-puppet (2.2.1.pre), and Bundler cannot continue.
    Make sure that `gem install rspec-puppet -v '2.2.1.pre'` succeeds before bundling.

A few days ago, I think, this did work. I've to admit, that I don't know how to check, where the dependency for tag _2.2.1.pre_ is coming in. As workaround I could remove this line from [Gemfile](https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/Gemfile):

    # Gemfile
    # not working: gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'

to install other gems, but this won't help me setting up a fresh development environment.

Could you please assist, maybe by rebuilding 2.2.1-pre to have a straightforward work-around?

Thanks a lot

**Comment by DavidS** [comment]
The quick fix is to just remove the :git part, then it will use the 
released version, not the current master.

But thanks for reporting that, I'll have a look what's actually causing 
that.

**Comment by DavidS** [comment]
I've tested this with the current master and it installed fine. Generally when running into bundler issues, I recommend removing your Gemfile.lock, your .bundle directory and the location you're using to install gems to (.bundle/vendor by default).

See http://rnelson0.com/2015/11/19/getting-a-fresh-start-in-a-git-repository/ for details on how to clean a git repo.

**Comment by ITler** [comment]
thanks!!
