### ISSUE TITLE
Testing XML

### ISSUE THREAD

**Issue by evansj** [rodjek/rspec-puppet#330]
I'm trying to find a way to test XML with rspec-puppet.

I have a resource which creates an XML file via an erb template. I want to do something like:

```ruby
    it { should contain_file('/tomcat/server.xml').
        .with_content_xpath('/Server[@port=8005]')
    }
```

I can write some xml tests, I just don't know how I "get" the contents of the generated file as a string so that I can test it from the spec file, using something like [this nokogiri example](https://gist.github.com/Fivell/8025849). Any help would be appreciated!

**Comment by choffee** [comment]
I think you can pull out file content with something like:

    content = catalogue.resource('file', '/tomcat/server.xml').send(:parameters)[:content]

You can then use rspec matches with that content.

It's not documented anywhere that I could see but I used something similar for validating YAML files.

**Comment by evansj** [comment]
@choffee that worked perfectly - many thanks!
