### ISSUE TITLE
Changelog on website does not match one in source.

### ISSUE THREAD

**Issue by choffee** [rodjek/rspec-puppet#331]
Is the change log on the website generated automatically?

http://rspec-puppet.com/changelog/

It only shows version 1.0.1.

Could it be change to just point to the git hub one?

**Comment by DavidS** [comment]
This is all done in https://github.com/rodjek/rspec-puppet/tree/gh-pages . It'd be awesome if anyone could have a go at this and update all the 2.x stuff into those pages.
