### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mmoll** [rodjek/rspec-puppet#332]
Would it be possible to cut a new release soon? I'm especially interested in having a released version containing the changes in #329.

**Comment by roidelapluie** [comment]
I guess #334 and #333 could be merged before making a new release.

**Comment by mmoll** [comment]
indeed.

**Comment by DavidS** [comment]
I've started cleaning up the changelog at https://github.com/rodjek/rspec-puppet/pull/339 in preparation for this.

**Comment by mmoll** [comment]
thanks!
