### ISSUE TITLE
Creating compound matchers

### ISSUE THREAD

**Issue by itissid** [rodjek/rspec-puppet#336]
I am on 2.12 version of rspec, Can we use abstractions like or/and like: https://www.relishapp.com/rspec/rspec-expectations/v/3-4/docs/compound-expectations with rspec puppet?

**Comment by DavidS** [comment]
The rspec documentation of 2.12 does not seem to describe compound expectations. This is not an rspec-puppet problem then.

What reason do you have for staying at such an ancient version?

**Comment by jantman** [comment]
rspec 3.1.0's documentation *does* describe compound matchers, but they still seem to not work with rspec-puppet... though maybe I'm missing something about how to properly use them. Would it be possible to get this reopened and either verified as valid, or an example of how they should work?

**Comment by DavidS** [comment]
@jantman there is already #365 describing a similar issue. Does that match what you're looking for?

**Comment by jantman** [comment]
@DavidS I suppose so? I honestly don't know enough about the internals of rspec to say with certainty. All I know is that I want to be able to do something like:

```
contain_file('foo).with_only('bar' => 'baz').or contain_file('foo').with_only('bar' => 'blam')
```
