### ISSUE TITLE
mocking function using Puppet::Parser::Functions.newfunction doesn't work

### ISSUE THREAD

**Issue by keymone** [rodjek/rspec-puppet#342]
i've tracked this down to environment where puppet stores `#newfunction`-created functions, some debugging putses:

    Functions.reset, usual before(:each)
    Functions.environment_module for *root* is created
    `newfunction`s go into *root* env
    Functions.environment_module for rp_env is created and used for specs

rp_env environment ends up without any functions created in `before`-hooks

**Comment by DavidS** [comment]
ouch. can you add a snippet of your before-hook, how you are defining these mocks?

**Comment by keymone** [comment]
i think this can be discarded as i was basically chasing ghosts. function i tried to mock was hiera and in newer puppet version (3.8+?) it has been switched to puppet 4x function api.

**Comment by DavidS** [comment]
Thanks!
