### ISSUE TITLE
How handle resource Type validation of `File.exists?` with rspec-puppet 2.3.0

### ISSUE THREAD

**Issue by fatmcgav** [rodjek/rspec-puppet#348]
Afternoon all

After upgrading to rspec-puppet 2.3.0, I've hit an issue whereby I've got a failing test[1] on a defined type [2][3], that's using a custom resource[4], which has got a `File.exists?` validate block[5]... 
Obviously when testing on TravisCI, that file doesn't exist, and I've got no way of making it exist AFAIK... 

What I could do with some pointers on is how to handle this scenario and make the test pass? 
It's probably worth adding that this test passed with rspec-puppet 2.2.0[6]...

Any ideas? 

Cheers
Gavin 

[1] https://travis-ci.org/fatmcgav/fatmcgav-glassfish/jobs/100859787#L1467-L1472 
[2] https://github.com/fatmcgav/fatmcgav-glassfish/blob/develop/manifests/create_domain.pp
[3] https://github.com/fatmcgav/fatmcgav-glassfish/blob/develop/spec/defines/create_domain_spec.rb#L134-L166
[4] https://github.com/fatmcgav/fatmcgav-glassfish/blob/develop/lib/puppet/type/domain.rb
[5] https://github.com/fatmcgav/fatmcgav-glassfish/blob/develop/lib/puppet/type/domain.rb#L79-L87
[6] https://travis-ci.org/fatmcgav/fatmcgav-glassfish/jobs/94887206#L252-L254

**Comment by DavidS** [comment]
I don't understand how this ever worked. You need to either stub `File.exists?` for these tests or create the file in a `:before` block (and clean it up in `:after`).

**Comment by fatmcgav** [comment]
Hehe, indeed.. 

I've tried stubbing `File.exists?`[1] for the `/tmp/template.xml` file, but that causes other errors[2]...

Any pointers?

[1] https://github.com/fatmcgav/fatmcgav-glassfish/commit/9dbf3d04b0ef215f49be5a48d21aafedce5c902c
[2] https://travis-ci.org/fatmcgav/fatmcgav-glassfish/jobs/101125286#L1470-L1478

**Comment by DavidS** [comment]
I'll have to look into that on monday, as it explicitely tells you that
File.exists? was not called. Too confusing.

**Comment by fatmcgav** [comment]
Hehe, cheers...

**Comment by adrienthebo** [comment]
It looks like this was introduced in 9c295b5de726128bc08acfb1efaeaf5987174563 ; that code calls `#to_ral` on resources which actually creates `Puppet::Type` instances and sets parameters - and setting a parameter triggers a call to the validate function. The validate functions are only meant to be applied on the agent during catalog application, whereas rspec-puppet unit tests are meant to only test the catalog, so by converting resources to their RAL equivalents this seems to break any type that might have validation functions like this.

**Comment by adrienthebo** [comment]
Correction - any types that both have validation hooks that may touch the system and have autorequires will trigger this behavior. I believe that the autorequires are only available by creating an instance of the type, and setting up the type triggers that validation.

One option could be to monkey patch custom types and rip out the validation function when RSpec is running; short of that I don't see any good solutions.

**Comment by DavidS** [comment]
Thanks for the analysis! to_ral sets up all relationships within the
catalog, which is required for the transitive dependency checking.  Otoh ,
the stubbing should have caught that, so I'll have another look at that
later today.

**Comment by DavidS** [comment]
Ah, of course! The catalog is built only once for the complete group (caching, yay!) so the second example will have the expectation, but not the compilation to match it. Replace `expects` with `stubs` to remove the assertion, while keeping the fake implementation.

**Comment by fatmcgav** [comment]
@DavidS So what would you recommend?

Changing `File.expects?` with `File.stubs?`?

**Comment by DavidS** [comment]
In https://github.com/fatmcgav/fatmcgav-glassfish/commit/9dbf3d04b0ef215f49be5a48d21aafedce5c902c#diff-51c7ec588ec9f75fa3df5d5a7d2e7b50R159, change

```
File.expects(:exists?).with('/tmp/template.xml').returns(true).once
```

to

```
File.stubs(:exists?).with('/tmp/template.xml').returns(true)
```

**Comment by fatmcgav** [comment]
Still seem to be getting the *unexpected invocation* error:

```diff
diff --git a/spec/defines/create_domain_spec.rb b/spec/defines/create_domain_spec.rb
index 1459722..8cf69c5 100644
--- a/spec/defines/create_domain_spec.rb
+++ b/spec/defines/create_domain_spec.rb
@@ -156,7 +156,7 @@ describe 'glassfish::create_domain' do
     end

     it do
-      File.expects(:exists?).with('/tmp/template.xml').returns(true).once
+      File.stubs(:exists?).with('/tmp/template.xml').returns(true)^M
       should contain_glassfish__create_service('test').with({
         'running'      => 'true',
         'mode'         => 'domain',
```

Results in:
> Failures:

>  1) glassfish::create_domain with a domain template file specified should contain Glassfish::Create_service[test] that requires Domain[test]
     Failure/Error: }).that_requires('Domain[test]')
     Mocha::ExpectationError:
       unexpected invocation: File.exists?('/Users/gavinw/Puppet/modules/fatmcgav/glassfish/spec/fixtures/modules/manifests/init.pp')
       satisfied expectations:
       - allowed any number of times, not yet invoked: #<Puppet::Util::Feature:0x7fcb34386628>.root?(any_parameters)
       - allowed any number of times, not yet invoked: File.exists?('/tmp/template.xml')
     # ./spec/defines/create_domain_spec.rb:165:in `block (3 levels) in <top (required)>'

**Comment by fatmcgav** [comment]
OK, looks like I've come up with a work-around in a4a218ae410a943542ae27683d6193e9aad6c02c... 
Am using Tempfile to create a file on FS, and passing that path through to the relevant places... 

So will go-ahead and close this one off... Might look at updating the docs' for rspec-puppet to make this scenario clearer, as I can't be the only person this change has affected... :S

**Comment by DavidS** [comment]
@fatmcgav thanks to working through this. Adding a note to the documentation is always great, but I also need to add that doing agent-side verification in the type is not very mainstream. I think this is a very vaguely defined area in puppet.
