### ISSUE TITLE
ensure_resources or ensure_packages from fixtures are picked up in coverage report

### ISSUE THREAD

**Issue by joshsouza** [rodjek/rspec-puppet#364]
I recently put together a test that has willdurand/nodejs as a dependency. After getting everything operational, I was getting reports of missing coverage as follows:

```
Untouched resources:

  File[nodejs-install-dir]
  Package[g++]
  Package[gcc-c++]
  Package[make]
  Package[python]
```

These are part of the nodejs module, and shouldn't be in my coverage tests, but they are not being filtered out. I discovered that this is due to how ensure_resource() and ensure_package() elements are added to the catalog. (Particularly, they have no file/line associated with where they come from)
I added this to 'def filter_resource?' in the coverage.rb:

```
      if resource.type != 'Class' and ! resource.line and ! resource.file
        puts 'Ignoring:'
        puts resource.to_s
        return true
      end
```

Which corrects the behavior, but I feel that is a 10-ton mallet for a 2 penny nail and is likely to break things like defined types and ensure_resource/package entities that are actually a part of the class in question.
I haven't dug incredibly deep into how rspec-puppet operates, but couldn't find a sane way to isolate this type of resource (defined in a different class, but not clarified within the resource), and I assume that the incredible minds that created this thing will have a much better idea for a proper fix.

Just thought I'd pass it along.

**Comment by cdenneen** [comment]
+1

**Comment by glarizza** [comment]
Filed this in response:  https://tickets.puppetlabs.com/browse/PUP-6530

**Comment by joshsouza** [comment]
Much appreciated!
