### ISSUE TITLE
Testing dynamically named resources?

### ISSUE THREAD

**Issue by ITler** [rodjek/rspec-puppet#366]
I've got a question. I'd like to test something like this:

```
class some_class_containing_file_resource() {
    $dynamic = 'dynamic-file-name'

    file { "/static-part-of-path/${dynamic}":
        [...]
    }
}


context 'how to test dynamically named resources?' do
    let(:pre_condition) do
        "class { 'some_class_containing_file_resource': }"
    end
    it do
        is_expected.to contain_file("/static-part-of-path/dynamic-file-name")
    end
end
```

The file resource under test comes from `some_class_containing_file_resource` class. Imagine the `dynamic-part-of-path` in file resource is held by a variable within the class.

Do I have a chance to reference the class variable (`$dynamic`) in the test? Something like:

```
it do
    is_expected.to contain_file("/static-part-of-path/#{pre_conditioned_class::dynamic}")
end
```

This would allow me to keep default values out of spec files.

**Comment by rodjek** [comment]
Unfortunately not. The variables in your manifest are not included in the compiled catalogue, which is what rspec-puppet is testing.
