### ISSUE TITLE
Support parallel_tests

### ISSUE THREAD

**Issue by daenney** [rodjek/rspec-puppet#367]
The issue name says it all. Make sure we can (safely) run tests in parallel by leveraging the `parallel_tests` gem. This becomes more and more important as test suites grow. puppetlabs-apache now takes a whole 7 minutes but every of those `_spec.rb`'s should be able to run fully independently.

**Comment by daenney** [comment]
I tried this on puppetlabs-apache after installing `parallel_tests` in the bundle and it seems to work as is:

```
bundle exec spec_prep
bundle exec rake parallel:spec[spec/{classes,defines,unit,functions,hosts,integration,types}/.\*/.\*_spec.rb]
1368 examples, 0 failures

Took 149 seconds (2:29)
```

I'm weary of the caching mechanism in rspec-puppet though and how this might be affected.

**Comment by DavidS** [comment]
AFAIK the parallel spec gem does fork off a new sub process for each
thread, so this should be very safe.

**Comment by alexharv074** [comment]
FWIW I wrote a blog post showing how to set up parallel_tests  http://razorconsulting.com.au/parallelising-rspec-puppet.html

**Comment by daenney** [comment]
@alexharv074 Awesome, thank you! I was working on something similar for the test matrix here.

**Comment by alexharv074** [comment]
:+1:

**Comment by hunner** [comment]
Also, puppetlabs_spec_helper recently added parallel fixtures cloning: https://github.com/puppetlabs/puppetlabs_spec_helper/pull/126

**Comment by domcleal** [comment]
I also opened a PR to puppetlabs_spec_helper to split up tests using CI/Travis matrices: https://github.com/puppetlabs/puppetlabs_spec_helper/pull/116.

**Comment by hunner** [comment]
Cool! Merged.

**Comment by rodjek** [comment]
Going to close this out as there's nothing really actionable here
