### ISSUE TITLE
rspec-puppet tutorial still recommends deprecated 'should'

### ISSUE THREAD

**Issue by alexharv074** [rodjek/rspec-puppet#374]
I notice in a lot of questions at ask.puppetlabs.com people still use the deprecated "should" in rspec-puppet tests rather than "is_expected.to".  I suspect that's because the [rspec puppet tutorial](http://rspec-puppet.com/tutorial/) still uses "should".  I can't see where to raise a PR or I'd fix it myself, but should be low hanging fruit for someone.

**Comment by igalic** [comment]
@alexharv074 can you provide a patch for this?
from what i gather, the docs are in the gh-pages branch https://github.com/rodjek/rspec-puppet/tree/gh-pages

**Comment by alexharv074** [comment]
Ah, there it is.  OK, no worries.

**Comment by igalic** [comment]
\o/

**Comment by alexharv074** [comment]
Here you go https://github.com/rodjek/rspec-puppet/pull/375

**Comment by igalic** [comment]
wh00t
it (still) auto-deploys! hurray :D
