### ISSUE TITLE
:undef broken in v2.4.0

### ISSUE THREAD

**Issue by deric** [rodjek/rspec-puppet#378]
Using `:undef`
```
let(:params) {{
  :value   => :undef,
}}
```
is causing `Undefined variable "value"` error with `STRICT_VARIABLES` on Puppet 3. Downgrading to `v2.3.2` resolves the problem. See deric/puppet-mesos#70. The code works fine with Puppet 4.

**Comment by domcleal** [comment]
I don't think strict variables was initialised correctly in v2.3.2, so the v2.4.0 behaviour is probably correct.  There were some bug reports and discussions on #voxpupuli yesterday after the 2.4.0 release and this seemed to be @DavidS's conclusion.

The essence of the manifest you linked to seems to fail in plain Puppet 3.8 with strict variables, without even invoking rspec-puppet:

<pre>
$ be puppet --version
3.8.6
$ be puppet apply --strict_variables
define property (
  $value
) {
  warning($value)
}

property { 'test':
  value => undef,
}
^D
Error: Undefined variable "value" at line 4 on node cobalt
</pre>

The same manifest does indeed work under Puppet 4, but not on 3 with strict variables (and either parser).

**Comment by deric** [comment]
Ok, thanks for explanation. So, proper solution would be
```puppet
define property (
  $value = undef,
) {
  warning($value)
}
```
right?

**Comment by domcleal** [comment]
I'm not certain, but that looks reasonable and it does seem to work.
