### ISSUE TITLE
Support data_provider from metadata

### ISSUE THREAD

**Issue by xaque208** [rodjek/rspec-puppet#385]
Puppet4 brings native data in modules.  When using hiera as the data_provider, rspec-puppet doesn't seem to respect the variables in the data directory for the module.  I'd love to start converting my modules away from the params pattern.  This support will be key to making that happen.  Please help?

**Comment by DavidS** [comment]
Have you had a look at the [hiera integration](https://github.com/rodjek/rspec-puppet#hiera-integration) section in the README? I haven't yet had time to check that out, but it would be great to have that documented/supported.

**Comment by xaque208** [comment]
Thank you @DavidS, I've just read it over and modified my tests.  In `spec_helper` I've added `c.hiera_config = 'hiera.yaml'`, as well as `let(:hiera_config) { 'hiera.yaml' }` at the beginning of my tests, and neither of them seem to operate as I expect.  It seems that either the new format for `hiera.yaml` is not supported, but I'm also assuming that the `hiera.yaml` is being loaded from the root of the module.

**Comment by DavidS** [comment]
@xaque208 , that's disappointing, but thanks for your feedback.

**Comment by xaque208** [comment]
@DavidS yes quite.  It means I (we) effectively cannot move my modules to use the new puppet4 patterns with testing.

**Comment by darkstar42** [comment]
Any progress on this issue?

**Comment by nce** [comment]
Maybe the issue lies with the [new hiera format](https://docs.puppet.com/puppet/4.5/reference/lookup_quick_module.html#example-with-hiera)? Nevertheless we'd be quite happy if this feature would be supported. Thanks for your efforts!

**Comment by cyberious** [comment]
Any progress on this, I am seeing an issue with nested module data not working when testing it further up the chain, however the module itself tests defaults fine.

**Comment by xaque208** [comment]
I've been able to get testing to work.  I don't know if it was the particular version of code(s) that I was on, but I no longer have this issue.

@cyberious I did run into an issue where I was trying to reference something like `os.family.lsb.blabla`, where, if `blabla` was not a key, the whole thing would just fail (maybe a hiera bug).  I think that was it.  

Here is an example module I've updated to use hiera data: https://github.com/xaque208/puppet-unbound

**Comment by xaque208** [comment]
Also, sorry for not coming back to report my success on this sooner.  I forgot.  If someone else can confirm, I think this can be closed.

**Comment by kemra102** [comment]
I'm still not able to get this working with Hiera data in modules even after setting the Hiera config with: https://github.com/rodjek/rspec-puppet#enabling-hiera-lookups

I suspect like others have mentioned that the new Hiera format is simply not supported.

**Comment by DavidS** [comment]
Folks, the NTP module has hiera data for all class parameters, got rid of the params class, and tests fine without any special configuration. See https://github.com/puppetlabs/puppetlabs-ntp/commit/5a6bfb71fe1f4796964400f2fc264c8094786d5c for the code changes.

Can someone who's experiencing the issue in their code do a proper write-up with example code, runtime versions (ruby, puppet, facter, rspec-puppet, Gemfile.lock, etc) and post that here?

**Comment by sford** [comment]
@DavidS thanks for the tip regarding the ntp module... that helped me get this working. In my case, I had an incomplete `metadata.json`... things appear to fail badly if there are any missing fields.

To recap, this worked for me:

1. Use latest version of all relevant libraries
2. Follow the [Puppet instructions for module hiera lookups](https://docs.puppet.com/puppet/latest/lookup_quick_module.html)
3. Make sure required `metadata.json` fields are present:
        
        {
          "name": "",
          "version": "",
          "author": "",
          "license": "",
          "source": "",
          "dependencies": [],
          "data_provider": "hiera",
          "description": ""
        }

**Comment by DavidS** [comment]
the metadata-json-lint gem helps with finding those issues.

**Comment by rodjek** [comment]
Sounds like this can be resolved with an update to the README then
