### ISSUE TITLE
Need help with testing registry entries

### ISSUE THREAD

**Issue by dandunckelman** [rodjek/rspec-puppet#389]
I'm struggling to get testing to work w/ the https://github.com/puppetlabs/puppetlabs-registry module.

I have a manifest that helps setup Chrome as the default browser on Windows 2012, which contains this:

```
registry_key { 'HKLM\SOFTWARE\Policies\Microsoft\Windows\System':
  ensure => present,
}->

registry_value { 'HKLM\SOFTWARE\Policies\Microsoft\Windows\System\DefaultAssociationsConfiguration':
  data   => 'c:/tmp/defaultapps.xml',
  ensure => present,
  type   => string,
}
```

And a test like this:

```
it { should contain_registry_key("HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System")
  .with(
    "ensure" => "present",
  )
}

it { should contain_registry_value("HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\\DefaultAssociationsConfiguration")
  .with(
    "ensure" => "present",
  )
  .that_requires("Registry_key[HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System]")
}
```

which results in this failure:

```
1) CLASS_NAME should contain Registry_value[HKLM\SOFTWARE\Policies\Microsoft\Windows\System\DefaultAssociationsConfiguration] that requires Registry_key[HKLM\SOFTWARE\Policies\Microsoft\Windows\System]
   Failure/Error:
     it { should contain_registry_value("HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\\DefaultAssociationsConfiguration")
       .with(
         "data"   => 'c:/tmp/defaultapps.xml',
         "ensure" => "present",
         "type"   => "string",
       )
       .that_requires("Registry_key[HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System]")
     }

   NoMethodError:
     undefined method `resource_type' for Registry_key[HKLM\SOFTWARE\Policies\Microsoft\Windows\System]:Puppet::Type::Registry_key
   # ./spec/classes/default_browser_spec.rb:41:in `block (2 levels) in <top (required)>'
```

The line number, 41, is referring to

```
.that_requires("Registry_key[HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System]")
```

I've also tried these:

```
.that_requires("Registry_key[HKLM/SOFTWARE/Policies/Microsoft/Windows/System]")

# and this:
.that_requires("Registry_key[HKLM\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\System]")
```

And both give errors like this:

```
expected that the catalogue would contain Registry_value[HKLM\SOFTWARE\Policies\Microsoft\Windows\System\DefaultAssociationsConfiguration] with that requires Registry_key[HKLM/SOFTWARE/Policies/Microsoft/Windows/System]

# and this:
expected that the catalogue would contain Registry_value[HKLM\SOFTWARE\Policies\Microsoft\Windows\System\DefaultAssociationsConfiguration] with that requires Registry_key[HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System]
```

Unfortunately, I **must** have the backslashes in the manifest, otherwise it won't work when applied on a node.  So this issue is isolated to the test of this particular module (as far as I can tell).

Any help is greatly appreciated.  Thanks

**Comment by ferventcoder** [comment]
@dandunckelman I think that the wsus_client may have some tests that use registry and do verification with rspec-puppet.

**Comment by ferventcoder** [comment]
@dandunckelman Also, you may consider joining the slack community - slack.puppet.com

**Comment by ferventcoder** [comment]
Here are the specs for wsus that check registry items - https://github.com/puppetlabs/puppetlabs-wsus_client/blob/master/spec/classes/init_spec.rb

**Comment by dandunckelman** [comment]
@ferventcoder thanks for finding that spec for me (I probably should've dug around the other windows-related modules).  I'll jump on slack ASAP (thx for the tip).

Unfortunately, my failure occurs when ensuring the **require** relationship:
```
.that_requires("Registry_key[HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System]")
```

and the tests in the wsus_client module doesn't check for those relationships.  I'll dig thru the other Windows modules to see if I can find a match for my failure.

Thanks

**Comment by ferventcoder** [comment]
Could be a limitation in rspec-puppet not dealing well with backslashes.

**Comment by ferventcoder** [comment]
@DavidS ^^

**Comment by DavidS** [comment]
Hi @dandunckelman , I've tried to reproduce the error you're seeing with your code, the current registry module's master, the current rspec-puppet master, and puppet 4.4.1, and failed. Can you specify more details on your environment?

**Comment by dandunckelman** [comment]
@DavidS thanks.  I'm glad to hear it works as expected in the latest/greatest.

Here's more info about my environment:
- Module Version:  1.1.3
- Ruby:  1.9.3-p484
- Puppet:  3.7.5
- RSpec-Puppet:  2.4.0
- OS:  Windows 2012 R2

Please let me know if you'd like any other info.

Thanks

**Comment by joeypiccola** [comment]
I wonder if I have hit the same issue. I have the following test. 
```
it {
  is_expected.to contain_registry_value('aes_128_128_enabled').that_requires(
    'registry_key[aes_128_128]',
  )
}
```
The above tests produces the following error.
```
failed: rspec: ./spec/classes/ciphers/aes_128_128_spec.rb:29: undefined method `resource_type' for #<Puppet::Type::Registry_key:0x00007ffc3b43e628>
  crypto_win::ciphers::aes_128_128 on windows-2008 R2-x64 passes with minimal params should contain Registry_value[aes_128_128_enabled] that requires registry_key[aes_128_128]
  Failure/Error:
          }

          it {
            is_expected.to contain_registry_value('aes_128_128_enabled').that_requires(
              'registry_key[aes_128_128]',
```
