### ISSUE TITLE
Incorrect trusted node data

### ISSUE THREAD

**Issue by jk2l** [rodjek/rspec-puppet#400]
Trusted node data should have $trusted['certname'] that is like fqdn. curretnly it is being hardcoded by Puppet::Test::TestHelper as "testing"

I think this one should be set properly

**Comment by jk2l** [comment]
Note: the current trusted data in rspec break test case that depends on trusted data

**Comment by rodjek** [comment]
Looks like #444 has been merged in which also implements this, so I'll close this PR. Thank you for the contribution though!

**Comment by rodjek** [comment]
This should be resolved by #444, please reopen if it's still not working for you
