### ISSUE TITLE
Negative tests

### ISSUE THREAD

**Issue by sspreitzer** [rodjek/rspec-puppet#404]
Hi all

Short question: 

I wish to test if a resource is not declared within a class. Does this make sense in BDD and if so can rspec-puppet do it?

Thanks a lot and kind regards
Sascha

**Comment by domcleal** [comment]
Any rspec test can be negated, e.g. `it { should_not contain_service('foo') }`. It's brittle, but useful to test things like behaviour changes in a manifest based on parameters.

**Comment by sspreitzer** [comment]
Thank you @domcleal! I also checked the following and it is working:
```ruby
    it { is_expected.to_not contain_package('bind-utils') }
    it { is_expected.not_to contain_package('nmap-ncat') }
```
