### ISSUE TITLE
Passing param :undef is broken

### ISSUE THREAD

**Issue by leoarnold** [rodjek/rspec-puppet#407]
Using the below fixture and spec tests, the last test will fail.

**Problem:** Instead of passing the value `:undef`, the attribute `group` just gets assigned its default value `'users'`.

```Puppet
# spec/fixtures/modules/undef_test/manifests/init.pp
class undef_test(
  $user  = undef,
  $group = 'users'
) { }
```

```Ruby
# spec/classes/undef_spec.rb
require 'spec_helper'

describe 'undef_test' do
  it { should compile.with_all_deps }

  context 'with params unset' do
    it { should contain_class('undef_test').without_user }

    it { should contain_class('undef_test').with(group: 'users') }
  end

  context 'with group => undef' do
    let(:params) { { :group => :undef } }

    it { should contain_class('undef_test').without_user }

    it { should contain_class('undef_test').without_group }
  end
end
```

**Comment by domcleal** [comment]
This is normal Puppet behaviour - it simply generates `undef` in the manifest to test, so will obey whatever rules Puppet has for the keyword.

<pre>
$ cat undef.pp 
class undef_test(
  $user  = undef,
  $group = 'users'
) {
  notify { "group=$group": }
}

class { 'undef_test':
  group => undef,
}
$ puppet apply undef.pp 
Notice: Compiled catalog for cobalt in environment production in 0.20 seconds
Notice: group=users
Notice: /Stage[main]/Undef_test/Notify[group=users]/message: defined 'message' as 'group=users'
Notice: Applied catalog in 0.08 seconds
</pre>

(Tested on Puppet 4.6.1)

The :undef option will be most useful when you have a required parameter that you wish to pass undef to. If you remove the default value then you'll see that passing `:undef` is necessary to define the parameter.
