### ISSUE TITLE
Question: Ability to set value to other module's variable?

### ISSUE THREAD

**Issue by Envek** [rodjek/rspec-puppet#415]
May be dumb question.

I'm developing a module which should act differently depending on other module's variable.

When I've added such a check here https://github.com/Envek/puppet-pgtune/commit/a4bba9e352da69be632ebc4677d0339bb46f6ba1#diff-60ae41fd0a31977447947f59940ee9a4R124 my tests start to fail with errors like:

```
  1) pgtune with no parameters should contain Postgresql::Server::Config_entry[work_mem] with value => "627kB"
     Failure/Error: it { should contain_postgresql__server__config_entry('work_mem').with('value' => '627kB') }
     Puppet::PreformattedError:
       Evaluation Error: Comparison of: #<Puppet::Pops::Model::ModelLabelProvider:0x007fe860bc3f18> > String, is not possible. Caused by 'Only Strings and Numbers are comparable'. at /Users/envek/Code/puppet-pgtune/spec/fixtures/modules/pgtune/manifests/init.pp:124:33 on node envek-macbook-work-7.local
     # ./spec/classes/pgtune_spec.rb:9:in `block (3 levels) in <top (required)>'
```

However, on servers everything works as expected

I wondering may be it's because the `$postgresql::repo::version` variable on which I depends is not set when executing tests.

**Question**: Is there a way to specify value for some variable via `let` or something?

**Comment by DavidS** [comment]
You'll have to reproduce your setup (to the point of all required classes being included/configured) to make your tests pass. You can put your additional puppet setup code into `pre_condition` as used here: https://github.com/rodjek/rspec-puppet/blob/9eb2c6ffc7f2dd56e2a72ac4966482848ad148ba/spec/hosts/array_spec.rb#L4
