### ISSUE TITLE
Unknown variable on defined tests

### ISSUE THREAD

**Issue by shaunrampersad** [rodjek/rspec-puppet#416]
Hi

My puppet code has a variable that is not instantiated in the define but defined in the init.pp of the module. 
When writing a test case for the define type, it fails cause the variable is not set within that function. 

E.G:
```
define jboss::create_home (
   $user = 'test',
) {
  file ( "/${::jboss::homedir}/${user}":
     ensure => directory,
  }
}
```

The test case contains

```
        context "jboss create home" do
          let(:title) { 'user home' }
          let(:params) {{
            :user             => 'testuser',
          }}

         it { is_expected.to contain_file('//testuser')
            .with_content(/^{.....
```

The error after running tests is:
 ```
    Puppet::PreformattedError:
        Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown variable: '::jboss::homedir'. at ../puppet-jboss/spec/fixtures/modules/jboss/manifests/jboss_create_home.pp:4:13 at line 1 on node testnode
```

I'm using version 2.4.0 of rspec-puppet.

If I update the gem to pin to version 2.3.2, then the tests pass. 

I could set the $::jboss::homedir variable within the test but I'm not sure how this is done and I dont see it in the documentation.

Shaun

**Comment by DavidS** [comment]
Your `jboss::create_home` define requires the jboss class to be included and configured. You can either do that in your test in a `pre_condition`, or by adding `include jboss` in your define.

The changed behaviour you're seeing between rspec-puppet versions is because 2.4 has enabled strict variable checking by default on puppet 4.
