### ISSUE TITLE
RSpec::Puppet::Coverage.add_filter has incorrect logic

### ISSUE THREAD

**Issue by shadow999** [rodjek/rspec-puppet#424]
I tried to exclude my `class foo::bar` by calling `RSpec::Puppet::Coverage.add_filter('class', 'foo::bar')`. But it actually added `Class[Foo::bar]` into the array. This will not work, since catalog contains `Class[Foo::Bar]`. 

I am wondering if `add_filter` can detect if it is class type then capitalize the first letter of the entire string and also the first letter after `::`?

**Comment by shadow999** [comment]
#425

**Comment by DavidS** [comment]
Merged #425
