### ISSUE TITLE
Hiera.lookup and interpolation

### ISSUE THREAD

**Issue by fatmcgav** [rodjek/rspec-puppet#427]
I'm trying to use rspec-puppet and `Hiera.lookup` within a spec test to generate a dynamic hash, which I'm then looping over to create test cases... 

However, I'm having issues with `Hiera.lookup` not correctly interpolating fact values within my Hiera data. 

Full code example is available here: https://gist.github.com/fatmcgav/5c272727756665c0e6e52731e1cc2179

Any pointers on how I can get these tests working?

Cheers

**Comment by DavidS** [comment]
From a quick reading you're using hiera correctly, but I'm no expert of its ruby interface. I would not be surprised if some part of rpsec/mocking hackery is interfering with what you're doing.

In general I'd recommend avoiding referencing external data - especially from the thing your testing - in your test setup. Building out the strings yourself in the test (e.g. using the `facts` hash from `on_supported_os`) would help on both counts.
