### ISSUE TITLE
Checking for packages that match a regex name.

### ISSUE THREAD

**Issue by traylenator** [rodjek/rspec-puppet#431]
I was trying to check that there were no packages matching a particular regex present.

The guess of 

```ruby
it { is_expected.not_to contain_package(%r{^sclo-.*$}) }
```

never fails a catalogue. Is something like this possible?

**Comment by domcleal** [comment]
I don't think there are any matchers that support regexes against the resource titles. You would probably have to inspect the catalog directly, which is accessible via `catalogue`, e.g.

    it { expect(catalogue).not_to satisfy('contain sclo-* packages') { |c| c.resource_refs.any? { |r| r.start_with?('Package[sclo-') } } }

`catalogue.resource_refs` returns an array of `ResourceType[title]` strings.

**Comment by traylenator** [comment]
@domcleal that works great and I can see generally useful  for other weird and wonderful things - thanks.
