### ISSUE TITLE
Help: How to setup rspec-puppet when i have hiera_include('classes') in manifests/site.pp

### ISSUE THREAD

**Issue by Cosaquee** [rodjek/rspec-puppet#432]
Hello, i want to setup rspec-puppet for my puppet project but the problem is that i do not have my manifests in `manifests` folder. I just have one line: `hiera_include('classes')` and Puppet code lives in `site` folder in `profile`,  `roles` and `common` folders. Can you guide me how to setup everything so i can write tests for classes that are in `site` folder ?

**Comment by DavidS** [comment]
Please follow the "Hiera Integration" section in the README: https://github.com/rodjek/rspec-puppet/#hiera-integration
