### ISSUE TITLE
"undefined method `[]' for false:FalseClass" against Puppet's master branch

### ISSUE THREAD

**Issue by domcleal** [rodjek/rspec-puppet#434]
Tests against Puppet's master branch (to be 4.9) are failing since [PUP-6980](https://tickets.puppetlabs.com/browse/PUP-6980) which changes slightly how the `hiera_config` setting is read. rspec-puppet sets hiera_config to `/dev/null`.

Example failure:

<pre>
  34) testhost should contain Class[sysctl::common]
      Failure/Error: Puppet::Resource::Catalog.indirection.find(node.name, :use_node => node)
      
      Puppet::PreformattedError:
        Evaluation Error: Error while evaluating a Function Call, undefined method `[]' for false:FalseClass at line 10:3 on node testhost
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/hiera_config.rb:114:in `create'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/configured_data_provider.rb:17:in `config'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/global_data_provider.rb:13:in `unchecked_key_lookup'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/data_provider.rb:45:in `block in key_lookup'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/invocation.rb:73:in `check'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/data_provider.rb:45:in `key_lookup'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:78:in `lookup_global'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:265:in `block in global_lookup_options'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:265:in `catch'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:265:in `global_lookup_options'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:274:in `env_lookup_options'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:244:in `block (2 levels) in retrieve_lookup_options'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/invocation.rb:116:in `with'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:240:in `block in retrieve_lookup_options'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/invocation.rb:58:in `lookup'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:239:in `retrieve_lookup_options'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:141:in `lookup_lookup_options'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:126:in `lookup_merge_options'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:58:in `block in lookup'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/invocation.rb:58:in `lookup'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/lookup_adapter.rb:50:in `lookup'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup.rb:77:in `search_and_merge'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/resource/type.rb:401:in `block (2 levels) in inject_external_parameters'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/resource/type.rb:400:in `catch'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/resource/type.rb:400:in `block in inject_external_parameters'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/resource/type.rb:396:in `each'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/resource/type.rb:396:in `inject_external_parameters'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/resource/type.rb:363:in `set_resource_parameters'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/resource/type.rb:171:in `evaluate_code'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/resource.rb:81:in `block in evaluate'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler.rb:51:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/resource.rb:73:in `evaluate'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/compiler.rb:395:in `each'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/compiler.rb:395:in `evaluate_classes'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/loader/../../../puppet/functions/include.rb:16:in `include'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/functions/dispatch.rb:47:in `invoke'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/functions/dispatcher.rb:36:in `block in dispatch'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/functions/dispatcher.rb:35:in `catch'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/functions/dispatcher.rb:35:in `dispatch'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/functions/function.rb:46:in `block in call'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/functions/function.rb:45:in `catch'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/functions/function.rb:45:in `call'
      # :10:in `block in call_function'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/runtime3_support.rb:284:in `eval'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/runtime3_support.rb:284:in `block in call_function'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler.rb:51:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/runtime3_support.rb:282:in `call_function'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/evaluator_impl.rb:941:in `call_function_with_block'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/evaluator_impl.rb:910:in `eval_CallNamedFunctionExpression'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/visitor.rb:69:in `visit_this_1'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/evaluator_impl.rb:82:in `evaluate'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/evaluator_impl.rb:638:in `block in eval_BlockExpression'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/evaluator_impl.rb:638:in `each'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/evaluator_impl.rb:638:in `reduce'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/evaluator_impl.rb:638:in `eval_BlockExpression'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/visitor.rb:69:in `visit_this_1'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/evaluator/evaluator_impl.rb:82:in `evaluate'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/parser/evaluating_parser.rb:63:in `evaluate'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/ast/pops_bridge.rb:32:in `evaluate'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/ast.rb:31:in `safeevaluate'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/resource/type.rb:181:in `block in evaluate_code'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/scope.rb:944:in `with_guarded_scope'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/resource/type.rb:179:in `evaluate_code'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/resource.rb:81:in `block in evaluate'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler.rb:51:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/resource.rb:73:in `evaluate'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/compiler.rb:555:in `evaluate_ast_node'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/compiler.rb:178:in `block (2 levels) in compile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler.rb:51:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/compiler.rb:178:in `block in compile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/context.rb:65:in `override'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet.rb:267:in `override'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/compiler.rb:162:in `compile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/parser/compiler.rb:33:in `compile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/indirector/catalog/compiler.rb:266:in `block (2 levels) in compile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util/profiler.rb:51:in `profile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/indirector/catalog/compiler.rb:264:in `block in compile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util.rb:223:in `block in benchmark'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/util.rb:222:in `benchmark'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/indirector/catalog/compiler.rb:262:in `compile'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/indirector/catalog/compiler.rb:53:in `find'
      # ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/indirector/indirection.rb:194:in `find'
      # ./lib/rspec-puppet/adapters.rb:74:in `catalog'
      # ./lib/rspec-puppet/adapters.rb:149:in `catalog'
      # ./lib/rspec-puppet/support.rb:213:in `build_catalog_without_cache'
      # ./lib/rspec-puppet/support.rb:222:in `block in build_catalog'
      # ./lib/rspec-puppet/cache.rb:17:in `call'
      # ./lib/rspec-puppet/cache.rb:17:in `get'
      # ./lib/rspec-puppet/support.rb:221:in `build_catalog'
      # ./lib/rspec-puppet/support.rb:30:in `block in load_catalogue'
      # ./lib/rspec-puppet/support.rb:188:in `with_vardir'
      # ./lib/rspec-puppet/support.rb:19:in `load_catalogue'
      # ./lib/rspec-puppet/example/host_example_group.rb:7:in `catalogue'
      # ./lib/rspec-puppet/support.rb:11:in `block in subject'
      # ./lib/rspec-puppet/matchers/create_generic.rb:82:in `call'
      # ./lib/rspec-puppet/matchers/create_generic.rb:82:in `matches?'
      # ./spec/hosts/testhost_spec.rb:4:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # NoMethodError:
      #   undefined method `[]' for false:FalseClass
      #   ./vendor/bundle/ruby/2.1.0/bundler/gems/puppet-ee07637150b2/lib/puppet/pops/lookup/hiera_config.rb:114:in `create'
</pre>

(https://travis-ci.org/rodjek/rspec-puppet/jobs/189123371)

A bisect of Puppet shows https://github.com/puppetlabs/puppet/commit/7c2889259933995745d65a9d7b105f6830e06267 as the cause, but it may be 331778e which changes how hiera_config is loaded. It now calls `YAML.load_file('/dev/null')`, which returns false rather than a hash.

**Comment by DavidS** [comment]
This is now tracked as https://tickets.puppetlabs.com/browse/PUP-7067

**Comment by domcleal** [comment]
PUP-7067 resolved, tests pass locally for me now.
