### ISSUE TITLE
puppet 4 freezes arguments for a function

### ISSUE THREAD

**Issue by vStone** [rodjek/rspec-puppet#442]
Puppet error: `Error while evaluating a Function Call, can't modify frozen hash `

Rspec-puppet should also freeze all parameters before passing them through to the function. Only after adding manual .freeze on the parameters, I'm able to reproduce the same error while running rspec tests

**Comment by domcleal** [comment]
Do you have a manifest you can show that reproduces this error?

I'm testing a very simple manifest (e.g. `test_function("a")`) with both Puppet 4 and 3 function APIs and no strings, arrays, hashes are passed frozen as far as I can tell, using Puppet 4.8.2.

I see a regression when a class name is passed in (fixed in #446), but I remain unsure if Puppet really does freeze function arguments.

**Comment by vStone** [comment]
I had a function that executed a keep_if on a hash which broke for me (whether or not that is a good idea is open for discussion) but it should have been detected by the tests.

**Comment by domcleal** [comment]
Was the hash defined in a manifest, or did it come from elsewhere? (e.g. Hiera, facts, ENC, another function)

**Comment by vStone** [comment]
It came from a fact

**Comment by domcleal** [comment]
Ah, thank you, that makes more sense now.

**Comment by vStone** [comment]
https://gist.github.com/vStone/1bc3dd691c93dac1b8b33b0add8e467a

**Comment by DavidS** [comment]
Would it make sense to restrict the freezing to a few well-known classes that would most likely cause issues, like String, Array, Hash, numbers?

**Comment by vStone** [comment]
Relevant api docs:
https://github.com/puppetlabs/puppet-specifications/blob/master/language/func-api.md#the-4x-api
`should not modify the scope`

**Comment by DavidS** [comment]
@vStone totally agreed. Given @domcleal 's findings on `Class` I wonder what else freezing stuff indiscriminately will break.

**Comment by domcleal** [comment]
> Looks like it does not matter if its a fact or regular variable:
> https://gist.github.com/vStone/1bc3dd691c93dac1b8b33b0add8e467a

Thanks, that's fascinating - the quoting seems to make a difference. If you quote 'foobar' with single quotes (as in your example), it's frozen. If you use double quotes (as I happened to), it's not frozen.

Either way, I think keeping the freezing is good - both to emulate this partial behaviour, and to test for scope modification.

I don't have any view on whether it's better to blacklist or whitelist classes though, I'm happy to change #446 to a whitelist if you'd prefer @DavidS.

**Comment by vStone** [comment]
I'm still digging through the puppet code to see where the freezing happens. will let you know if I find something.

**Comment by DavidS** [comment]
A huge :man_facepalming: on the single vs. double-quoting. Thanks for working through this, both of you. Getting an idea where that freezing happens will hopefully clear up what rspec-puppet should do.

**Comment by domcleal** [comment]
Despite the string inconsistencies, @vStone's correct in that facts are also frozen (both hashes and strings) so functions need to work reliably with both frozen and unfrozen data. Always testing them with frozen data seems the most useful behaviour to me.

**Comment by vStone** [comment]
Another relevant ticket: https://tickets.puppetlabs.com/browse/PUP-4825

**Comment by DavidS** [comment]
http://www.rubypigeon.com/posts/a-review-of-immutability-in-ruby/ has been a good read. 

Especially it points out that `freeze` is shallow. So freezing a hash might still leave a function open to erroneously modify a value contained in the hash.

**Comment by vStone** [comment]
https://github.com/adrienthebo/puppet/blob/fa522acf47f1ff632ef75a6c4cb4c1d1cf644024/lib/puppet/parser/scope.rb#L588

**Comment by vStone** [comment]
```
13:50 < vStone> Could somebody explain when/which/where function arguments are frozen before passing them through to a function? cfr https://github.com/rodjek/rspec-puppet/issues/442#issuecomment-275657629
13:50 < vStone> and/or update the relevant docs in https://github.com/puppetlabs/puppet-specifications/blob/master/language/func-api.md
13:57 < helindbe> vStone: there is no freezing going on in the function call API per se - that would be way to slow
13:57 < vStone> I got that far, but we are trying to determine where it IS happening
13:57 < helindbe> it is the responsability of each function to not mutate
13:57 < vStone> especially since we saw that double quoted strings are not frozen when passed, but single quoted strings and facts are.
13:58 < vStone> cc: Dominic 
13:58 < helindbe> oh, trying to figure out who/where froze what is an argument?
13:58 < vStone> yes
13:58 < vStone> if there is a rule that can be duplicated in rspec-puppet :)
13:58 < helindbe> evaluator does not freeze, so if something came from an operation on a string, that sting would not be frozen
13:59 < helindbe> the lexer freezes tokens IIRC
13:59 < helindbe> certainly all keywords etc.
13:59 < Dominic> makes sense, and it doesn't seem unreasonable that a single-quoted string would be frozen either
14:00 < helindbe> hashes freezes keys IIRC, but may hand out copies (not sure)
14:00 < helindbe> if it was not expensive, we would be freezing all data that ends up as values in the puppet language
14:01 < vStone> so its best to assume that all arguments passed are immutable
14:01 < helindbe> yes, always
```

**Comment by domcleal** [comment]
Indeed, for facts Puppet appears to deep freeze them instead: https://github.com/puppetlabs/puppet/blob/master/lib/puppet/parser/scope.rb#L775.
