### ISSUE TITLE
Resource not found when $name != $title

### ISSUE THREAD

**Issue by jarro2783** [rodjek/rspec-puppet#448]
When testing that a catalogue compiles correctly, we get a failure when the name of a resource is overridden explicitly, and we refer to the new name rather than the title of the resource.

Our specific case is that we use [the Elasticsearch module](https://github.com/elastic/puppet-elasticsearch), which sets `$name` in one of their `service` definitions. See https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/service/init.pp#L196

We use `notify => Service['elasticsearch-cluster']`, where `elasticsearch-cluster` is the value set by `$name`, and not the actual title of the `service` resource. When I run Puppet it works fine, but `rspec-puppet` complains:
```
error during compilation: Could not retrieve dependency 'Service[elasticsearch-support]'
```

**Comment by domcleal** [comment]
Can you show in more detail the example and matcher you're using that causes the issue?

I can reproduce an error when using `compile.with_all_deps`, but it isn't a compilation error, it's an error generated by the matcher (`expected that the catalogue would include Service[svc-name] used at [..]`), which makes me think your issue is different.

**Comment by jarro2783** [comment]
This is weird. I have made a minimal example and I can reproduce it with `compile.with_all_deps`, but not with just `compile`. However, my real code fails even with `compile`.

The full error is:
```
     Failure/Error: is_expected.to compile
       error during compilation: Could not retrieve dependency 'Service[elasticsearch-showcase]' of File_line[Set UseParNewGC]
```

The actual code is literally just:
```
it {
  is_expected.to compile
}
```

**Comment by jarro2783** [comment]
I've tracked it down. Elasticsearch is doing something different for `systemd` vs `openrc`. We are only using it on `openrc` hosts at the moment, hence I've never seen the error before.

Nevertheless, `compile.with_all_deps` does appear to be broken.

**Comment by DavidS** [comment]
@jarro2783 I still can't help you without more information on which module(s) you are using, and how your tests look like.

**Comment by domcleal** [comment]
I created a reproducer for the `compile.with_all_deps` and relationship matcher issues here: https://github.com/domcleal/rspec-puppet/commit/dbd1ce699923a0d08602a6dcfb9b3b81e87fa1a6

Resource references using the `name` can't find the resource, rspec-puppet only usually looks up resources by title or `alias` meta-parameters.

The original compilation error I think was simply a manifest bug.

**Comment by DavidS** [comment]
Thanks for the repro. This definitely should be fixed.

**Comment by jarro2783** [comment]
Sorry about the confusion. The example posted by @domcleal is the same as what I am talking about.
