### ISSUE TITLE
Automated resource helper spec output

### ISSUE THREAD

**Issue by luyseyal** [rodjek/rspec-puppet#450]
It would be cool if there were a command line utility to generate a skeleton spec for a given class. Obviously, this would be rudimentary. But, it would help newbies like myself get the hang of it.

Example:
`bundle exec rspec-create /path/to/class.pp /path/to/hiera/yaml operatingsystem`

That command would try to compile /path/to/class.pp including the yaml and operating system you defined. It would dump out an example spec using the defined resource types and whatnot it found.

Again, this is not a replacement for a proper spec.

This is about helping folks get started. :)

The "code coverage" report is what gave me the idea. That and working with grails.

Hope this is helpful to someone. Thank you for the hard work, everyone!

**Comment by DavidS** [comment]
have a look at https://github.com/nwops/puppet-retrospec

**Comment by luyseyal** [comment]
Thank you!
