### ISSUE TITLE
How-To doublecheck params values?

### ISSUE THREAD

**Issue by crashmaster** [rodjek/rspec-puppet#459]
Have a parms class like:

```
# params.pp
class xyz::params {
  $boo = 'boo_value'
}
```

How do I write a puppet rspec test for checking that `xyz::params::boo` is `boo_value` (should fail when it changes).

Thanks!

**Comment by domcleal** [comment]
rspec-puppet only really has [matchers](http://rspec-puppet.com/matchers/) that test the catalog generated by a Puppet compilation. Parameters or variables assigned in a manifest that aren't used for anything have no effect on the catalog, so I don't think there's any way to test their value.

Your tests should use rspec-puppet's resource matchers to check that resource parameters/properties are assigned correctly.

**Comment by crashmaster** [comment]
I see, thanks for the quick response!
