### ISSUE TITLE
Document how to pass params to modules in host tests

### ISSUE THREAD

**Issue by renflo** [rodjek/rspec-puppet#460]
I am desperately trying to find out how to pass params to modules in my spec/hosts tests. 

The following code is representative of what I have tried

```
require 'spec_helper'

describe 'myhost.example.com' do
  # Overriding parameters which are both encrypted *and* validated by the modules
  # As they would make the test fail.
  # let(:params) { { module: { id_var: '123' } } }
  # let(:params) { { ':module' => { ':id_var' => '123' } } }
  # let(:params) { { 'module' => { 'id_var' => '123' } } }
  # let(:params) { { ':module::id_var' => '123' } }
  # let(:params) { { 'module::id_var' => '123' } }
  # let(:params) { { 'module::params::id_var' => '123' } }
  # let(:params) { { id_var: '123' } }
  # let(:params) { { ':id_var' => '123' } }
  # let(:params) { { :id_var => '123' } }
  it { is_expected.to compile }
end
```

Please note that my rspec helper bootstrap hiera, so the param I'm trying to set is supposed to override the value already found by hiera. The reason why I do not fix the hiera config is because It's production configuration I'm trying to validate, so it cannot be changed _but_ a few variables are encoded by eyaml and I cannot give the credentials to decrypt them to all machines running the tests (for obvious reasons).

**Comment by domcleal** [comment]
rspec-puppet simply generates and runs Puppet manifests to create catalogs - there is no DSL syntax it can add to a manifest to override parameters on specific modules.

If you want to change values determined through data binding then you need to extend your data binding (i.e. Hiera) configuration, e.g. add a "testing" item to the hierarchy and populate it.

**Comment by renflo** [comment]
So `let(:params)` is usable in class specs but not in hosts specs?

**Comment by renflo** [comment]
Modifying the hiera config which is used by our real hosts in different environments and mixing "spec" config is not an alternative as it would open for scary bugs.

**Comment by domcleal** [comment]
> So let(:params) is usable in class specs but not in hosts specs?

Yes, because a class test generates a simple manifest containing `class { 'example': params ... }`. There is no equivalent syntax to pass parameters in when compiling a node catalog, except for facts.

**Comment by renflo** [comment]
I see. I would suggest updating the section "Testing hosts" in http://rspec-puppet.com/tutorial/ other might try this and struggle for a while. 

Do you know if there is a way for me to overwrite the value in hiera in another way (at test runtime)? is there a ruby object representing hiera I can use to modify the resolved configuration?

**Comment by domcleal** [comment]
The documentation appears accurate to me (it states that `params` is used for defined types and classes), but you can submit amendments to the `gh-pages` branch of this repo.

There isn't a supported method in rspec-puppet to modify the Hiera configuration or modify data binding at runtime.

**Comment by renflo** [comment]
ok. thanks.
