### ISSUE TITLE
Working with hiera data provider

### ISSUE THREAD

**Issue by TraGicCode** [rodjek/rspec-puppet#465]
After reading the documentation i'm still unsure on how i can use rspec-puppet + its hiera backend to alter data pulled in from hiera in order to test different code paths i have in my manifest.  For example i want to test this failure.  What is the recommended approach in order to achieve this?

```
# Configures the ntp services
class ntp::service inherits ntp {
  if ! ($ntp::service_ensure in [ 'running', 'stopped' ]) {
    fail('service_ensure parameter must be running or stopped')
  }

}

```

**Comment by rodjek** [comment]
rspec-puppet doesn't have a hiera backend as such. From the sounds of it, you probably want the [hiera-puppet-helper](https://github.com/mthibaut/hiera-puppet-helper) project that extends rspec-puppet to allow you to specify the hiera data for a particular spec

```
let(:hiera_data) { {'ntp::service_ensure' => 'something-that-isnt-running-or-stopped'} }
```
