### ISSUE TITLE
$facts hash is not available when testing a function

### ISSUE THREAD

**Issue by npwalker** [rodjek/rspec-puppet#503]
I've created an example repo of the problem here: https://github.com/npwalker/rspec_function_issue

Essentially, trying to use the $facts hash in a puppet code function results in it not being able to find the $facts hash.  Using top-scope variable references to the facts works.

**Comment by npwalker** [comment]
Looks like @seanmil already took care of this with https://github.com/rodjek/rspec-puppet/commit/d50acf0eccd8996622fb34b86797569e6e077aad but it hasn't made it into an official release yet.

**Comment by jairojunior** [comment]
Same problem here. :+1:

**Comment by rodjek** [comment]
2.6.0 has been pushed to rubygems.org which includes the fix for this issue
