### ISSUE TITLE
Nested keys in structured facts are incorrectly downcased

### ISSUE THREAD

**Issue by seanmil** [rodjek/rspec-puppet#506]
Puppet downcases fact names (see FACT-777) but any keys as part of hashes in structured facts are left as-is and accessible using their original, possibly mixed-case, names. rspec-puppet incorrectly downcases all hash keys in the facts hash, making it impossible to accurately test situations where mixed-case hash keys are expected in facts.

**Comment by seanmil** [comment]
See PR #507 for a patch addressing this.

**Comment by rodjek** [comment]
Closing this as the fix in #507 has been merged.
