### ISSUE TITLE
let(:node) not able to override $fqdn setting

### ISSUE THREAD

**Issue by calmenergy** [rodjek/rspec-puppet#509]
This showed up for me when
- using both rspec-puppet (v2.5.0) and rspec-puppet-facts (v1.7.1)
- using `let(:node)` to specify a node name
- some class in the catalogue being tested references the` $::fqdn` fact

I believe the issue is that line 146 of support.rb contains this:
`facts_val.merge!(munge_facts(facts)) if self.respond_to?(:facts)`
which means that if `fqdn `is already defined in the existing `:facts` hash, we're not going to be able to override it, and we get fqdn as foo.example.com, as defined by rspec-puppet-facts. 

Am I missing something?

**Comment by calmenergy** [comment]
See PR#510, but I don't know what the intended behavior is, here, so not sure I got it right.

**Comment by rodjek** [comment]
Resolved in #513
