### ISSUE TITLE
Unclear about lib/rspec-puppet/coverage.rb

### ISSUE THREAD

**Issue by calmenergy** [rodjek/rspec-puppet#514]
I'm not familiar with good Ruby practices at all, and I'm trying to understand what's going on in coverage.rb. Two things:

1. Lines 20-21: To my untrained eye this looks malformed -- as though` :add`,  `:cover!,` etc. are being delegated to a newly-created-on-demand instance?
```
      def_delegators(:instance, :add, :cover!, :report!,
                     :filters, :add_filter, :add_from_catalog)
```
2. Class `resourceWrapper` (line 188) never declares `@touched`?

**Comment by rodjek** [comment]
> Lines 20-21: To my untrained eye this looks malformed -- as though:add, :cover!, etc. are being delegated to a newly-created-on-demand instance?

That's correct. The created-on-demand instance is being cached in a class instance variable, so you basically get singleton-like behaviour if you use the class methods (`RSpec::Puppet::Coverage.add` etc) but can also have multiple instances of the class as well.

> Class resourceWrapper (line 188) never declares @touched?

Yeah, this makes use of a bit of ruby magic. Referencing an undefined instance variable (`@touched` in this case) will return `nil`. The two bang operators (`!!`) in `RSpec::Puppet::Coverage::ResourceWrapper#touched?` will negate the value of `@touched` twice, converting it to a boolean (`nil` is a falsey value in Ruby, so `!nil` => `true`, `!!nil` => `false`).
