### ISSUE TITLE
(from PUP-6127) clientnoop agent fact not more working starting from Puppet 4.4.1

### ISSUE THREAD

**Issue by MosesMendoza** [rodjek/rspec-puppet#515]
https://tickets.puppetlabs.com/browse/PUP-6127
Hi,
Starting from Puppet 4.4.1, the clientnoop agent fact makes the catalog compilation failing.
I didn't find any trace of deprecation in the Puppet 4.4, 4.3 or even 4.2 changelogs.
The exact message I get from my TravisCI unit tests is:
Evaluation Error: Unknown variable: '::clientnoop'
Rudy

**Comment by DavidS** [comment]
rspec-puppet does not emulate a full execution environment to provide developers with full control to exercise their code.

If you need prefabbed facts, have a look at https://github.com/mcanevet/rspec-puppet-facts , which provides canned full-system facts for easy use in tests.

cc @ryayon

**Comment by DavidS** [comment]
A simple example to add just the `clientnoop` noop flag, put `let(:facts) { { :clientnoop => "true" } }` into your test suite.
