### ISSUE TITLE
NoMethodError: "allow_value" while testing type alias

### ISSUE THREAD

**Issue by poikilotherm** [rodjek/rspec-puppet#518]
Dear valued maintainers,

I'm really stuck at extending my rspec tests for puppet types I defined.

```ruby
$ bundle exec rspec spec/type_aliases/x509pem_spec.rb 

Certmgmt::X509pem
  example at ./spec/type_aliases/x509pem_spec.rb:5 (FAILED - 1)

Failures:

  1) Certmgmt::X509pem 
     Failure/Error: it { is_expected.to allow_value(cert) }
     
     NoMethodError:
       undefined method `allow_value' for #<RSpec::ExampleGroups::CertmgmtX509pem:0x000000034d9178>
     # ./spec/type_aliases/x509pem_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.00203 seconds (files took 0.8873 seconds to load)
1 example, 1 failure
```

Searching through the docs and in the examples provided with rspec-puppet didn't work out. There doesn't seem to be many people having implemented these rather new Puppet feature, so not many examples using rspec testing out there (and hard to find, too).

Running the spec tests of rspec-puppet seems to work:
```ruby
$ bundle exec rspec spec/type_aliases/shape_spec.rb 
Aliases::Shape
[...]
Finished in 0.36029 seconds (files took 0.7605 seconds to load)
6 examples, 0 failures
```

`<begging>` Could you please give me a hint what I'm doing wrong?`</begging>` Willing to expand the docs, too :-)

The failing spec test can be found at:
https://github.com/poikilotherm/puppet-certmgmt/blob/development/spec/type_aliases/x509pem_spec.rb

Travis CI builds showing the error:
https://travis-ci.org/poikilotherm/puppet-certmgmt/builds/234821039

Thanks in advance!
Cheers,
Oliver

**Comment by DavidS** [comment]
Hi Oliver,

support for type aliases was added in https://github.com/rodjek/rspec-puppet/pull/423/commits/30f007d24af5eb6b60ee91ea76db7182d8ec701b (#402) and has not yet been released. You can amend your Gemfile to point to `master`, if you want to try out the new features before they are released.

We'd be very grateful for any feedback on pre-release versions, but be aware that here be dragons.


Cheers, David

**Comment by poikilotherm** [comment]
Oops. Didn't expect that things from August 16 are not released yet... ;-) Thanks for the hint, will test ASAP.

**Comment by DavidS** [comment]
Heh, yeah - I had to look it up myself. There is a new release in the works. RSN!

**Comment by poikilotherm** [comment]
Pointed gem to master:
```
gem 'rspec-puppet',
  :git => 'git://github.com/rodjek/rspec-puppet',
  :branch => 'master'
```

Now things validate properly:
```ruby
$ bundle exec rspec spec/type_aliases/x509pem_spec.rb 

Certmgmt::X509pem
  should match value "-----BEGIN CERTIFICATE-----\nMIIDBDCCAm2gAwIBAgIJAKLH+e+4r20DMA0GCSqGSIb3DQEBBQUAMIGaMRwwGgYD\nVQQDDBNjZXJ0bW5ndC5wdXBwZXQuY29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwK\nV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTESMBAGA1UECgwJQ3JheSBJbmMu\nMRAwDgYDVQQLDAdDaGlwc2V0MSAwHgYJKoZIhvcNAQkBFhFqb2huLmRvZUBjcmF5\nLmNvbTAeFw0xNjA4MTQxMzI3MTlaFw0xNzA4MTQxMzI3MTlaMIGaMRwwGgYDVQQD\nDBNjZXJ0bW5ndC5wdXBwZXQuY29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2Fz\naGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTESMBAGA1UECgwJQ3JheSBJbmMuMRAw\nDgYDVQQLDAdDaGlwc2V0MSAwHgYJKoZIhvcNAQkBFhFqb2huLmRvZUBjcmF5LmNv\nbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA3RifaAX6Vr/MbXWeqGdHG0mi\nx6fsWi63jkvIeAW178RRaVUSEg8up/o+QoNWBQk44GLdimIpORGUNJPHPhD8E/v/\nJwx72D/DZmKHuJGXQF19rfq598Cb2Ey/KngSjeoiiPJNON68qZDjZM793USsF2aG\nPJ2FMrx+IIDNk+w/QucCAwEAAaNQME4wHQYDVR0OBBYEFMlielrD6m0q++AokZjZ\nTgJDVj2vMB8GA1UdIwQYMBaAFMlielrD6m0q++AokZjZTgJDVj2vMAwGA1UdEwQF\nMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAxb3z2JcBY5W1Zxv5iKPub/0EQayF4ZyY\n+rretIjMPLVu2D5+0iAlEbmVU6hV4nTRmRsY2SnLRVWpX+sihwF821p/YuqooXjm\nn1owYvkpRRd4by1wrL4pm8oywiiEwDkL3iULPcWqNeX6RXkWV1uRPES/gIyxj6xL\nkSC+ksQ+5O0=\n-----END CERTIFICATE-----\n"

Finished in 0.13722 seconds (files took 1.07 seconds to load)
1 example, 0 failures
```

What kind of dragons might be hanging around?

**Comment by poikilotherm** [comment]
Just curious: #402 is not added to milestone 2.6.0 - is that as intended?

**Comment by DavidS** [comment]
Thanks for testing!

Re dragons: I feel more pressure to fix bugs in a release, than unexpected features in master :->

Re milestones: those are mostly forward looking, i.e. "what we plan to address", and not so much for "this' what we did." For the latter, commit log is always more accurate.

**Comment by poikilotherm** [comment]
Sry to disturb again... I think I just found an issue.

If I call rspec via `bundle exec rake spec`, the tests for type_aliases are playing nicely. If I try to call them via `bundle exec rspec spec/type_aliases/x509pem.rb`, things go wrong:
```ruby
$ bundle exec rspec spec/type_aliases/x509pem_spec.rb 

Certmgmt::X509pem
  should match value "[...]" (FAILED - 1)

Failures:

  1) Certmgmt::X509pem should match value "[...]"
     Failure/Error: it { is_expected.to allow_value(cert) }
       expected that the type alias would match value "[...]" but it raised the error Evaluation Error: Resource type not found: Certmgmt::X509pem at line 3:13 on node certmgmt::x509pem
     # ./spec/type_aliases/x509pem_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.13831 seconds (files took 1.11 seconds to load)
1 example, 1 failure
```

**Comment by DavidS** [comment]
You still need to have the fixtures installed, to have rspec-puppet find the module:

```
david@davids:~/git/tmp/puppet-certmgmt$ bundle exec rake spec_prep
Cloning into 'spec/fixtures/modules/stdlib'...
remote: Counting objects: 563, done.
remote: Compressing objects: 100% (501/501), done.
remote: Total 563 (delta 160), reused 207 (delta 44), pack-reused 0
Receiving objects: 100% (563/563), 277.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (160/160), done.
david@davids:~/git/tmp/puppet-certmgmt$ bundle exec rspec spec/type_aliases/x509pem_spec.rb 

Certmgmt::X509pem
  should match value "-----BEGIN CERTIFICATE-----\nMIIDBDCCAm2gAwIBAgIJAKLH+e+4r20DMA0GCSqGSIb3DQEBBQUAMIGaMRwwGgYD\nVQQDDBNjZXJ0bW5ndC5wdXBwZXQuY29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwK\nV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTESMBAGA1UECgwJQ3JheSBJbmMu\nMRAwDgYDVQQLDAdDaGlwc2V0MSAwHgYJKoZIhvcNAQkBFhFqb2huLmRvZUBjcmF5\nLmNvbTAeFw0xNjA4MTQxMzI3MTlaFw0xNzA4MTQxMzI3MTlaMIGaMRwwGgYDVQQD\nDBNjZXJ0bW5ndC5wdXBwZXQuY29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2Fz\naGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTESMBAGA1UECgwJQ3JheSBJbmMuMRAw\nDgYDVQQLDAdDaGlwc2V0MSAwHgYJKoZIhvcNAQkBFhFqb2huLmRvZUBjcmF5LmNv\nbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA3RifaAX6Vr/MbXWeqGdHG0mi\nx6fsWi63jkvIeAW178RRaVUSEg8up/o+QoNWBQk44GLdimIpORGUNJPHPhD8E/v/\nJwx72D/DZmKHuJGXQF19rfq598Cb2Ey/KngSjeoiiPJNON68qZDjZM793USsF2aG\nPJ2FMrx+IIDNk+w/QucCAwEAAaNQME4wHQYDVR0OBBYEFMlielrD6m0q++AokZjZ\nTgJDVj2vMB8GA1UdIwQYMBaAFMlielrD6m0q++AokZjZTgJDVj2vMAwGA1UdEwQF\nMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEAxb3z2JcBY5W1Zxv5iKPub/0EQayF4ZyY\n+rretIjMPLVu2D5+0iAlEbmVU6hV4nTRmRsY2SnLRVWpX+sihwF821p/YuqooXjm\nn1owYvkpRRd4by1wrL4pm8oywiiEwDkL3iULPcWqNeX6RXkWV1uRPES/gIyxj6xL\nkSC+ksQ+5O0=\n-----END CERTIFICATE-----\n"

Finished in 0.11438 seconds (files took 0.73951 seconds to load)
1 example, 0 failures

david@davids:~/git/tmp/puppet-certmgmt$ 
```

**Comment by domcleal** [comment]
@poikilotherm what's happening is that the module won't be loaded by Puppet's autoloader if some of its dependencies are missing, so the type alias isn't loaded from the module either.

If you do a checkout of the repo as -is, the module won't be loadable and the test fails as you describe. If you run `rake spec_prep` (which is a pre-req to `rake spec`, which is why the whole run works) then `spec/fixtures/modules` is populated and running the individual spec file should then work.

Note that if you run `rake spec` successfully, the fixtures directory will be cleaned up on completion so you then need to run `rake spec_prep` again. (This is all a feature of puppetlabs_spec_helper.)

**Comment by poikilotherm** [comment]
That's some really usefull info for an RSpec newbie. Shall I add this to the docs and create a PR for it? Maybe this helps some other newbies, too...

**Comment by domcleal** [comment]
Though many people assume it is, it's not actually part of rspec-puppet, so it'd be best to keep/improve the documentation in puppetlabs_spec_helper. Usually rspec-puppet is just configured to point to `spec/fixtures/modules/` and puppetlabs_spec_helper's responsible for populating it.

Perhaps a note in the README about fixtures that points to pl_spec_helper's docs as a common way of populating the directory, and then improve pl_spec_helper's docs to describe how spec_prep/spec/spec_clean work.

**Comment by DavidS** [comment]
@poikilotherm @domcleal these days rspec-puppet and puppet_spec_helper (PSH) have common maintainership, and are almost always used together. So put the docs where they would have helped you the most.

PS: In a not too distant future, I'd like to split up PSH and distribute the parts to better defined components, or to other projects like here.
