### ISSUE TITLE
let(:facts) gives Error: Operator '[]' is not applicable to an Undef Value.

### ISSUE THREAD

**Issue by ardrigh** [rodjek/rspec-puppet#521]
Similar to previous issue https://github.com/rodjek/rspec-puppet/issues/344 I am having issues getting tests to run where $facts are used in the manifest. The values don't appear to be populated so they always fail.

I have setup a new CentOS 7 VM with a number of gems installed to try out rspec tests for some code I am refactoring. I followed some setup guides, and for the most part I have the tests running.

The problem is a fair bit of the code uses the new $facts hash for `os` values and `$trusted` for role information etc. 

I saw in the README that I should be able to define the `os` facts, but I cannot get it to work. I even copied the line directly out of the README file.

I have the following manifest:
```puppet
class profile::virtual::yum_repos {

  $el_version = $facts['os']['release']['major']

  # use el_version for yumrepo wrapper...
}
```

I have a spec file for it:
```puppet
require 'spec_helper'

describe 'profile::virtual::yum_repos', :type => :class do
  let(:facts) { {:os => { :family => 'RedHat', :release => { :major => '7', :minor => '1', :full => '7.1.1503' } } } }
  it { is_expected.to compile }
  it { should contain_class('profile::virtual::yum_repos') }
end
```

When I try to run it, all I get is the same error message:
```
$ rake test

  1) profile::base should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile }
       error during compilation: Evaluation Error: Operator '[]' is not applicable to an Undef Value.

     Failure/Error: require profile::virtual::yum_repos
     
     Puppet::PreformattedError:
       Evaluation Error: Operator '[]' is not applicable to an Undef Value. 
```

I don't know how else to try setting the facts for this to work. I tried different combinations of keys and values in the hash, but nothing worked.

As a workaround, I tried setting the defaults_facts which is also mentioned in the README file. And this works with the tests passing:
```puppet
Spec.configure do |c|
  c.default_facts = {
    :os => {
      :release => { :major => '7', :minor => '3', :full => '7.3.1611' }
    }
  }
end
```
```
profile::virtual::yum_repos
  should compile into a catalogue without dependency cycles
  should contain Class[profile::virtual::yum_repos]
```
However we use a number of different OS's and release versions, so I can't rely on setting just one default.

I am testing this using gems manually installed in the test VM (not using rvm or bundler).

```
*** LOCAL GEMS ***

ast (2.3.0)
bigdecimal (1.2.0)
diff-lcs (1.3)
facter (2.4.6)
fast_gettext (1.1.0)
gettext (3.2.2)
gettext-setup (0.24)
hiera (3.3.1)
io-console (0.4.2)
json (1.7.7)
json_pure (1.8.6)
locale (2.1.2)
metaclass (0.0.4)
metadata-json-lint (1.1.0)
mocha (1.2.1)
parallel (1.11.2)
parser (2.4.0.0)
powerpack (0.1.1)
psych (2.0.0)
puppet (4.10.1)
puppet-lint (2.2.1)
puppet-syntax (2.4.0)
puppetlabs_spec_helper (2.1.2)
rainbow (2.2.2)
rake (12.0.0)
rdoc (4.0.0)
rspec (3.6.0)
rspec-core (3.6.0)
rspec-expectations (3.6.0)
rspec-mocks (3.6.0)
rspec-puppet (2.5.0)
rspec-support (3.6.0)
rubocop (0.49.0)
ruby-progressbar (1.8.1)
semantic_puppet (1.0.0)
spdx-licenses (1.1.0)
text (1.3.1)
unicode-display_width (1.2.1)
```

Is there anything else I can provide to help work out how to fix this?

**Comment by domcleal** [comment]
I'm unable to reproduce this, would you be able to publish a repo or gist with the full reproducer?

**Comment by ardrigh** [comment]
I will run through the setup in another new VM and see if it still happens. Then I will be provide steps for what I've done.

**Comment by ardrigh** [comment]
I think this error is being caused by a hiera_hash call in our code and the line information might be misleading. I need to do more work on test setup and making the hiera lookups work correctly.

So will close this issue.
