### ISSUE TITLE
(MODULES-4287) Platform pretending not handling Pathname#absolute?

### ISSUE THREAD

**Issue by rodjek** [rodjek/rspec-puppet#522]
vcsrepo uses [Pathname#absolute?](https://github.com/puppetlabs/puppetlabs-vcsrepo/blob/4dbc439e02a8dcdb44308e25aa4617d35afd77b0/lib/puppet/type/vcsrepo.rb#L161-L162) when validating the path parameter. This is not currently being handled by how we're pretending to be different platforms, but as this is part of Ruby stdlib we'll need to.

/cc @ipcrm

**Comment by DavidS** [comment]
Should we be pushing people towards using `Puppet::Util.absolute_path?` instead? Otherwise this might evolve into a drawn out game of whack-a-mole.

**Comment by seanmil** [comment]
My 2¢ from the sidelines: If there is a utility function in Puppet which is part of a public and stable API that is preferred for any of these tasks I'd rather use it as there is very likely a problem there that someone else has already solved for me. However, historically the Puppet code base wasn't well documented and it wasn't clear what functions should be considered stable/public and so people like me didn't go looking for them. I think noting these functions in the rspec-puppet README (or noting a link to the spots where these functions can be found) to raise awareness of them is a win/win both from a rspec-puppet standpoint and from a module developer standpoint. Certainly seems better than a never ending game of whack-a-mole...

**Comment by DavidS** [comment]
I have been made aware of https://github.com/puppetlabs/puppet/blob/master/lib/puppet/file_system.rb which is puppet's preferred internal filesystem abstraction. Obviously usage of this is not as widespread as we might want it to be.

**Comment by rodjek** [comment]
"fixed" in #528
