### ISSUE TITLE
Capital letters in facts seems to not be supported

### ISSUE THREAD

**Issue by zbikmarc** [rodjek/rspec-puppet#525]
I was trying to do tests for my manifest where I am getting data from Google Cloud Platform facts and one of facts is `projectId`. Imagine my surprise when I found out that problem with passing tests where caused by this capital `I` letter. 

```
$ facter gce.project
{
  numericProjectId => SANITIZED_INT,
  projectId => "SANTIZED_STRING"
}
```

I tried to mock projectId like this:
```
let(:facts) {{
    :gce  => { :project => { :projectId => 'project'}, :instance => { :zone => 'zone' } },
}}
```
However it fails to find such key. Because I was expecting problem with structured fact I even tried to do this:
```
let(:facts) {{
     :projectId => 'project'
}}
```
and then use (just for testing) `$facts['projectId']` in manifest. Same result, can not find key and returns `Undef`. 
However When I changed it to:
```
let(:facts) {{
    :projectid => 'project'
}}
``` 
It worked flawlessly, but it does not help me at all because in GCE this attribute in structured fact has CamelCase name.

**Comment by seanmil** [comment]
Did you test against the master branch? I believe this should have been resolved with https://github.com/rodjek/rspec-puppet/pull/507

**Comment by zbikmarc** [comment]
Tried building from master and seems that #507 fixes this problem.

When new version of gem might be expected?
