### ISSUE TITLE
Link teardown after suite incompatible with parallel_tests

### ISSUE THREAD

**Issue by domcleal** [rodjek/rspec-puppet#526]
cef39574 introduces an incompatibility with the parallel_tests gem (used/recommended by puppetlabs_spec_helper) as it removes the module symlink after every suite has completed.

When using parallel_tests, the suite is executed by multiple processes and the teardown executing at the end of each suite can cause the symlink to be removed while another process is running a test. This causes intermittent failures finding resources within the module under test (e.g. https://travis-ci.org/puppet-testing/puppetlabs-postgresql/jobs/240309046).

Could the teardown simply be reverted, leaving whatever symlink was created in place?

**Comment by DavidS** [comment]
... or move the symlink create/remove to the tests using them. Will have to have a think about that.

**Comment by domcleal** [comment]
Whether it's a suite or individual example before/after, it'd still cause errors between multiple processes as they're modifying the same link.

If cleaning up the link's important then it'd perhaps be better to copy/recreate the whole fixtures directory in a temporary dir, but that may create a new class of issues.

**Comment by rodjek** [comment]
Hmmm, damn, I didn't consider the parallel_spec case. I'll pull the link removal code.
