### ISSUE TITLE
param keys are not converted to strings when subkeys are symbols

### ISSUE THREAD

**Issue by logicminds** [rodjek/rspec-puppet#530]
This is more of a UI bug but it can be confusing to the user as to which hash syntax to use when using the `let(:params)` block.  Should they use symbols or not symbols?  Personally, I think we should just convert all symbols  to strings for the user, before passing to puppet.  Since it is easier to type `key2: 'value2'` than `:key2 => 'value2'` I would expect this error to pop up often since humans take the path of least resistance. 

What works:

```ruby
let(:params) do
{
  key1: 'value1', 
  :key2 => 'value2'
}
end

let(:params) do
{
  key1: {
    'option' => 'value1'
    'option2' => {
       'sub_option1' => 'value1'
    }
  },
  :key2 => value2
}
end
```

What doesn't work, and results in error message from puppet complaining about ':' not being valid.

```ruby
let(:params) do
{
  key1: {
    option1: value1
    option2: {
       sub_option1: value1
    }
  },
  :key2 => value2
}
end
```

**Comment by rodjek** [comment]
The fix for this issue is already in master (#441), there just hasn't been a release for a while, but it will be part of tomorrow's release.
