### ISSUE TITLE
Time For a New Release?

### ISSUE THREAD

**Issue by seanmalloy** [rodjek/rspec-puppet#532]
Looks like it has been a while since the last release. There are many fixes on the master branch since the 2.5.0 release, and it would be nice if these were available in a release.

Any plans on doing a release soon?

**Comment by seanmalloy** [comment]
I see there are four open issues for the 2.6 milestone.

![image](https://user-images.githubusercontent.com/685221/27578269-410bccf0-5ae9-11e7-9a94-7a0491815153.png)

**Comment by rodjek** [comment]
Sorry for the delay, 2.6.0 will be out tomorrow (just finishing it off now)

**Comment by rodjek** [comment]
2.6.0 has just been pushed up to rubygems.org
