### ISSUE TITLE
"Could not parse for environment rp_env: Illegal variable name" error with 2.6.0

### ISSUE THREAD

**Issue by vinzent** [rodjek/rspec-puppet#536]
The following block started to fail with 2.6.0 (worked fine upto version 2.5.0):

```
context 'with resource titled /opt/$HOME/some weird dir/' do
        let(:title) { '/opt/$HOME/some weird dir/' }

        context 'with defaults' do
          it { is_expected.to contain_exec('selinux::exec_restorecon /opt/$HOME/some weird dir/').with(command: "restorecon -R '/opt/$HOME/some weird dir/'", refreshonly: true) }
        end
      end
```
(complete file: https://github.com/voxpupuli/puppet-selinux/blob/master/spec/defines/selinux_exec_restorecon_spec.rb#L33-L39)

prouced output:

```
    Puppet::ParseErrorWithIssue:

       Could not parse for environment rp_env: Illegal variable name, The given name 'HOME' does not conform to the naming rule /^((::)?[a-z]\w*)*((::)?[a-z_]\w*)$/ at line 2:34 on node testing-docker-3937aaca-76c2-472a-aa38-74d9e6f3f336.ec2.internal

```

I tried to escape every $HOME with \ - but the error remains. 

Example fail on Travis: https://travis-ci.org/voxpupuli/puppet-selinux/jobs/242614152
related issue: https://github.com/voxpupuli/puppet-selinux/issues/225

**Comment by rodjek** [comment]
Hmmm, interesting. Confirmed that I can reproduce it locally, I'll let you know when I've tracked it down.

**Comment by rodjek** [comment]
https://github.com/rodjek/rspec-puppet/commit/1b7869c is the cause, I'll fix and push out a new release shortly

**Comment by vinzent** [comment]
@rodjek thanks for tracking this down!

**Comment by rodjek** [comment]
2.6.1 has been pushed to rubygems with the fix for this issue
