### ISSUE TITLE
Support for Puppet 3.0

### ISSUE THREAD

**Issue by antonlindstrom** [rodjek/rspec-puppet#54]
When running tests with rspec-puppet against Puppet 3.0 the run fails with the message:

```
Error converting value for param 'statedir': Could not find value for $vardir on node example.local
```

For example, I ran the test [powerdns__package_spec.rb](https://github.com/antonlindstrom/puppet-powerdns/blob/master/spec/classes/powerdns__package_spec.rb) and got the following output:

```
1) powerdns::package 
   Failure/Error: it { should contain_package('pdns-server').with_ensure('present') }
   Puppet::Error:
     Error converting value for param 'statedir': Could not find value for $vardir on node example.local
   # ./spec/classes/powerdns__package_spec.rb:5:in `block (2 levels) in <top (required)>'
```

This may be related fixes: [puppet issue 13429](http://projects.puppetlabs.com/issues/13429), [mcollective-plugin PR 38](https://github.com/puppetlabs/mcollective-plugins/pull/38). 

Thanks!

**Comment by logicminds** [comment]
I know this issue is closed but have come across this issue with other code bases and found this issue to be helpful.  The better fix is to do the following:

```
begin
    Puppet.initialize_settings
 rescue
        # do nothing otherwise calling init twice raises an error
 end

```
