### ISSUE TITLE
Broken package provider setting when running under macOS

### ISSUE THREAD

**Issue by pegasd** [rodjek/rspec-puppet#554]
When trying to launch spec tests for Ubuntu-specific modules under macOS, I get the following error:

```
error during compilation: Parameter ensure failed on Package[nasty_package]: Provider pip3 must have features 'purgeable' to set 'ensure' to 'purged' at [ ... long pathname snipped ... ]
```

This happens for all packages that have `ensure => purged` set.

Under Ubuntu, tests pass as expected.

Note that the test is wrapped inside a `on_supported_os` iterator and all the OS-specific facts are set, so I'd assume the default provider should be set to `apt`, which does have the `purgeable` attribute.

I've created a sample module [here](https://github.com/pegasd/puppet-my_module) to illustrate the issue.

**Comment by rodjek** [comment]
2.6.4 has been pushed to rubygems with the fix for this issue
