### ISSUE TITLE
No longer able to explicitly set hostname, fqdn or domain facts

### ISSUE THREAD

**Issue by seanmil** [rodjek/rspec-puppet#565]
With the changes as a result of the report starting in, I think, #509 it is no longer possible to set a node name independent from the system's facter FQDN. This is a breaking change from the prior release and has broken a number of our test cases.

In environments where the node (certificate) name of a system is independent from its FQDN this introduces significant testing issues as there is no longer any way to set the fqdn, hostname, or domain facts (either top-level or in the networking hash) to the expected/required values for testing.

Previously in facts_hash https://github.com/rodjek/rspec-puppet/blob/c6639523b7989fd1c935905f0348f4267d288442/lib/rspec-puppet/support.rb#L113 any user-specified facts were merged in last.

**Comment by seanmil** [comment]
In order to stick with semver, I think any solution will require letting people override the facts via setting them in the facts hash.

A way to support this going forward might be to let people do something like: `let(:fqdn) { 'test.example.com' }` to set the value that the `fqdn`, `domain`, and `hostname` facts derive from, and if no `let(:fqdn)` is declared then default to the value of `:node`.

**Comment by seanmil** [comment]
I've just pushed a fix which I believe addresses both the original concerns/goals as well as provides compatibility with user-supplied fact overrides.

**Comment by rodjek** [comment]
Yeah, I've never actually seen a real world use of nodename != fqdn, it's always been a theoretical case until now! :)

Given that, I don't think it's possible to satisfy all the conditions without a breaking change. I think I'll have to revert the original change and restore the 2.5.x behavior. I like the idea of using `let(:fqdn)`, but that's still a breaking behavior change. As it would require a major version bump, I'd also like to rename `let(:node)` to something like `let(:certname)` to make the difference between the two obvious.

**Comment by seanmil** [comment]
Having nodename != fqdn is a requirement in our environment for a couple of reasons. It does make some things a bit more complicated in Puppet-land, given the general presumption that they are equal, but it is quite doable.

Did you have a chance to look at the PR I put up? Any reason to think it wouldn't work to achieve the original intention that prompted the change while still providing backwards compatibility?

**Comment by rodjek** [comment]
Yeah, the change that was introduced in 2.6.0 to override the fqdn based facts was to account for the rspec-puppet-facts workflow. rspec-puppet-facts gives you a hash of pre-generated facts for a particular OS, which includes things like `fqdn`, `hostname`, `domain` etc and we need to be able to override those values if the user specifies a node name in their spec.

That desired behaviour is pretty much the exact opposite of what you need, if i'm reading this correctly. We could perhaps add a configuration option to disable/enable the nodename overwriting facts to avoid having to back out the change while still providing the work flow you need... A bit of a stopgap solution until I have time to work on 3.0.0

**Comment by rodjek** [comment]
@seanmil I've pushed 2.6.5 to rubygems with a solution for this, you'll just need to set `derive_node_facts_from_nodename = false` in your `RSpec.configure` block.
