### ISSUE TITLE
2.6.4 breaks testing certain confined type parameters

### ISSUE THREAD

**Issue by tylerjl** [rodjek/rspec-puppet#567]
I searched around but couldn't find any existing issues/PRs for this, and I don't 100% understand the diff I looked at between 2.6.4 and 2.6.3, so apologies if this is somewhat off the mark.

I test a `validate` block for a certain defined type in `puppet-elasticsearch` that stopped working as expected upon upgrading to 2.6.4. Here's the setup:

```
$ git clone git@github.com:tylerjl/puppet-elasticsearch
$ git checkout 3166cd0b22c232fbcf6be171f05d69d70b5d3fb1
$ bundle install
```

This revision is on 2.6.3 of rspec-puppet. The test in question passes:

```
$ bundle exec rspec spec/unit/type/elasticsearch_user_spec.rb
........

Finished in 0.03632 seconds (files took 2.98 seconds to load)
8 examples, 0 failures
```

Switch to the newer version, and watch the test fail without seeing the exception raised:

```
$ sed -i 's/2\.6\.3/2.6.4/' Gemfile
$ bundle update
$ bundle exec rspec spec/unit/type/elasticsearch_user_spec.rb
.......F

Failures:

  1) Puppet::Type::Elasticsearch_user when validating values password should reject short passwords
     Failure/Error:
       expect { described_class.new(
         :name => resource_name,
         :password => 'foo',
       ) }.to raise_error(Puppet::Error, /must be at least/)

       expected Puppet::Error with message matching /must be at least/ but nothing was raised
     # ./spec/unit/type/elasticsearch_user_spec.rb:53:in `block (4 levels) in <top (required)>'

Finished in 0.04737 seconds (files took 2.66 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/unit/type/elasticsearch_user_spec.rb:52 # Puppet::Type::Elasticsearch_user when validating values password should reject short passwords
```

I don't know what changes to confinement happened that changed, but I _suspect_ that it may be related to the fact that [the parameter is confined by a feature](https://github.com/elastic/puppet-elasticsearch/blob/a3f69ccaa4fcb2398c243e1937155186905f1bcb/lib/puppet/type/elasticsearch_user.rb#L19)?

**Comment by rodjek** [comment]
rspec-puppet has to monkey patch some significant bits of Puppet in order to do cross-platform tests. I recommend having a separate spec_helper for your catalogue specs that isn't used for your ruby unit specs (like you have a separate spec_helper for your acceptance tests)

**Comment by tylerjl** [comment]
Thanks @rodjek - I think I've been conflating the dependencies needed to test simple ruby classes (i.e. types, providers) as opposed to classes/defined types that are explicitly calling out to methods provided by puppet-rspect. Simply avoiding `require 'rspec-puppet'` in the associated spec helper solves this case.

I appreciate the support!
