### ISSUE TITLE
contain_package and resource aliases

### ISSUE THREAD

**Issue by eputnam** [rodjek/rspec-puppet#568]
I'm having a problem with the `contain_package` matcher.
[The `it` block](https://github.com/puppetlabs/puppetlabs-haproxy/blob/master/spec/defines/instance_spec.rb#L240-L242):
```ruby
it 'should not install the haproxy package' do
  subject.should_not contain_package('haproxy')
end
```
In the [haproxy::install](https://github.com/puppetlabs/puppetlabs-haproxy/blob/master/manifests/install.pp) class, whatever the package name is, the package resource is always given the alias "haproxy". When prying into the test, i found that the catalogue contains these resources:
```
[2] pry(#<Puppet::Resource::Catalog>):1> @resources
=> [["Stage", "main"],
 ["Class", "Settings"],
 ["Class", "main"],
 ["Class", "Haproxy::Params"],
 ["Haproxy::Instance", "group1"],
 ["Haproxy::Config", "group1"],
 ["Haproxy::Install", "group1"],
 ["Haproxy::Service", "group1"],
 ["Anchor", "group1::haproxy::begin"],
 ["Anchor", "group1::haproxy::end"],
 ["File", "/etc/haproxy-group1"],
 ["Concat", "/etc/haproxy-group1/haproxy-group1.cfg"],
 ["Concat::Fragment", "haproxy-group1-00-header"],
 ["Concat::Fragment", "haproxy-group1-haproxy-base"],
 ["File", "/var/lib/haproxy"],
 ["Package", "customhaproxy"],
 ["File", "/etc/default/haproxy-group1"],
 ["Service", "haproxy-group1"],
 ["Concat_file", "/etc/haproxy-group1/haproxy-group1.cfg"],
 ["Concat_fragment", "haproxy-group1-00-header"],
 ["Concat_fragment", "haproxy-group1-haproxy-base"]]
```
As you can see, there is no Package['haproxy']. However, there is an alias:
```
[4] pry(#<Puppet::Resource::Catalog>):1> @aliases
=> {"Package[customhaproxy]"=>[["Package", "haproxy"]]}
```
When I comment out the alias in install.pp, the tests pass. I also found that this does not happen with Puppet 4.10.4 but it does happen with Puppet 5.0.0. 

Further, when this commit is reverted in Puppet 5.0.0, the tests pass: https://github.com/puppetlabs/puppet/commit/3aa97102de760b10b9afd8a74bc5b4cfa05ef31a

Any thoughts? Is this an rspec-puppet issue?

**Comment by rodjek** [comment]
This is probably something that you'll need to change your tests for. It didn't cause a problem in the past because those aliases weren't explicitly created, but given that `Package[customhaproxy]` is aliased to `Package[haproxy]`, then `contain_package('haproxy')` should match that resource and I'm leaning towards this behaviour being correct.

```
[3] pry(#<Puppet::Resource::Catalog>):1> resource('Package', 'haproxy')
=> Package[customhaproxy]{:name=>"customhaproxy", :ensure=>"present", :alias=>"haproxy"}
```

It makes sense to me that you should be able to refer to this as `Package[haproxy]` or `Package[customhaproxy]` in the tests, just like you would in the manifest itself, and in that case you shouldn't be expecting `Package[haproxy]` to not be in the catalogue.

**Comment by eputnam** [comment]
Yeah, that makes sense to me. Regardless, if there's going to be an alias, we need to find another way to test. Thanks @rodjek !
