### ISSUE TITLE
trusted_facts does not allow symbol keys

### ISSUE THREAD

**Issue by ardrigh** [rodjek/rspec-puppet#572]
I am currently trying to implement tests for a specific role based on `$trusted` extension [pp_role]
(https://docs.puppet.com/puppet/5.0/ssl_attributes_extensions.html#puppet-specific-registered-ids).

Getting this error in TravisCI:
```shell
     Puppet::Error:
       Unsupported data type: 'Symbol' on node testing-docker-de3089bf-4888-46b9-9847-9b47c5543b92.ec2.internal
```

**Edit:** Changing this line:
```ruby
let(:trusted_facts) do
  {
    :pp_role => 'freeipa_server'
  }
end
```

To this line:
```ruby
let(:trusted_facts) do
  {
    'pp_role' => 'freeipa_server'
  }
end
```

Now passes. Which matches the documentation after I read it again :man_facepalming: 

Is it possible to support using `:pp_role` for `trusted_facts` like the other hash values do?
e.g.
```ruby
let(:facts) do
  {
    :os => {
      :architecture => 'x86_64',
      :name         => 'CentOS',
      :famiy        => 'RedHat',
      :release      => {
        :major => '7',
        :minor => '3',
        :full  => '7.3.1611',
      }
    },
    :networking => {
      :fqdn     => 'client.example.com',
      :hostname => 'client',
      :domain   => 'example.com',
    }
  }
end
```

**Comment by rodjek** [comment]
Thanks @ardrigh, 2.6.5 has been pushed to rubygems with the fix for this

**Comment by ardrigh** [comment]
That's amazing, thanks for the update :100: :1st_place_medal:
