### ISSUE TITLE
document partially overriding params and facts in inner scopes

### ISSUE THREAD

**Issue by DavidS** [rodjek/rspec-puppet#575]
a nice pattern is to partially override facts and params by using
```ruby
let(:params) do
  super().merge({
    param: 'value'
  })
end
```

this should be mentioned on e.g. http://rspec-puppet.com/documentation/classes/

[updated to add the required `()` for super, and fix the call chain]

**Comment by rodjek** [comment]
What, I move the docs into the master branch so that it's nice and easy to update them and no PR? You slacker, David 😜

**Comment by DavidS** [comment]
... and there I wanted to leave some work for you. How ungrateful! :-D
