### ISSUE TITLE
Unable to test Windows specs on a Windows computer

### ISSUE THREAD

**Issue by glennsarti** [rodjek/rspec-puppet#577]
rspec-puppet version 2.6.4
Probably affects 2.6.0 and above though

Repro:
Windows 10
Ruby 2.4
* Clone puppetlabs-chocolatey module (https://github.com/puppetlabs/puppetlabs-chocolatey)
* bundle install
* bundle exec rake spec
* specs fail on 12 unit tests

Delete/rename all tests in spec/classes folder
* bundle exec rake spec
* specs all pass

Reason:
For some unknown reason in https://github.com/puppetlabs/puppetlabs-chocolatey/blob/master/lib/puppet_x/chocolatey/chocolatey_common.rb#L20 the `Puppet::Util::Platform.windows?` is evaluating as false in the failed tests.

Even though I'm doing windows tests on a windows computer, and I have not instructed rspec-puppet to impersonate a POSIX system.

I believe I have narrowed down the issue to the commit https://github.com/rodjek/rspec-puppet/commit/05d4f74402866f2d1668145344771aad064dd2ee

In this line - https://github.com/rodjek/rspec-puppet/blob/master/lib/rspec-puppet/support.rb#L370 if you don't specify an `operatingsystem` fact in your facts list then it assumes your computer is POSIX.

This assumption is wrong.  If I don't specify which operating system I want, then surely it should not be pretending at all.

I confirmed a workaround by adding `operatingsystem => 'windows'` at the top `facts` hash for all tests in the `spec/classes` directory, but this is not satisfactory for modules that are primarily created and tested on Windows.

---

Also this pretending ability is bleeding out to other other tests.  In my case, testing for files in `classes` should not be adversely affecting tests in the `unit` folder.

**Comment by Iristyle** [comment]
@glennsarti can we pin back to `< 2.6.0` like the other Windows modules? See also #498 / https://tickets.puppetlabs.com/browse/SDK-334

**Comment by glennsarti** [comment]
I thought about that.  I decided to go the workaround route instead of pinning due to how simple the workaround was and the module would still continue to take in fixes from rspec-puppet.

**Comment by glennsarti** [comment]
If we find more cases where the bleeding is an issue (instead of just adding an `operatingsystem` fact), then we would probably need to consider pinning then.

**Comment by rodjek** [comment]
I've got a branch going locally that contains the monkey patching so that it'll only take effect if running from an rspec-puppet example group, which should clear up part of this issue. I need to run it through a bunch more testing tomorrow, but I'm hoping to have it out in a new release soon.

**Comment by rodjek** [comment]
2.6.5 has been pushed to rubygems which should fix this issue
