### ISSUE TITLE
Multiple puppet versions

### ISSUE THREAD

**Issue by gerases** [rodjek/rspec-puppet#580]
Hi,

The systemwide version of puppet on my system is under /usr/share and that's version 3.5. I want to test 4.0 code. I downloaded a 4.0 puppet gem and I can't figure out how to make rspec-puppet use puppet version 4.0.

What's the best way to do this?

Thanks!

**Comment by rodjek** [comment]
Hi @garases,

The most common pattern is to use [Bundler](https://bundler.io) to manage the gems in your module or control repo, with something like the following in your `Gemfile`:

```
source 'https://rubygems.org'

gem 'rspec-puppet', '~> 2.6.0'
gem 'puppet', ENV.fetch('PUPPET_GEM_VERSION', '~> 4.0')
```

By default, that'll tell bundler to use the latest 4.x Puppet release when you run `bundle install`, but also gives you the option to specify the puppet version in the `PUPPET_GEM_VERSION` environment variable.

After you've run `bundle install`, you can then run the tests through bundler by prefixing your normal command with `bundler exec` and it will then use the version of Puppet specified in your Gemfile (e.g. `bundle exec rake spec` or `bundle exec rspec`).

Hope that helps!

**Comment by gerases** [comment]
This is a great tip. Thank you.

The only problem is that I'm getting this error:

     Failure/Error: it { is_expected.to compile }
       error during compilation: uninitialized constant RGen::ECore::ELong on node MY_NODE_NAME

I'm running it like so:

    bundle exec rspec PATH/spec/classes/my_module.pp

Any ideas? Thank you.

**Comment by rodjek** [comment]
What's the output of `bundle show`?

**Comment by gerases** [comment]
Hi @rodjek,

Here's the output of `bundle show`:

> Gems included by the bundle:
>   * bundler (1.15.3)
>   * diff-lcs (1.3)
>   * facter (2.5.0)
>   * fast_gettext (1.1.0)
>   * gettext (3.2.3)
>   * gettext-setup (0.26)
>   * hiera (3.4.0)
>   * json_pure (1.8.6)
>   * locale (2.1.2)
>   * puppet (4.10.5)
>   * rspec (3.6.0)
>   * rspec-core (3.6.0)
>   * rspec-expectations (3.6.0)
>   * rspec-mocks (3.6.0)
>   * rspec-puppet (2.6.4)
>   * rspec-support (3.6.0)
>   * text (1.3.1)

**Comment by gerases** [comment]
After I modify the LOAD_PATH to exclude the system location, it starts working. I modified the actual `rspec` script that `gem` placed into my bin dir.

I did this:

```
delete_at_indices = []
$LOAD_PATH.each_with_index do |path, index|
  delete_at_indices.push(index) if path =~ /vendor/
end

delete_at_indices.each do |index|
  $LOAD_PATH.delete_at(index)
end
```

Is there a way to achieve the same using a more standard method?

**Comment by rodjek** [comment]
If you run `bundle install --disable-shared-gems`, it should prevent any system installed gems from polluting your bundler environment.

**Comment by gerases** [comment]
Thank you for your reply, Tim.

From the bundler changelog:

> ## 1.0.0.rc.2 (July 29, 2010)
> ...
>   completely remove `--disable-shared-gems`. If you install to
>     system, you will not be isolated, while if you install to
>     another path, you will be isolated from gems installed to
>     the system. This was mostly an internal option whose naming
>     and semantics were extremely confusing.
> ...

So, I don't have that option seems like. I didn't install to system, but something else had installed to system. So, I guess it's not possible now unless with the solution I posted? It might be a question for the bundler developers at this point.

**Comment by gerases** [comment]
The advice from the `bundle` team is to use the `--path` option to bundle.

Can I ask you another question please:

If a file resource looks like this:

```
file {'/etc/some_file':
  content = file('ABSOLUTE_PATH_TO_FILE_ON_PUPPET_MASTER')
}
```

what's the best way to test it?

**Comment by gerases** [comment]
Hi @rodjek 

Sorry to bug, but another question.

When running `rspec-puppet-init` from within a brand new module without the `spec` directory, I get:

```Errno::ENOENT: No such file or directory - spec/fixtures/manifests/site.pp
  /usr/share/ruby/fileutils.rb:1145:in `initialize'
  /usr/share/ruby/fileutils.rb:1145:in `open'
  /usr/share/ruby/fileutils.rb:1145:in `rescue in block in touch'
  /usr/share/ruby/fileutils.rb:1141:in `block in touch'
  /usr/share/ruby/fileutils.rb:1139:in `each'
  /usr/share/ruby/fileutils.rb:1139:in `touch'
  /home/sgerasenko/.bundle/ruby/gems/rspec-puppet-2.6.4/lib/rspec-puppet/setup.rb:124:in `safe_touch'
  /home/sgerasenko/.bundle/ruby/gems/rspec-puppet-2.6.4/lib/rspec-puppet/setup.rb:16:in `run'
  /home/sgerasenko/.bundle/ruby/gems/rspec-puppet-2.6.4/bin/rspec-puppet-init:20:in `<top (required)>'
  /home/sgerasenko/.bundle/ruby/bin/rspec-puppet-init:23:in `load'
  /home/sgerasenko/.bundle/ruby/bin/rspec-puppet-init:23:in `<top (required)>'```

I think that's because `FileUtils.touch` won't create intermediate directories when trying to make `spec/fixtures/manifests/site.pp`.

When I do create all the necessary directories, I get:

```Unable to setup rspec-puppet automatically in a control repo
 + spec/fixtures/manifests/site.pp
 + spec/spec_helper.rb
 + Rakefile```

What does that error mean?
