### ISSUE TITLE
Testing file resource when it refers to a file on puppet master

### ISSUE THREAD

**Issue by gerases** [rodjek/rspec-puppet#588]
Hi,

I've run into a situation where the `file` resource uses the `file` function to refer to the content stored on the puppet master like so:

```
  file { SOME_NAME:
    content => file(PATH_TO_FILE_ON_MASTER),
    ...
  }
```

That prevents the catalog compilation during the testing. Is there a way around this?

Thanks!

**Comment by rodjek** [comment]
If you're passing an absolute path to `file()`, you don't have many options.

You could stub out the function entirely by redefining it:
```
before do
  Puppet::Parser::Functions.newfunction(:file, :arity => -2, :type => :rvalue) do |vals|
    "the contents of the file for testing purposes"
  end
end
```

You could also mock the internals of the function, using your mocking framework of choice. For example, if using rspec-mocks:
```
before do
  allow(Puppet::Parser::Files).to receive(:find_file).with(any_args).and_call_original
  allow(Puppet::Parser::Files).to receive(:find_file).with(PATH_TO_FILE_ON_MASTER, anything).and_return(PATH_TO_FILE_ON_MASTER)
  allow(Puppet::Filesystem).to receive(:exist?).with(any_args).and_call_original
  allow(Puppet::Filesystem).to receive(:exist?).with(PATH_TO_FILE_ON_MASTER).and_return(true)
  allow(Puppet::Filesystem).to receive(:read_preserve_line_endings).with(any_args).and_call_original
  allow(Puppet::Filesystem).to receive(:read_preserve_line_endings).with(PATH_TO_FILE_ON_MASTER).and_return("the contents of the file for testing purposes")
end
```
This is potentially a more fragile solution as the behaviour of the `file` function may change between Puppet releases and may require adjusting the mocks.

Refactoring your manifest to not depend on the existence of a file on the master would be the best option.

**Comment by gerases** [comment]
That's awesome, Tim. At least I have a few options now. Thanks a lot!!!
