### ISSUE TITLE
rspec-puppet-init

### ISSUE THREAD

**Issue by gerases** [rodjek/rspec-puppet#594]
Hi @rodjek

Sorry to bug, but another question.

When running rspec-puppet-init from within a brand new module without the spec directory, I get:

```
  Unable to setup rspec-puppet automatically in a control repo
 /usr/share/ruby/fileutils.rb:1145:in `initialize': No such file or directory - spec/fixtures/manifests/site.pp (Errno::ENOENT)
        from /usr/share/ruby/fileutils.rb:1145:in `open'
        from /usr/share/ruby/fileutils.rb:1145:in `rescue in block in touch'
        from /usr/share/ruby/fileutils.rb:1141:in `block in touch'
        from /usr/share/ruby/fileutils.rb:1139:in `each'
        from /usr/share/ruby/fileutils.rb:1139:in `touch'
        from /home/sgerasenko/.bundle/ruby/gems/rspec-puppet-2.6.7/lib/rspec-puppet/setup.rb:124:in `safe_touch'
        from /home/sgerasenko/.bundle/ruby/gems/rspec-puppet-2.6.7/lib/rspec-puppet/setup.rb:16:in `run'
        from /home/sgerasenko/.bundle/ruby/gems/rspec-puppet-2.6.7/bin/rspec-puppet-init:20:in `<top (required)>'
        from /home/sgerasenko/bin/rspec-puppet-init:17:in `load'
        from /home/sgerasenko/bin/rspec-puppet-init:17:in `<main>'
```

Thank you!
I think that's because FileUtils.touch won't create intermediate directories when trying to make spec/fixtures/manifests/site.pp.

When I do create all the necessary directories, I get:

```
Unable to setup rspec-puppet automatically in a control repo
 + spec/fixtures/manifests/site.pp
 + spec/spec_helper.rb
 + Rakefile
```

What does that error about "control repo" mean?

**Comment by rodjek** [comment]
Control repo refers to the [common pattern](https://docs.puppet.com/pe/latest/cmgmt_control_repo.html) of having a version controlled repository that is deployed to your puppet master. This is very different to a module repository and unique to each user/company, so rspec-puppet-init doesn't attempt to do an automatic setup.

rspec-puppet-init determines if the current working directory is a module or not by looking for a `metadata.json` file. Your new module didn't have one, so it assumed that it was running inside a control repo. I'll update the error message to make it more clear what's happening and prevent it from trying to create the files.
