### ISSUE TITLE
Exec's cwd attribute throwing fully qualified path error on windows

### ISSUE THREAD

**Issue by TraGicCode** [rodjek/rspec-puppet#602]
When running the spec tests for the https://github.com/voxpupuli/puppet-rabbitmq module on linux all pass and run perfect.  

When running the spec tests on windows the following error is thrown

```
32) rabbitmq on ubuntu-14.04-x86_64 should compile into a catalogue without dependency cycles
      Failure/Error: it { is_expected.to compile.with_all_deps }
        error during compilation: Parameter cwd failed on Exec[/var/lib/rabbitmq/rabbitmqadmin]: cwd must be a fully qualified path at C:/Users/tragiccode/Source/GitHub/puppet-rabbitmq/spec/fixtures/modules/staging/manifests/file.pp:126
      # ./spec/classes/rabbitmq_spec.rb:24:in `block (4 levels) in <top (required)>'
```

How to reproduce:
1.) Ensure you're on a windows machine
2.) Clone the following repo https://github.com/voxpupuli/puppet-rabbitmq
3.) in the root of the repo run the following
```
bundle install --path .bundle
bundle exec rake spec
```

You should see the above error along with others

**Comment by DavidS** [comment]
I've tried to reproduce this, but with a new module, and these two files:

```puppet
# init.pp
class foo {
  if $::facts['osfamily'] == 'windows' {
	exec { 'C:\\bin\\foo': cwd => 'C:\\foo' }
  } else {
	exec { '/bin/foo': cwd => '/foo' }
  }
}
```
```ruby
# spec/classes/foo_spec.rb
require 'spec_helper'

describe 'foo' do
  on_supported_os.each do |os, os_facts|
    context "on #{os}" do
      let(:facts) { os_facts }

      it { is_expected.to compile.with_all_deps }
      it('on windows', if: os_facts[:osfamily] == 'windows') { is_expected.to contain_exec('C:\\bin\\foo') }
      it('on !windows', unless: os_facts[:osfamily] == 'windows') { is_expected.to contain_exec('/bin/foo') }
    end
  end
end
```
I couldn't get it to break. I *can* reproduce it with rabbitmq, as well as the [staging](https://forge.puppet.com/puppet/staging) module alone, whose tests throw the exact same error.

I've poked around at the staging module, but its test suite would need an overhaul to start attacking this.

**Comment by TraGicCode** [comment]
@DavidS closing this since this is resolved thanks to @wyardley removing puppet-staging from the rabbitmq module
