### ISSUE TITLE
Cannot load win32ole on non-windows os

### ISSUE THREAD

**Issue by TraGicCode** [rodjek/rspec-puppet#609]
We have a bunch of a windows machines and were wanting to run the rspec tests on an ubuntu machine with jenkins.  Jenkins is currently complaining it cannot finr the win32ole gem.  I understand this gem will not exist on a non-windows system but it looks like puppet-rspec is trying to do some sort of monkey patching by looking at the stacktrace.  Is this a bug or something that can or cannot be implemeneted to work?

 ```
 12) role::windowsworkstation should compile into a catalogue without dependency cycles should compile into a catalogue without dependency cycles
      Failure/Error: it { is_expected.to compile }

      LoadError:
        cannot load such file -- win32ole
      # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.8/lib/rspec-puppet/monkey_patches.rb:275:in `require'
      # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.8/lib/rspec-puppet/monkey_patches.rb:275:in `require'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/wmi.rb:18:in `connect'
      # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/wmi.rb:31:in `execquery'
```

**Comment by DavidS** [comment]
That's a duplicate of #599: platform dependent facts being loaded, when they should be mocked.

**Comment by TraGicCode** [comment]
Going to verify and close this if this is indeed the same issue which is what it sounds like.  Thanks!

**Comment by TraGicCode** [comment]
closing since this is a duplicate

**Comment by TraGicCode** [comment]
Duplicate of #599
