### ISSUE TITLE
Pretending is not working with https://github.com/grosser/parallel_tests

### ISSUE THREAD

**Issue by TraGicCode** [rodjek/rspec-puppet#612]
@DavidS Have any ideas why pretending would not work correctly when running the spec tests in parallel?

voxpupuli/puppet-stackify#8

**Comment by rodjek** [comment]
This is an interesting one. It's not actually related to parallel_tests at all, but using parallel_tests makes it more visible.

Running `bundle exec rspec spec/classes/install_spec.rb` by itself shows the same error, but not if the init_spec is run in the same process before it `bundle exec rspec spec/classes/init_spec.rb spec/classes/install_spec.rb`, so something is setting up a state in the init tests that the install tests need and it's bleeding through.

**Comment by rodjek** [comment]
Resolved by #608
