### ISSUE TITLE
Rspec fails when testing a class with a lambda function

### ISSUE THREAD

**Issue by danmurray2020** [rodjek/rspec-puppet#613]
I have come across this twice were the rspec tests fails to parse lambda functions in the code.
`$array = filter(split($::fact, '[, ]')) |$x|  { $x =~ /^\S+$/ }`

returns the following error
`puppet::Error: Could not match |$x|`

This code works fine on its own, but when run through the rake task it fails to evaluate the variable. 

The actual rspec test is just doing a compile all dependencies and sets the $::fact. Apologies if lacking information, just though I would post to see if this was something that was supported or a known bug. Running rspec-puppet 2.6.9 and puppet 3.6.2

**Comment by rodjek** [comment]
@danmurray2020 Have you [configured rspec-puppet](http://rspec-puppet.com/documentation/configuration/#parser) to use the Puppet 3.x `future` parser?

**Comment by madAndroid** [comment]
We're experiencing the same problem with the `2.6.9` release - if we pin to `2.5.0`, then the problem no longer occurs. We've got `parser = 'future'` set in the `spec_helper.rb`, and this works with `2.5.0`, but not with `2.6.0`

**Comment by rodjek** [comment]
@danmurray2020 @madAndroid Can you please create a simple repo that recreates the failure and link it here?
