### ISSUE TITLE
Converts camelcase variable names to lowercase

### ISSUE THREAD

**Issue by alexharv074** [rodjek/rspec-puppet#622]
Given this manifest:

```
class foo (
  $fooBar,
) {
  notify { "Got ${fooBar}": }
}
```

This spec file:

```
require 'spec_helper'

describe 'foo' do
  let(:params) do
    {
      'fooBar' => 'baz',
    }
  end
  it 'write catalog' do
    File.write('foo.json', PSON.pretty_generate(catalogue))
  end
end
```

I end up with this in the catalog:

```
    {
      "type": "Class",
      "title": "Foo",
      ...
      "parameters": {
        "foobar": "baz"
      }
    },
```

That is, the parameter `fooBar` has been downcased as `foobar`.

Is it a bug?

**Comment by alexharv074** [comment]
Actually, I think it's probably the Puppet compiler that does this, not Rspec-puppet.

**Comment by rodjek** [comment]
Yeah, rspec-puppet shouldn't be downcasing any parameter names. What version of puppet are you running that test against?

**Comment by alexharv074** [comment]
Latest everything:

```
$ for i in puppet rspec-puppet ; do bundle show $i ; done 
/Library/Ruby/Gems/2.0.0/gems/puppet-5.3.3-universal-darwin
/Library/Ruby/Gems/2.0.0/gems/rspec-puppet-2.6.9
```

**Comment by alexharv074** [comment]
Intriguing.

Using manifest:

```
class foo (
  $fooBar,
  $foobar,
) {
  notify { "Got '${fooBar}' and '${foobar}'": }
}
```

And test:

```
require 'spec_helper'

describe 'foo' do
  let(:params) do
    {
      'fooBar' => 'baz',
      'foobar' => 'BAZ',
    }
  end
  it 'write catalog' do
    File.write('foo.json', PSON.pretty_generate(catalogue))
  end
end
```

I end up with these in the catalog:

```
     {
      "type": "Class",
      "title": "Foo",
     ...
      "parameters": {
        "foobar": "BAZ"
      }
    },
```

I.e. because both params are the same when downcased, one clobbers the other.

The parameter that ends up documented in catalog is the first one I pass in the params hash in the spec file.

However, Puppet still "works"; I also have this in the catalog:

```
    {
      "type": "Notify",
      "title": "Got 'baz' and 'BAZ'",
      ...
    }
```

Likewise, if I puppet apply it, I get the right output.

**Comment by rodjek** [comment]
@alexharv074 I've been looking into this and this behaviour is indeed internal to Puppet. The [documentation](https://puppet.com/docs/puppet/5.3/lang_resources_advanced.html#full-syntax) states that the resource attributes should be lowercase words.

Given that, I'd say the `Class[Foo]` parameters only listing `foobar` in the catalogue is the correct behaviour. The compiler using both values when constructing the resources in the scope of the class feels like a bug though, so I'll close this issue on rspec-puppet and refer it to the Puppet Language team.

**Comment by hlindberg** [comment]
Expected? yes. 
Desired? IMO no, not giving value to users

What we could do in the compiler is to add a validation (warning or error if --strict is on) if a class has parameters that only differ by case
