### ISSUE TITLE
Documentation for Testing Loops

### ISSUE THREAD

**Issue by jcitarello** [rodjek/rspec-puppet#623]
Hi, 

I am trying to find documentation on how to test loops with rspec, but am having trouble finding it.  If anyone has a link to share, or could perhaps provide an example I would be very appreciative!

For example:

$apps = ['app1','app2','app3']

$apps.each | String $app| {
  package { "${name}-${app}":
     name   => $app,
     ensure => 'installed',
  }
}

**Comment by rodjek** [comment]
Something like this should work (just a normal ruby loop through an array).

```ruby
describe 'myclass' do
  ['app1', 'app2', 'app3'].each do |app|
    it { is_expected.to contain_package("whatevernameis-#{app}").with_ensure('installed') }
  end
end
```

**Comment by jcitarello** [comment]
Pefect! Thank you.,
