### ISSUE TITLE
scheduled_task trigger seems to break rspec-puppet - undefined method validate_trigger for nil:NilClass

### ISSUE THREAD

**Issue by jessereynolds** [rodjek/rspec-puppet#625]
Performing rspec testing of a puppet class containing a `scheduled_task` resource fails with the following error message if it contains the `trigger` parameter: 

```
failed: rspec: ./spec/classes/sausage_spec.rb:8: error during compilation: Parameter trigger failed on Scheduled_task[foo]: Validate method failed for class trigger: undefined method `validate_trigger' for nil:NilClass at /Users/jesse/src/puppet/tmp/pdk_test/sausage/spec/fixtures/modules/sausage/manifests/init.pp:10
  sausage on windows-2012 R2-x64 should compile into a catalogue without dependency cycles
  Failure/Error:
        let(:facts) { os_facts }

        it { is_expected.to compile }
      end
    end
```

**Comment by asedge** [comment]
I get a different error:
```
  1) scheduled_task_failure on windows-2012 R2-x64 should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile.with_all_deps }
       error during compilation: Parameter trigger failed on Scheduled_task[test]: Validate method failed for class trigger: uninitialized constant Win32 at /home/sean/dev/scheduled_task_failure/spec/fixtures/modules/scheduled_task_failure/manifests/init.pp:2
     # ./spec/classes/schedule_task_failure_spec.rb:7:in `block (4 levels) in <top (required)>'
```

What version of rspec-puppet are you using?  You may want to share your Puppet code and test so it can be reproduced.

**Comment by asedge** [comment]
@rodjek Here's another example module that shows rspec failures when testing a `scheduled_task` on Linux: https://github.com/asedge/scheduled_task_failure.  If you look at the `spec_helper.rb` and uncomment the constant definitions the tests will pass.  I'm hopeful you have a better way of achieving the same goal.

**Comment by rodjek** [comment]
@jessereynolds can you send me a copy of the `sausage` class (or point me to a repo) that is being tested so that I can reproduce the bug?

@asedge Yep, unfortunately we can't just install and use Win32::TaskScheduler on non-Windows hosts as it uses FFI to call native Windows methods. I think what I'll end up doing is similar to your solution and embed a fake `Win32::TaskScheduler` class in rspec-puppet with a complete copy of all the constants defined in it.
