### ISSUE TITLE
v2.6.4 cause "Could not find the daemon directory (tested [/etc/sv,/var/lib/service])"

### ISSUE THREAD

**Issue by hashar** [rodjek/rspec-puppet#629]
When bumping rspec-puppet [2.6.3 to 2.6.4](https://github.com/rodjek/rspec-puppet/compare/v2.6.3...v2.6.4) I have been blessed with:
```
Warning: Found multiple default providers for service: runit, debian, redhat; using runit
     RuntimeError:
       Could not find the daemon directory (tested [/etc/sv,/var/lib/service])
```

That is with puppet `4.8.2` on a Debian Stretch (version 9).

Based on Puppet lib/puppet/provider/service/*.rb it does not seem to recognize the default service provider for Stretch:
```
systemd.rb:  defaultfor :operatingsystem => :debian, :operatingsystemmajrelease => "8"
```

**Comment by hashar** [comment]
Since I am targetting Debian Jessie (version 8) I have just set a few more facts:
```
     let(:facts) { {
         :initsystem => 'systemd',
+        :operatingsystem => 'debian',
+        :operatingsystemmajrelease => 8,
         :lsbdistrelease => '8.9',
         :lsbdistid => 'Debian',
     } }
```

And that fixed it.  Most probably one can upgrade Puppet to a version that takes in account Debian Stretch (v9) and that would fix it as well. Though when targetting a specific operating system it is safer to set all the needed facts.


The reason the issue appeared in v2.6.4 is because of 308d0166cbd9dc75f6535ee1d0cf09c781fbc0b2 which actually is a good thing.

**Comment by hashar** [comment]
Giuseppe Lavagetto pointed me at https://github.com/mcanevet/rspec-puppet-facts which sets all the proper facts automagically.

**Comment by cdenneen** [comment]
I had commented about this in the Slack #puppet-dev channel... not sure if @rodjek you have any ideas... running latest versions and getting this error on Ubuntu 14.04 which isn't systemd:

https://puppetcommunity.slack.com/files/U11JKRSCF/FAJBTEB7D/-.pl

**Comment by baurmatt** [comment]
@cdenneen Did you get this issue fixed for Ubuntu 14.04? Running into the same problem even thought we're using rspec-puppet-facts/facterdb :(

**Comment by pegasd** [comment]
Fired again with Puppet `5.5.6`.
Not sure if it should be fixed here or in `puppet` itself.

**Comment by baurmatt** [comment]
Found our problem. Turns out, we had a `spec/classes/init_gentoo_spec.rb` and `spec/classes/init_spec.rb`. Somehow this conflicted an threw the `Could not find the daemon directory (tested [/etc/sv,/var/lib/service])` error. This could be solved, besides using rspec-puppet-facts, by moving everything in `spec/classes/init_spec.rb`.
