### ISSUE TITLE
Testing Windows file resources that are symlinks when pretending to be Windows

### ISSUE THREAD

**Issue by asedge** [rodjek/rspec-puppet#632]
I created a repository that demonstrates the problem and the `spec_helper.rb` has a workaround we are currently using: https://github.com/asedge/windows_manages_symlinks_failure

Steps to reproduce:
1. Clone and change directory into the repository on a non-Windows machine.
2. Install the bundle: `bundle install --path vendor/bundle`
3. Run the tests: `bundle exec rake spec`

**Comment by rodjek** [comment]
@asedge Thanks for the repro case! Could you check out the changes in #635 and see if they solve the issue for you?

**Comment by asedge** [comment]
Thanks @rodjek!  I'll try this out tomorrow and let you know.

**Comment by asedge** [comment]
@rodjek Sorry for the delay!  This is looking pretty good now too, thanks!

**Comment by rodjek** [comment]
@asedge no worries, thanks for testing it out
