### ISSUE TITLE
Allow testing with `server_facts`

### ISSUE THREAD

**Issue by fatmcgav** [rodjek/rspec-puppet#642]
Using Puppet [`server_facts`](https://puppet.com/docs/puppet/5.3/lang_facts_and_builtin_vars.html#serverfacts-variable) breaks when attempting to test the code via rspec-puppet.

**Comment by fatmcgav** [comment]
At a quick glance of the rspec-puppet code, I _think_ it should be a case of setting up the `server_facts` hash in [`build_catalog_without_cache`](https://github.com/rodjek/rspec-puppet/blob/master/lib/rspec-puppet/support.rb#L340).

`server_facts` is constructed in Puppet code here: https://github.com/puppetlabs/puppet/blob/master/lib/puppet/indirector/catalog/compiler.rb#L392-L417
And is assigned to the `node` object via a call to [`add_server_facts`](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/node.rb#L162-L168).

So in theory, it doesn't look too hard to plumb through...

**Comment by jeefberkey** [comment]
We set `server_facts` like this in one of our tests:
```puppet
# from https://github.com/simp/pupmod-simp-simp/blob/master/spec/classes/init_spec.rb#L29
let(:facts) do
    os_facts[:server_facts] = {
      :servername => 'puppet.bar.baz',
      :serverip   => '1.2.3.4'
    }
    os_facts
end
```

And I get an error that looks like:
```
     Failure/Error: it { is_expected.to compile.with_all_deps }
       error during compilation: Attempt to assign to a reserved variable name: 'server_facts' on node hostname.domain
```
Versions:
Puppet: 5.3.3
Ruby: 2.1.9
puppetlabs_spec_helper (2.6.1)
rspec-puppet (2.6.9)
rspec-puppet-facts (1.8.0, 0.12.0)

**Comment by fatmcgav** [comment]
@jeefberkey I've stuck an initial PR up in #643 

It works for me testing locally, but would be good to get someone else to try it :) 
I've just got rspec-puppet checked out locally, and then pointed the Gemfile at a path for it...
