### ISSUE TITLE
Notify as Resource Attribute Failing

### ISSUE THREAD

**Issue by jcitarello** [rodjek/rspec-puppet#668]
Similar to the issues I am seeing with require as an attribute, I am now seeing the same/similar issue with notify. I know that I have done this before without issue, but can't figure out why it's failing rspec.

Please advise, thanks! 

Code:

init.pp
```
# Class: smo
class smo {
  include smo::config
  include smo::service
}
```
config.pp
```
  file { '/opt/NetApp/snapdrive/snapdrive.conf':
    source => 'puppet:///modules/smo/snapdrive.conf',
    mode   => '0644',
    notify => Class['smo::service'],
  }
```
rspec for smo_spec.rb
```
require 'spec_helper'

describe 'smo' do
    it { should contain_class('smo::config') }
    it { should contain_class('smo::service') }
end
```
rspec for config_spec.rb
```
require 'spec_helper'

describe 'smo::config' do
  it{ is_expected.to contain_file('/opt/NetApp/snapdrive/snapdrive.conf') }

  it{ is_expected.to contain_file('/opt/NetApp/smo/properties/smo.config') }

  it{ is_expected.to contain_file('/opt/NetApp/smo/cmode_profile') }

  it{ is_expected.to contain_file('/opt/NetApp/smo/cmode_profile/cmode_profile.config') }
end
```

Rake Spec Error:
```
 1) smo::config should contain File[/opt/NetApp/snapdrive/snapdrive.conf]
     Failure/Error: it{ is_expected.to contain_file('/opt/NetApp/snapdrive/snapdrive.conf') }
     
     Puppet::Error:
       Could not find resource 'Class[Smo::Service]' in parameter 'notify' at /home/me/Projects/modules/smo/spec/fixtures/modules/smo/manifests/config.pp:11 on node [mynode]
```

**Comment by rodjek** [comment]
When you do `describe 'smo::config' do ... end`, rspec-puppet is testing `Class[smo::config]` as a discrete unit (as if you had a manifest that only contained the line `include smo::config`.

Going by the manifest for `Class[smo::config]`, it does not itself include `Class[smo::service]` and so it does not exist in the test catalogue. If you want to avoid refactoring your manifests, you can work around this by defining a [pre condition](http://rspec-puppet.com/documentation/classes/#specifying-code-to-include-before) in your spec test that contains `include smo::service`.
