### ISSUE TITLE
Can't stub Facter.fact when testing custom fact

### ISSUE THREAD

**Issue by fatmcgav** [rodjek/rspec-puppet#673]
I'm writing a custom fact, which has the following `confine`:
```ruby
  confine :dmi do |v|
    v['product']['name'] == 'Openstack Nova'
  end
```

However when I try and stub the `:dmi` fact in my unit test, it fails :( 
fact_spec.rb: 
```ruby
describe 'Facter::Util::Fact::custom_fact', :type => :fact do

  before(:each) {
    # Clear facter each run
    Facter.clear
    # Over-ride :dmi['product']['name'] value
    # Facter.fact(:dmi).stubs(:value).returns('blah')
    Facter.fact(:dmi).stubs(:value).returns({'product' => {'name' => 'Openstack Nova'}})
  }
...
```

And the error is:
```
 Failures:

  1) Facter::Util::Fact::custom_fact with a valid response should return a hash
     Failure/Error: Facter.fact(:dmi).stubs(:value).returns('blah')

     Mocha::StubbingError:
       can't stub method on frozen object: nil
```

If I replace `:dmi` with `:kernel` in my `before (:each)` block, then the code doesn't error... 

So that leads me to believe that rspec-puppet is possibly allowing stubbing of 'certain' facts? 
Or could this an issue with the version of facter being used, and the `dmi` fact not being present?

Ideas?

Gem versions:
```
gem list |egrep 'rspec-puppet|^puppet |facter'
facter (2.5.1)
facterdb (0.5.0)
puppet (5.3.3)
rspec-puppet (2.6.9)
rspec-puppet-facts (1.9.0, 1.8.0)
```

**Comment by fatmcgav** [comment]
As discussed with @rodjek on Slack, this is due to the `:dmi` fact not being present in the version of `facter` used for testing.
```ruby
bundle exec ruby -e "require 'facter'; p Facter.fact(:dmi)"
nil
```

The work-around is to do a `Facter.add`, e.g.:
```ruby
    if Facter.fact(:dmi).nil?
      Facter.add(:dmi) { setcode { {'product' => {'name' => 'Openstack Nova'}} } }
    else 
      Facter.fact(:dmi).stubs(:value).returns({'product' => {'name' => 'Openstack Nova'}})
    end
    Facter.flush
```

Cheers for the suggestion @rodjek ...

**Comment by tthayer** [comment]
I've been trying to do something similar with a custom fact in one of my modules and the adding the fact or stubbing it with a known value does nothing to actually test the fact does the right thing. I feel like there is a gap in my knowledge that is preventing me from implementing my testing correctly but this categorically feels like the wrong way to approach it.
