### ISSUE TITLE
Enable Both Actual and Expected Results in test report?

### ISSUE THREAD

**Issue by darkn3rd** [rodjek/rspec-puppet#683]
Given that we are using ruby to test puppet code, it would be nice to enable the string that was received, not just the expected.  Is there an easy way to enable this? 

My current output (actual results) looks like this:

```
  1) dk_elasticsearch::config on ubuntu-16.04-x86_64 should enable limits.conf for processes started by init.d on trusty
     Failure/Error: is_expected.to contain_exec(command)
       expected that the catalogue would contain Exec[sed -r -i 's/#? +(session +required +pam_limits.so)//' /etc/pam.d/su]
     # ./spec/classes/config_spec.rb:14:in `block (4 levels) in <top (required)>'
```

Test Snippet

```ruby
it 'should enable limits.conf for processes started by init.d on trusty' do
  command = "sed -r -i 's/#?\s+(session\s+required\s+pam_limits.so)/\1/' /etc/pam.d/su"
  is_expected.to contain_exec(command)
end
```

Puppet Snippet:

```puppet
exec {"sed -r -i 's/#?\\s+(session\s+required\\s+pam_limits.so)/\\1/' /etc/pam.d/su": }
```

**Comment by rodjek** [comment]
In this case, there's nothing easy to compare it to as it's an existence check (does this resource exist in the catalogue or not). When the parameters of a resource differ, we show both actual and expected as there is something to compare.

We could perhaps show all the resources of the tested type in the output in this case though (so for your example, all the `Exec` resources) but it might get unwieldy for catalogues with a lot of resources.

**Comment by pegasd** [comment]
I would advise to use a short descriptive name for the exec resource and put the command as a parameter. Then you'd see the difference.

**Comment by darkn3rd** [comment]
So if I did this with the descriptive name and separated the command I could get the result?  I was hoping for "expected" . "but got...".

The use case is string interpolation in Puppet vs. Ruby, such a test could help iron out such errors.

**Comment by rodjek** [comment]
As @pegasd mentioned, the best solution is to refactor your exec resource so that it has a static name and move the command string into the `command` attribute.

```puppet
exec { 'enable limits.conf in pam':
  command => "sed -r -i 's/#?\\s+(session\s+required\\s+pam_limits.so)/\\1/' /etc/pam.d/su",
}
```

```ruby
it do
  is_expected.to contain_exec('enable limits.conf in pam').with(
    'command' => "sed -r -i 's/#?\s+(session\s+required\s+pam_limits.so)/\1/' /etc/pam.d/su",
  )
end
```

This way the Exec resource always exists in the catalogue with a predictable name and the command string is now a diffable attribute.
