### ISSUE TITLE
`confdir` on Windows

### ISSUE THREAD

**Issue by asedge** [rodjek/rspec-puppet#686]
I believe [this](https://github.com/rodjek/rspec-puppet/blob/11a8dfde3d1827b3431e89c8e166f09fbd3b735a/lib/rspec-puppet.rb#L41) `confdir` setting is being translated to `C:\etc\puppet` on Windows.  If `C:\etc` does not exist Puppet tries to create it using this method: https://github.com/puppetlabs/puppet/blob/8afe8190cca0263619b79e64bd2ff74241881286/lib/puppet/settings.rb#L359-L366.  If you're not an administrator on Windows, we are losing admin rights where I work, the `FileUtils.mkdir_p` fails and the test suite bombs.  I have worked around this by doing this in my `spec/spec_helper.rb`:
```
if RSpec.configuration.platform == :windows
  RSpec.configure do |c|
    c.confdir = 'C:/puppet'
  end
end
```
Which works when people have the right `spec_helper.rb` but that's not always the case.  I'm hoping this gem could support something for us poor Windows users who are not admins.

**Comment by rodjek** [comment]
Yikes, yeah there's a few settings there that make some unfortunate platform assumptions that I'd completly forgotten about. Thanks @asedge, I'll get them fixed up in the next release so that you don't have to work around this in the future!

**Comment by asedge** [comment]
Thanks @rodjek! If there's anything I can do to help let me know!
