### ISSUE TITLE
Question about puppet variable scope

### ISSUE THREAD

**Issue by gerases** [rodjek/rspec-puppet#690]
Hello!

I have a define that is structured like this:

```
define x() {
  $some_var = 'test'
  y { 'some_name_var':  }
}
```

the `y` define uses a template and that template uses `@some_var`. When I run rspec-puppet tests against `x()`, the template does see `@some_var`.

... but when i run puppet for real, puppet master returns the template with `@some_var` empty.

This is very puzzling to me. My expectation is that `@some_var` shouldn't be visible in either.

Any ideas?

Thanks again,
  Sergei

**Comment by rodjek** [comment]
What version of Puppet are you running the tests against? Also, is it the same version that is on your puppet master?

**Comment by gerases** [comment]
Hi @rodjek,

You know it's been long enough for the details of this to vacate my brain :) I'm ok with closing this.

Thank you all the same,
  Sergei
