### ISSUE TITLE
rspec-puppet fails on nested data type aliases

### ISSUE THREAD

**Issue by tuxmea** [rodjek/rspec-puppet#692]
first type alias:
`
type Core_stdlib::Port = Integer[0,1024]
`
second type alias:
`
type Globals::Uri = Struct[{
  'fqdn' => String,
  'port' => Core_stdlib::Port,
}]
`
rspec-puppet fails with error message:
`
Found value has wrong type, references an unresolved type 'Core_stdlib::Port'
`
Puppet agent is working as expected. rspec-puppet throws error.

**Comment by rodjek** [comment]
@tuxmea I'm not able to reproduce this locally. Is the `core_stdlib` module available in the `spec/fixtures` directory?

**Comment by pegasd** [comment]
This could also be due to forgetting to add `core_stdlib` to dependencies list in `metadata.json` file.

**Comment by tuxmea** [comment]
I can check in two weeks (when I am back at customer). Maybe it is related to the missing dependency in metadata.json (which is a nightmare my 5cent)

**Comment by tuxmea** [comment]
could not reproduce. Everything is working as it should. Closing issue.
