### ISSUE TITLE
Puzzling error

### ISSUE THREAD

**Issue by SwampFalc** [rodjek/rspec-puppet#763]
I'm trying to unittest a few modules I wrote and I run into a serious error whenever I wish to include another module into one of mine.

Here's a gist with what I believe to be the relevant files: https://gist.github.com/SwampFalc/c333c842f05c3106aac7f4ce9771dfbf

The error I get is also in there, though I will point out I'm using pdk (1.12) and not standalone rspec-puppet.

Note that actually applying the module works without a single error. So am I doing something wrong, or is this an rspec-puppet bug?

**Comment by kjetilho** [comment]
your fixtures says the systemd module can be gotten from your source_dir(!)

**Comment by rodjek** [comment]
As @kjetilho said, the problem is in your `.fixtures.yml`. If you remove the `symlinks` hash entirely and let it setup the symlink using the default behaviour it should work for you.
