### ISSUE TITLE
Allow multiple entries in modulepath

### ISSUE THREAD

**Issue by jerger** [rodjek/rspec-puppet#78]
Hi,

while developing puppet modules with dependencie to other modules it would be nice to use a modulepath with mor than one directory-entry. For defining modulepath I use:

c.module_path = File.join(File.dirname(**FILE**), '../../')

Best regards,
jerger

**Comment by alexharv074** [comment]
@tcolgate @rodjek It certainly doesn't seem to work for me either.

**Comment by alexharv074** [comment]
Ok - I figured it out - according to the setup documentation, you're meant to set your module path to spec/fixtures/modules and then if other modules are needed, you have to create symbolic links.  The puppetlabs_spec_helper gem's .fixtures.yml file can then be used to create all the links.  Seems like a bit of a hack, but if that's what everyone's doing I guess that's what I'll do.

**Comment by DavidS** [comment]
Sad, but true. I'm planning to move more and more stuff from puppetlabs_spec_helper to rspec-puppet in the coming months, so the former can go away.

**Comment by alexharv074** [comment]
I think it would be good if a feature was added to simply have rspec-puppet allow multiple entries in the module path, as @jerger said.  In that case you could have R10K or librarian-puppet load your shared modules, and local module/s could be loaded directly without any need for symbolic links.
