### ISSUE TITLE
be_valid_types doesn't seem to be able to catch exception

### ISSUE THREAD

**Issue by faxm0dem** [rodjek/rspec-puppet#785]
I'm migrating a unit test for a ruby type from an older rspec version.
If I'm not mistaken, the following should be equivalent:

### old style
```ruby
expect { described_type.new(name: 'test', force: 'nope') }.to raise_error(Puppet::Error)
 ```

### new style
```ruby
expect {be_valid_type.with_set_attributes({:force => 'nope'})}.to raise_error(Puppet::Error)
```

However, while the former works as expected (test succeeds), the latter fails with:

```
     Failure/Error: expect { be_valid_type.with_set_attributes({:force => 'nope'})}.to raise_error
       expected Exception but nothing was raised
```

**Comment by rodjek** [comment]
Hi @faxm0dem,

That matcher does raise exceptions on invalid parameter values and is tested [here](https://github.com/rodjek/rspec-puppet/blob/ffa754a058f603f85a38d78d89b27f33b81e893c/spec/types/valid_provider_spec.rb#L70-L79) (the fake type being tested can be viewed [here](https://github.com/rodjek/rspec-puppet/blob/ffa754a058f603f85a38d78d89b27f33b81e893c/spec/fixtures/modules/fake_type/lib/puppet/type/fake.rb)). Can you provide a more complete example to reproduce the scenario you're seeing?

**Comment by faxm0dem** [comment]
you can check travis for the above failure for more details:

https://travis-ci.org/ccin2p3/puppet-cpan/jobs/652374296?utm_medium=notification&utm_source=github_status

**Comment by faxm0dem** [comment]
I guess I forgot the `should` statement (sorry, rspec is kind of black magic to me)
