### ISSUE TITLE
Breaking changes added in 2.8.0 causing failures with PDK 1.18.1 

### ISSUE THREAD

**Issue by 4derstap** [rodjek/rspec-puppet#816]
When using Sensitive in your modules then builds can break as per [changelog of 2.8.0](https://rspec-puppet.com/changelog/#280).

Instead of increasing the minor version I rather expect to increase the major version due to the breaking changes. The Gemfile.lock is generated with this dependency:

```
      rspec-puppet (>= 2.3.2, < 3.0.0)
```

Increasing the major version for this release would have prevented our builds to break.

**Comment by DavidS** [comment]
Thank you for your feedback.
